### ISSUE TITLE
Prepare_data 文档优化

### ISSUE THREAD

**Issue by tink2123** [PaddlePaddle/docs#194]
**背景：**
准备数据作为使用指南的第一部分也是非常重要的一个环节，希望起到更清晰的指导意义。目前的文档结构与内容存在几个小问题仍需优化：

**优化问题：**
1）准备数据概览页，与recordio相关的内容需要去掉并修改相关文字，例如：
![default](https://user-images.githubusercontent.com/31891223/47131678-9e8ff600-d2d2-11e8-9511-f75874a5c913.png)
2）numpy array这篇文档和其他两篇的区别是什么？能否重新梳理一下结构？
3）python reader和pyreader 同步/异步无法区分，是否需要修改标题？

**Comment by luotao1** [comment]
python reader和pyreader 同步/异步无法区分：可能不是修改标题就能解决这个问题，是否需要修改代码里命名？
