### ISSUE TITLE
There is problem about sequence_expand op doc.

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/docs#197]
![image](https://user-images.githubusercontent.com/5595332/47198762-b170fc00-d3a0-11e8-992c-e6dd1c45b0d1.png)

There is problem about the lod of the cases. The right case should be:

![image](https://user-images.githubusercontent.com/5595332/47198820-fd23a580-d3a0-11e8-8f7a-10b41eeafdfa.png)

Which can be infer from:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/sequence_expand_op.cc#L122

**Comment by kuke** [comment]
It's OK. You can treat the LoD in the original doc as the length-based LoD, instead of the offset-based one. In the Python end, we prefer to let users get used to the length-based LoD.

**Comment by NHZlX** [comment]
我看到 c++端的op都是使用的 offset-based。是python端会将 length-based LoD改成offset-based么？

**Comment by luotao1** [comment]
python端已经改成length-based, C++端也要改成length-based。

**Comment by NHZlX** [comment]
@luotao1 原来这样。我之前对sequence 这块不是太熟悉，想了解这个op，发现两边的文档不一致就会感觉到疑问。我感觉对其他的刚接触这块的同学也应该会遇到这个问题，所以会影响到用户体验，感觉有必要进行fix
