### ISSUE TITLE
【API Guide-RNN】 内容讨论

### ISSUE THREAD

**Issue by tink2123** [PaddlePaddle/docs#228]
**背景：**
需补充一篇 RNN 的 api_guide，讨论此篇 guide 中应说明哪些API。

**暂定相关API：**
dynamicRNN、staticRNN、dynamic_lstm、dynamic_lstmp、dynamic_gru、gru_unit、beem_search_decode、lstm_unit、beam_search

如需调整，请老师指出。

**Comment by shanyi15** [comment]
辛苦review～ ～ @luotao1

**Comment by shippingwang** [comment]
> **背景：**
> 需补充一篇 RNN 的 api_guide，讨论此篇 guide 中应说明哪些API。
> 
> **暂定相关API：**
> dynamicRNN、staticRNN、dynamic_lstm、dynamic_lstmp、dynamic_gru、gru_unit、beem_search_decode、lstm_unit、beam_search
> 
> 如需调整，请老师指出。

请指点下NN具体应该包括什么。NN中有很多是属于数学操作，conv，pool，和现在加入的RNN等。NN中需要写的是除去这些文档的其他api么～

**Comment by luotao1** [comment]
> NN具体应该包括什么

NN是包括其他所有api_guide的上级目录，即NN是一级目录，介绍fluid有多少类型的api_guide，分别指向这些api_guide.rst。

> NN中需要写的是除去这些文档的其他api

所有api都要找到各自的位置，NN中不出现api介绍，只出现api_guide的介绍。因此，NN可以最后再写。

**Comment by shippingwang** [comment]
> > NN具体应该包括什么
> 
> NN是包括其他所有api_guide的上级目录，即NN是一级目录，介绍fluid有多少类型的api_guide，分别指向这些api_guide.rst。
> 
> > NN中需要写的是除去这些文档的其他api
> 
> 所有api都要找到各自的位置，NN中不出现api介绍，只出现api_guide的介绍。因此，NN可以最后再写。

收到～

**Comment by shanyi15** [comment]
please refer to https://github.com/PaddlePaddle/FluidDoc/issues/291 for more details.
