### ISSUE TITLE
Which type of APIs should Print layer belong to 

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/docs#239]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py#L44

Now it is in the `control_flow.py`, but it doesn't belong to any types of control flow.

**Comment by luotao1** [comment]
@kuke @shanyi15 Print的具体位置，应该从API接口方面考虑，不是文档问题。

**Comment by panyx0718** [comment]
tensor.py seems better

**Comment by shanyi15** [comment]
close for this question belongs to API interface, please open issue in Paddle repo, thanks!
