### ISSUE TITLE
《timeline工具简介》多机部分优化

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/docs#283]
有用户反馈：
“
http://www.paddlepaddle.org/documentation/docs/zh/1.1/advanced_usage/development/profiling/timeline_cn.html#
更新一下吧，多卡下 fluid.ExecutionStrategy() num_threads 不设成 1 会卡住”

定位原文：https://github.com/PaddlePaddle/FluidDoc/blob/release/1.1/doc/fluid/howto/optimization/timeline_cn.md

请 @typhoonzero @gongweibao 看下，谢谢！

**Comment by typhoonzero** [comment]
这个 应该是考虑解决在多卡下开启profiler  hang住的bug，文档暂时不加说明了，优先考虑修复这个bug。所以先close这个issue了。
