### ISSUE TITLE
如何基于此项目生成一份离线的paddle文档

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/docs#3552]
来自https://github.com/PaddlePaddle/Paddle/issues/33158

**Comment by wadefelix** [comment]
您好，此项目文档均由 md 或 rst 格式写成，对直接阅读还是比较友好的，clone下来即可，也方便对文档进行更新。
而且github的渲染也很OK。

若想本地进行更友好的阅读与编写，欢迎使用jupyterhub镜像 `paddlepaddle/paddle:2.1.0-jupyter`，内已安装paddle和jupyter（用户名`paddle`,密码`hipaddle`），可以运行 https://github.com/PaddlePaddle/book 项目的ipynb文件，也可以编译md和rst文件。

启动此镜像的命令：
```bash
docker run -d -p 80:80 -e USER_PASSWD=hipaddle -v $(pwd):/home/paddle paddlepaddle/paddle:2.1.0-jupyter
## 注：映射到容器的主机目录必须具有写权限。建议创建一个777权限的空目录专门用来存在此镜像容器生成的ipynb文件等，且建议不要将主机的home目录映射到容器内。
```
若您使用本机启动，您便可以浏览器打开 http://localhost/ 打开此jupyter实例。
Enjoy Paddle!

若有任何疑问，包括且不仅限于paddlepaddle/docker/git/jupyter话题，欢迎交流。
