### ISSUE TITLE
Python API注释模版

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/docs#383]
可以复制粘贴的那种，当下优先级非最高

**Comment by haowang101779990** [comment]
[python-doc examples_v1.zip](https://github.com/PaddlePaddle/FluidDoc/files/2620282/python-doc.examples_v1.zip)
第一块注释是提炼出的模板，后面四个是找的正常显示的示例（英文端正常显示），是个py文件方便复制粘贴，运行可打印出具体的说明
