### ISSUE TITLE
Speed of search is very slow!

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/docs#390]
![image](https://user-images.githubusercontent.com/10721757/49003694-6dda9080-f19d-11e8-9985-347f1c89b9ca.png)

**Comment by shanyi15** [comment]
That's because a necessary file index.js for search bar put on aws cannot be downloaded in mainland China for the network environment is quite bad. We're trying to move them to Baidu Cloud, this work is in process...

**Comment by shanyi15** [comment]
For this is a website issue, recommend to create issue [here](https://github.com/PaddlePaddle/Paddlepaddle.org/issues) ,thanks

**Comment by shanyi15** [comment]
It has been repaired, please have a try. :)

**Comment by shanyi15** [comment]
close for it has been repaired
