### ISSUE TITLE
写RFC时，还没有提PR，怎么填写这个RFC的PR链接

### ISSUE THREAD

**Issue by unseenme** [PaddlePaddle/docs#3989]
https://github.com/PaddlePaddle/docs/blob/41bdb6b80dd4619b8d0dbb5579fb21d4e1159497/docs/guides/10_contribution/rfcs.md?plain=1#L5

步骤是不是这样。
1 写RFC
2 提交RFC
3 提PR

在step3才能知道的PR链接，在step1的时候，是不是没法填写。不知道我理解得对不对。

**Comment by TCChenlong** [comment]
对的 可以先填 空，等提交PR后再补充PR链接~
