### ISSUE TITLE
【飞桨体验评测任务第一期】API文档问题列表

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/docs#4266]
##  一、背景

在今年1月，为了提升飞桨框架的易用性，并能够和开发者多样化的联动，共同打造优秀的开源生态，我们开展了第一期飞桨体验评测任务。第一期的重点方向是飞桨API文档及目录、安装模块，我们共收集到了210份开发者的反馈。其中有很多已经转为需求，进行研发中；此外，我们也精心挑选了一部分反馈，希望你可以加入到飞桨文档的建设中来。

## 二、参与方式

为了更好的参与到本次修复中，你可以参考如下的流程：
1、按格式回复本ISSUE，认领相关的API问题；
2、参考如下内容，进行文档修复：

- [中文API文档贡献指南 · PaddlePaddle/docs Wiki](https://github.com/PaddlePaddle/docs/wiki/%E4%B8%AD%E6%96%87API%E6%96%87%E6%A1%A3%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97)
- [英文API文档贡献指南 · PaddlePaddle/docs Wiki](https://github.com/PaddlePaddle/docs/wiki/%E8%8B%B1%E6%96%87API%E6%96%87%E6%A1%A3%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97)
- [Home · PaddlePaddle/docs Wiki](https://github.com/PaddlePaddle/docs/wiki)

3、提交PR，并在 PR内 @TCChenLong 进行 review；

**认领格式**

回复的格式为：

【昵称】：你的昵称

【序号】：你想要修复的问题的序号

【题目】：你想要修复的问题的题目

如：

【昵称】：TC.Long

【序号】：1

【题目】：paddle.add 文档问题

## 三、任务列表

| 序号 | 题目 | 认领人 |
| --- | --- | --- |
| 1 | [1、paddle.to_tensor 文档问题](https://github.com/PaddlePaddle/docs/issues/4237) |   |
| 2 | [2、paddle.vision.transforms.ToTensor 文档问题 ](https://github.com/PaddlePaddle/docs/issues/4238) | [笠雨聆月](https://github.com/Liyulingyue)( https://github.com/PaddlePaddle/docs/pull/4318 https://github.com/PaddlePaddle/Paddle/pull/40647 )   |
| 3 | [3、paddle.vision.transforms.Resize 文档问题](https://github.com/PaddlePaddle/docs/issues/4239) | [笠雨聆月](https://github.com/Liyulingyue)( https://github.com/PaddlePaddle/docs/pull/4319 https://github.com/PaddlePaddle/Paddle/pull/40719 )   |
| 4 | [4、paddle.vision.models.VGG 文档问题](https://github.com/PaddlePaddle/docs/issues/4240) |   |
| 5 | [5、paddle.vision.models.ResNet 文档问题](https://github.com/PaddlePaddle/docs/issues/4241) |   |
| 6 | [6、paddle.tile 文档问题](https://github.com/PaddlePaddle/docs/issues/4242) | [Nyakku Shigure](https://github.com/SigureMo)( https://github.com/PaddlePaddle/docs/pull/4321 https://github.com/PaddlePaddle/Paddle/pull/40731 )  |
| 7 | [7、paddle.summary 文档问题](https://github.com/PaddlePaddle/docs/issues/4243) |   |
| 8 | [8、paddle.stack 文档问题](https://github.com/PaddlePaddle/docs/issues/4244) |   [笠雨聆月](https://github.com/Liyulingyue)( https://github.com/PaddlePaddle/docs/pull/4320 https://github.com/PaddlePaddle/Paddle/pull/40722 ) |
| 9 | [9、paddle.optimizer.SGD 文档问题](https://github.com/PaddlePaddle/docs/issues/4245) | [Nyakku Shigure](https://github.com/SigureMo)( https://github.com/PaddlePaddle/docs/pull/4304 )  |
| 10 | [10、paddle.optimizer.Adam 文档问题](https://github.com/PaddlePaddle/docs/issues/4246) |   |
| 11 | [11、paddle.nn.MSELoss 文档问题](https://github.com/PaddlePaddle/docs/issues/4247) |   |
| 12 | [12、paddle.nn.LayerNorm 文档问题](https://github.com/PaddlePaddle/docs/issues/4248) |   |
| 13 | [13、paddle.nn.Flatten 文档问题](https://github.com/PaddlePaddle/docs/issues/4249) |   |
| 14 | [14、paddle.nn.Conv1D 文档问题](https://github.com/PaddlePaddle/docs/issues/4250) |   |
| 15 | [15、paddle.nn.AdaptiveAvgPool2D 文档问题 ](https://github.com/PaddlePaddle/docs/issues/4251) |   |
| 16 | [16、paddle.Model 文档问题](https://github.com/PaddlePaddle/docs/issues/4252) |   |
| 17 | [17、paddle.max 文档问题](https://github.com/PaddlePaddle/docs/issues/4253) | [RangeKing](https://github.com/RangeKing) ( https://github.com/PaddlePaddle/docs/pull/4328 )  |
| 18 | [18、paddle.index_select 文档问题](https://github.com/PaddlePaddle/docs/issues/4254) | [RangeKing](https://github.com/RangeKing) ( https://github.com/PaddlePaddle/docs/pull/4334 )  |
| 19 | [19、paddle.flatten 文档问题](https://github.com/PaddlePaddle/docs/issues/4255) |   |
| 20 | [20、paddle.distributed.alltoall 文档问题](https://github.com/PaddlePaddle/docs/issues/4256) |   |
| 21 | [21、paddle.distributed.all_gather 文档问题](https://github.com/PaddlePaddle/docs/issues/4257) |   |
| 22 | [22、paddle.device.set_device 文档问题](https://github.com/PaddlePaddle/docs/issues/4258) |   |
| 23 | [23、paddle.clip 文档问题](https://github.com/PaddlePaddle/docs/issues/4259) | [Nyakku Shigure](https://github.com/SigureMo)( https://github.com/PaddlePaddle/docs/pull/4299 )  |
| 24 | [24、paddle.cast 文档问题](https://github.com/PaddlePaddle/docs/issues/4260) |   |
| 25 | [25、paddle.matmul 文档问题 ](https://github.com/PaddlePaddle/docs/issues/4261) |   |
| 26 | [26、paddle.gather 文档问题](https://github.com/PaddlePaddle/docs/issues/4262) |   |
| 27 | [27、paddle.static.Executor 文档问题](https://github.com/PaddlePaddle/docs/issues/4263) |   |
| 28 | [28、paddle.concat 文档问题](https://github.com/PaddlePaddle/docs/issues/4264) |   |
| 29 | [29、paddle.io.BatchSampler 文档问题](https://github.com/PaddlePaddle/docs/issues/4265) |   |

再一次感谢你对飞桨的贡献！

**Comment by SigureMo** [comment]
【昵称】：Nyakku Shigure

【序号】：23

【题目】：paddle.clip 文档问题

【PR 链接】：
   - 中文：https://github.com/PaddlePaddle/docs/pull/4299
   - 英文：未修改

**Comment by SigureMo** [comment]
【昵称】：Nyakku Shigure

【序号】：9

【题目】：paddle.optimizer.SGD 文档问题

【PR 链接】：
   - 中文：https://github.com/PaddlePaddle/docs/pull/4304
   - 英文：https://github.com/PaddlePaddle/Paddle/pull/40479

**Comment by Liyulingyue** [comment]
【昵称】：笠雨聆月

【序号】：2

【题目】：paddle.vision.transforms.ToTensor 文档问题

【PR 链接】：

中文：https://github.com/PaddlePaddle/docs/pull/4307
英文：未修改

**Comment by liyongchao911** [comment]
【昵称】：Nicolas David

【序号】：7

【题目】：paddle.summary 文档问题

**Comment by Liyulingyue** [comment]
【昵称】：笠雨聆月

【序号】：3

【题目】：paddle.vision.transforms.Resize文档问题

【PR 链接】：

中文：https://github.com/PaddlePaddle/docs/pull/4319
英文：https://github.com/PaddlePaddle/Paddle/pull/40719

**Comment by Liyulingyue** [comment]
【昵称】：笠雨聆月

【序号】：8

【题目】：paddle.stack文档问题

【PR 链接】：

中文：https://github.com/PaddlePaddle/docs/pull/4320
英文：https://github.com/PaddlePaddle/Paddle/pull/40722

**Comment by SigureMo** [comment]
【昵称】：Nyakku Shigure

【序号】：6

【题目】：paddle.tile 文档问题

【PR 链接】：
   - 中文：https://github.com/PaddlePaddle/docs/pull/4321
   - 英文：https://github.com/PaddlePaddle/Paddle/pull/40731

**Comment by RangeKing** [comment]
【昵称】：RangeKing

【序号】：17

【题目】：paddle.max 文档问题

【PR 链接】：

 - 中文：https://github.com/PaddlePaddle/docs/pull/4328
 - 英文：未修改

**Comment by RangeKing** [comment]
【昵称】：RangeKing

【序号】：18

【题目】：paddle.index_select 文档问题

【PR 链接】：

 - 中文：https://github.com/PaddlePaddle/docs/pull/4334
 - 英文：未修改，目前已经使用Paddle API创建
