### ISSUE TITLE
paddle.tile文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4337]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tile_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/tile_en.html

### 红线问题

- API的代码部分，增加paddle的版本检查，防止因版本不一致导致的结果不一致
- 中英文文档内容不一致：
   - 中文文档中最后一部分是“使用本API的教程文档”， 给出了使用该API的其他文档以及连接
   - 英文文档没有此部分，建议添加
   

### 内容问题

- 缺少应用场景，请增加在哪些情况下可以使用此API来解决问题

### 主观评价

- 文档对该API的行为描述和功能介绍完整
- 缺少相应的使用场景，可以增加这一部分，让该API更加完善

**Comment by Ligoml** [comment]
1. 关于版本检查的建议，由于 
 - a.增加paddle.__version__的命令，响应的需要在例程中增加输出示例，每次版本迭代都修改全部输出是一个比较大的工作量 
 - b.paddle的api在开发时会尽量做到向前兼容，如有非兼容升级会在文档中说明，所以版本对例程的影响应该不大。
综合以上两个原因，paddle的版本检查是不需要加入的~

2. 使用本API的教程文档由于部分文档没有英文版本，因此可以暂时不处理该问题
3. 使用场景的问题不是API文档可以解决的，需要教程、案例等等文档作为补充~
