### ISSUE TITLE
paddle.real_文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4338]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/real_cn.html#real
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/real_en.html#real

### 红线问题

- 1. API行为描述中对该API的调用方式说明不完整
   - 调用方式1： 使用paddle.real(),将tensor作为参数传入，返回该tensor的实部
   - 调用方式2：直接使用x.real(),不加参数，直接返回tensor x的实部
   - 代码中对这两种方式都有举例，但是调用方式2没有说明
- 2. 中文文档和英文文档格式不一致：
   - 中文文档中 “返回” 作为段落标题，文本格式有误
   - 中文文档中缺乏和英文文档中的“Return type”的对应的段落（返回类型）

### 内容问题

- 针对该API的不同调用方式的缺少相应的行为和区别描述

### 主观评价

- 该API比较简单，文档内容基本满足使用。建议按照红线中的要求进一步完善

**Comment by Ligoml** [comment]
红线问题1：调用方式在示例里说明清楚就可以的，文字描述反而容易引起困惑

红线问题2：需要修改
