### ISSUE TITLE
paddle.any_文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4339]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/any_cn.html#any
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/any_en.html#any

### 红线问题

- 中英文文档不是100%一致：
   - 1. 关于API的描述：
      - 中文： “该OP是对指定维度上的Tensor元素进行逻辑或运算，并输出相应的计算结果”
      - 英文为："Computes the the logical or of tensor elements over the given dimension." 
      - 英文更改为： Computes the the logical or of tensor elements over the given dimension, and return the result， 这样跟中文更加一致
    - 2. 英文文档中有“Return type”和“Raises”段落， 指出使用该API的返回类型和异常情况，中文无对应段落，需要增加

### 内容问题

 - API中，关于参数axis的说明——“如果为None，则计算所有元素的逻辑或并返回包含单个元素的Tensor变量，否则必须在 [−rank(x),rank(x)] 范围内。如果 axis[i]<0 ，则维度将变为 rank+axis[i] ，默认值为None”， 其中： “必须在 [−rank(x),rank(x)] 范围内。如果 axis[i]<0 ，则维度将变为 rank+axis[i] ” 这句话无法理解所要表达的含义（英文同此），希望增加更多说明
 - 代码中使用了paddle.assign, paddle.cast 这两个API， 希望增加代码注释，减小初次使用该文档的学习成本
 - 代码注释中的：
            # x is a bool Tensor with following elements:
           #    [[True, False]
           #     [False, False]]
  该内容有误，应该为
           #     [[True, False]
           #     [True, True]]

### 主观评价

需要增加更多说明，并更正相关错误

**Comment by Ligoml** [comment]
红线问题1：需要修改
红线问题2：return type是前端解析问题，raises删除
内容部分1：不易理解，建议修改描述，代码中第一次出现的概念和API增加引用
内容部分2：输出错误，需要修改
