### ISSUE TITLE
paddle.index_select 文档评估

### ISSUE THREAD

**Issue by GeYuYao-hub** [PaddlePaddle/docs#4343]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/index_select_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/index_select_en.html

### 主观评价

文档写的是没有问题，但是由于没有用过这个api看了两次文字描述并没有懂，不过代码部分的注释例子举得很完善，看了一会就看懂了。全程大概用了两分钟。

**Comment by Ligoml** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/39876205/160376058-72d2040d-fc53-4c3e-a6f8-9a831caa8fd9.png">
说法要改
