### ISSUE TITLE
paddle.add 文档评估

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/docs#4348]
### 文档中英文链接

- 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/add_cn.html#add
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/add_en.html#add

### 红线问题

中英文不一致，英文文档中多出了参数with_quant_attr ，并且英文文档对于广播介绍更为详尽，更好一些

### 主观评价

中文文档已经较为清楚了。但是如果能在末尾附注广播内容可能会更好。

**Comment by Ligoml** [comment]
红线问题：参数with_quant_attr，需确认，源码中并无此参数
文末链接：英文教程文档内容出现问题，已给到研发修复
