### ISSUE TITLE
paddle.reshape 文档评估

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/docs#4350]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/reshape_cn.html#reshape
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/reshape_en.html#reshape

### 红线问题

文末附带的教程文档不一致

### 主观评价

较好

**Comment by Ligoml** [comment]
教程文档不一致的原因是部分教程仅有中文版，该问题目前可接受，感谢指出~
