### ISSUE TITLE
paddle.cumsum 文档评估

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/docs#4355]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/cumsum_cn.html#cumsum
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/cumsum_en.html#cumsum

### 内容问题

示例代码中的输出应从# VarType.FP64 更替为 # paddle.float64

### 主观评价

较好

**Comment by Ligoml** [comment]
除本篇文档外，还检索出以下文档存在同样错误，建议一起修改
文档1链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/basic_usage_cn.html#inputspec-tensor
内容问题：
<img width="883" alt="image" src="https://user-images.githubusercontent.com/39876205/160068742-3819cb90-fd77-4db0-8868-a6e6da589a18.png">
文档2链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/InputSpec_cn.html#inputspec
内容问题：
<img width="698" alt="image" src="https://user-images.githubusercontent.com/39876205/160068955-6139b07f-2fc5-46e6-8052-2d80a841edb3.png">
文档3链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/gradients_cn.html#gradients
内容问题：
<img width="773" alt="image" src="https://user-images.githubusercontent.com/39876205/160069413-c92e5233-eff7-42e3-b450-fb4600fe1a6d.png">
文档4链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/Program_cn.html#program
内容问题：
<img width="717" alt="image" src="https://user-images.githubusercontent.com/39876205/160069548-3b91c77f-4205-42ee-8f94-9f118a641a4f.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/39876205/160069581-ff8f092b-cf3d-4fcf-95bb-1a0d7f6467bc.png">

可一并修改，注意中英文需要同步更新

**Comment by Liyulingyue** [comment]
@Ligoml 已修改
中文 https://github.com/PaddlePaddle/docs/pull/4402
英文 https://github.com/PaddlePaddle/Paddle/pull/40984

**Comment by Ligoml** [comment]
修正10篇中英文api文档中参数type的描述，删除core.VarDesc.VarType
中文：https://github.com/PaddlePaddle/docs/pull/4378
英文：https://github.com/PaddlePaddle/Paddle/pull/40947
