### ISSUE TITLE
paddle.save

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4359]
### 文档中英文链接
中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/save_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/save_en.html
### 红线问题
- 英文的描述中 Note里没有描述“如果您需要这些没有保存的属性，请调用set_value接口将数值设置到带有这些属性的Tensor中。”的内容

### 结构问题
- 无
### 内容问题
- 无
### 格式问题
- 无
### 主观评价
- 中文的描述中参数protocol取值[2,4]，建议明确每种取值的意义及适用场景

**Comment by Ligoml** [comment]
- 中英文文档不一致，需要确认set_value接口的note提示是否需要同步到中文文档
- 需要在文档中增加参数protocol取值[2,4]分别的含义
