### ISSUE TITLE
paddle.Model

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4362]
### 文档中英文链接
中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/Model_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Model_en.html
### 红线问题
- fit(train_data=None, eval_data=None, batch_size=1, epochs=1, eval_freq=1, log_freq=10, save_dir=None, save_freq=1, verbose=2, drop_last=False, shuffle=True, num_workers=0, callbacks=None)
中关于callbacks参数的描述中，**建议增加ProgBarLogger 和 ModelCheckpoint这两个默认参数的介绍，以及代码或描述的链接
少了num_iters参数及对应的说明**
- evaluate(eval_data, batch_size=1, log_freq=10, verbose=2, num_workers=0, callbacks=None)
**少了num_iters参数及对应的说明**
- summary(input_size=None, batch_size=None, dtype=None)
**源码里是没有batch_size这个参数的**
### 结构问题
- 无
### 内容问题
- 无
### 格式问题
- 无
### 主观评价
-  eval_batch(inputs, labels=None)返回：如果没有定义评估函数，则返回包含了预测损失函数的值的列表；如果定义了评估函数，则返回一个元组（损失函数的列表，评估指标的列表）。**建议增加一个定义了评估函数的示例**
- predict(test_data, batch_size=1, num_workers=0, stack_outputs=False, callbacks=None) **关于stack_outputs参数的描述不够详细，参考英文版的进行描述**

**Comment by Ligoml** [comment]
参考issue中的评估意见，增加更多基础说明与示例
