### ISSUE TITLE
paddle.summary

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4364]
### 文档中英文链接
中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/summary_cn.html
英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/summary_en.html
### 红线问题
- 无
### 结构问题
- 无
### 内容问题
- 无
### 格式问题
- 无
### 主观评价
-  **是否考虑增加与paddle.Model里的summary的区别**

**Comment by Ligoml** [comment]
一样的
