### ISSUE TITLE
paddle.conj文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4375]
### 文档中英文链接

- 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/conj_cn.html
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/conj_en.html

### 红线问题

- 英文文档中 Returns章节文本格式有问题
- 英文文档中有“return type”章节，中文无

### 主观评价

结构完整，good!

**Comment by Ligoml** [comment]
1. Returns格式问题建议开发者提PR修复
2. 英文return type是前端解析出来的，无法在文档层面做修改，中文无即可
