### ISSUE TITLE
paddle.randn文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4388]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/randn_cn.html
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/randn_en.html

### 红线问题

1）英文文档右侧没有导航按钮
2）最后的“使用本API的教程文档”，中英文内容不一致。

### 主观评价

内容总体上来数，比较详细。

**Comment by Ligoml** [comment]
看的很仔细~英文导航栏属于前端设计问题，使用本API的教程文档不一致的主要原因是因为部分英文文档缺失
