### ISSUE TITLE
paddle.logsumexp文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4389]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/logsumexp_cn.html
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/logsumexp_en.html

### 内容问题

1）英文文档排版故障，标题和内容连在一起了。

### 主观评价

API接口功能易理解

**Comment by Ligoml** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/39876205/160346182-b517cab2-0572-499b-bea5-a3662f339f9c.png">
英文文档公式解析有问题
