### ISSUE TITLE
paddle.expand_as文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4392]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/expand_as_cn.html
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/expand_as_en.html

### 红线问题

- 一致
- 能跑
![image](https://user-images.githubusercontent.com/20416270/160225288-0ce03e3f-a34c-46f2-b9c8-0b089d5102ce.png)

![image](https://user-images.githubusercontent.com/20416270/160225305-b00cba0d-f526-49b7-bb6b-0c0f5ad09e23.png)

- 中文文档的 【返回】 栏目 与 英文文档的【Returns】  有点差异，中文文档没有说明返回值与y的关系，而英文文档较详细，说明了它们之间的关系。两个文档的实例代码不一致

### 结构问题

按API文档推荐的结构书写，无遗漏。

### 内容问题

通畅、准确、易理解。
API描述部分描述清楚。
示例代码以注释给出了运行结果
没有死链、错字、错误标点等低级错误。

### 格式问题

使用了深度学习领域通用的词汇和说法
API文档格式满足格式规范
英文文档没有使用numpy创建输入

### 主观评价

这两个文档写得不错，能够帮助我理解这个API的使用。

中文文档还有实例链接，这个是加分项，不过英文文档没有。

**Comment by Ligoml** [comment]
1. 示例中需要尽量避免numpy，需要修改示例代码
2. return需与英文保持一致
