### ISSUE TITLE
paddle.prod文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4393]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/prod_cn.html#prod

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/prod_en.html#prod

### 红线问题

无问题

### 结构问题

按API文档推荐的结构书写，无遗漏。

### 内容问题

使用了深度学习领域通用的词汇和说法
API文档格式满足格式规范
英文文档没有使用numpy创建输入

### 格式问题

中文文档   【返回 】这个标题有格式问题

### 主观评价

这两个文档写得不错，能够帮助我理解这个API的使用。

**Comment by Ligoml** [comment]
1. 示例中需要尽量避免numpy，需要修改示例代码
2. return需与英文保持一致
