### ISSUE TITLE
paddle.bmm文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4394]
### 文档中英文链接

英文文档：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/bmm_en.html#bmm

中文文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/bmm_cn.html#bmm

### 红线问题

无问题

![image](https://user-images.githubusercontent.com/20416270/160225887-460cc314-ce82-4b2d-81bd-6bb0c37a7af1.png)

### 结构问题

按API文档推荐的结构书写，无遗漏。

### 内容问题

使用了深度学习领域通用的词汇和说法
API文档格式满足格式规范
说明了在什么场景下使用该API
以注释给出了运行结果
没有死链、错字、错误标点等低级错误

### 格式问题

中文文档格式有点问题：
【参数】栏目标题

### 主观评价

这中文和英文两个文档写得不错，能够帮助我理解这个API的使用。

**Comment by Ligoml** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/39876205/160349402-8f648c1b-526f-4674-ac8b-ab3d2f199869.png">
标点符号也需要注意
