### ISSUE TITLE
paddle.floor_mod文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4396]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_mod_en.html#floor-mod

没有找到该API中文文档的链接。

### 红线问题

无问题

### 结构问题

无问题

### 内容问题

无问题

### 格式问题

示例代码仅使用Paddle API

### 主观评价

没有找到中文文档！！！！！！！！！

**Comment by Ligoml** [comment]
中文文档在这里：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/mod_cn.html
官网解析问题，已反馈~
