### ISSUE TITLE
paddle.set_printoptions文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4397]
### 文档中英文链接

英文文档：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/set_printoptions_en.html#set-printoptions

中文文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/set_printoptions_cn.html#set-printoptions

### 红线问题

无红线问题

![image](https://user-images.githubusercontent.com/20416270/160226398-badc0ceb-6ec4-4f0d-8e6d-008ef64fa628.png)

中文文档比英文文档少一个参数 linewidth 的介绍。

### 结构问题

无结构问题

### 内容问题

以注释给出了运行结果
没有死链、错字、错误标点等低级错误
全文语句通畅、准确、易理解

### 格式问题

满足格式规范

### 主观评价

中英文文档参数列表不一致。
能够有效的帮助自己了解并使用这个API

**Comment by Ligoml** [comment]
中文文档缺失参数，需要参照英文文档补充上
