### ISSUE TITLE
paddle.eye文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4398]
### 文档中英文链接

英文文档：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/eye_en.html#eye
中文文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/eye_cn.html#eye

### 红线问题

中英文的内容不一致，英文文档没有说明参数的数据类型为非负int32。
英文文档没有介绍 【抛出异常】

### 结构问题

是按API文档推荐的结构书写

### 内容问题

无问题。

### 格式问题

无格式问题。

### 主观评价

中英文文档内容不一致，其他没什么问题。

**Comment by Ligoml** [comment]
中英文的内容不一致，英文文档没有说明参数的数据类型为非负int32，需要研发确认参数问题
