### ISSUE TITLE
paddle.minimum 文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4403]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/minimum_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/minimum_cn.html

### 结构问题

API 返回部分格式与同行的内容区分度不明确，容易混淆。

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/minimum_cn.html#:~:text=%C2%B6-,Tensor%EF%BC%8C%E5%AD%98%E5%82%A8%E8%BF%90%E7%AE%97%E5%90%8E%E7%9A%84%E7%BB%93%E6%9E%9C,-%E3%80%82%E5%A6%82%E6%9E%9Cx%E5%92%8C

英文部分返回说明指代不明确

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/minimum_en.html#:~:text=Returns-,N%2DD%20Tensor.,-A%20location%20into 

### 内容问题

英文语法问题
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/minimum_en.html#:~:text=Compare%20two%20tensors%20and%20returns%20a%20new%20tensor%20containing%20the%20element%2Dwise%20minima.  应该为return

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/minimum_en.html#:~:text=A%20location%20into%20which%20the%20result%20is%20stored.  翻译错误需要重新翻译

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/minimum_en.html#:~:text=If%20x%2C%20y%20have%20different%20shapes%20and%20are%20%E2%80%9Cbroadcastable%E2%80%9D%2C%20the%20resulting%20tensor%20shape%20is%20the%20shape%20of%20x%20and%20y%20after%20broadcasting.%20If%20x%2C%20y%20have%20the%20same%20shape%2C%20its%20shape%20is%20the%20same%20as%20x%20and%20y.    翻译流畅度很差

### 主观评价

英文翻译有点生硬，中文问题不大

**Comment by Ligoml** [comment]
建议修改英文文档，包括翻译问题和N-D tensor的描述

注：文档评估需基于develop
