### ISSUE TITLE
paddle.is_tensor 文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4404]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/is_tensor_en.html#is-tensor
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/is_tensor_cn.html

### 结构问题

文档中，中英文处的介绍 ‘返回’ 格式不一样

### 内容问题

中文部分
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/is_tensor_cn.html#:~:text=%E8%BF%94%E5%9B%9E%EF%BC%9A%E5%B8%83%E5%B0%94%E5%80%BC%EF%BC%8C%E5%A6%82%E6%9E%9Cx%E6%98%AFpaddle.Tensor%E7%9A%84%E8%AF%9D%E8%BF%94%E5%9B%9ETrue%EF%BC%8C%E5%90%A6%E5%88%99%E8%BF%94%E5%9B%9EFalse%E3%80%82  太过口语化

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/is_tensor_en.html#:~:text=True%20if%20%E2%80%98x%E2%80%99%20is%20a%20paddle.Tensor%2C%20otherwise%20False.   英文翻译错误

![image](https://user-images.githubusercontent.com/12640462/160364234-ef7ab892-1d71-4bbb-96a2-2b6d6a850720.png)
文档底部的翻译时态都不对吧？？？不应该是Is吗

### 主观评价

英文部分翻译流畅性整体不好，示例不错

**Comment by Ligoml** [comment]
- 结构问题已调整，中文文档口语化问题可以修改
- 英文文档翻译有什么错误？
- 打星提示的英文部分是对的，指的是你刚刚阅读完（过去时）的这篇文档是否有帮助
