### ISSUE TITLE
paddle.normal 文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4405]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/normal_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/normal_cn.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/normal_en.html#:~:text=This%20OP%20returns%20a%20Tensor%20filled%20with%20random%20values%20sampled%20from%20a%20normal%20distribution%20with%20mean%20and%20std%20(standard%20deviation)%20.    中英文此处翻译不一致

### 内容问题

![image](https://user-images.githubusercontent.com/12640462/160366539-246e262e-3314-49bf-b52f-e498b34797eb.png)

代码处的注释random有一个即可，因为两行是一个整体

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/normal_cn.html#:~:text=str%2C%20%E5%8F%AF%E9%80%89)%20%2D-,%E6%93%8D%E4%BD%9C%E7%9A%84%E5%90%8D%E7%A7%B0,-(%E5%8F%AF%E9%80%89%EF%BC%8C%E9%BB%98%E8%AE%A4    中文翻译不对

### 主观评价

整体还可以，英文阅读通顺度较低

**Comment by Ligoml** [comment]
中英文翻译不对的地方在哪里？可以截个图画框示意一下~

代码处的注释需要修改
