### ISSUE TITLE
paddle.matmul 文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4407]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/matmul_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/matmul_cn.html

### 红线问题

代码示例中打印的结果以此如下：
`(1,)
(10,)
(10, 5)
(10, 5, 5)
(10, 3, 5, 5)`
与文档中稍微有点出入，这部分是否要保持一致？？？

### 内容问题

中文部分

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/matmul_cn.html#:~:text=%E5%AE%9E%E9%99%85%E8%A1%8C%E4%B8%BA%E5%8F%96%E5%86%B3%E4%BA%8E-,%E8%BE%93%E5%85%A5%20x%20%E3%80%81%E8%BE%93%E5%85%A5%20y,-%E3%80%81%20transpose_x%20%EF%BC%8C%20transpose_y%20%E3%80%82%E5%85%B7%E4%BD%93   这个地方建议直接写为 x、y

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/matmul_cn.html#:~:text=%E5%AE%9E%E9%99%85%E8%A1%8C%E4%B8%BA%E5%8F%96%E5%86%B3%E4%BA%8E%E8%BE%93%E5%85%A5%20x%20%E3%80%81%E8%BE%93%E5%85%A5%20y%20%E3%80%81%20transpose_x%20%EF%BC%8C%20transpose_y%20%E3%80%82 这句话理解有问题，感觉缺少了主语部分

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/matmul_cn.html#:~:text=transpose_y%20%E3%80%82%E5%85%B7%E4%BD%93%E5%A6%82%E4%B8%8B%EF%BC%9A-,%E5%A6%82%E6%9E%9C%20transpose%20%E4%B8%BA%E7%9C%9F,-%EF%BC%8C%E5%88%99%E5%AF%B9%E5%BA%94%20Tensor  此处为真建议直接用True

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/matmul_cn.html#:~:text=%E7%9A%84%E4%B9%98%E6%B3%95%E8%BF%90%E7%AE%97-,%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%86%E5%85%B6%E5%88%A0%E9%99%A4%E3%80%82,-%E5%A6%82%E6%9E%9C%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%8F%82%E6%95%B0 这句话意思没说明为什么，另外前后句子阅读不太顺畅。

英文部分

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/matmul_en.html#:~:text=matmul%20follows%20the%20complete%20broadcast%20rules  中式翻译

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/matmul_en.html#:~:text=Currently%2C%20the%20input-,tensors%E2%80%99,-number%20of%20dimensions   多了个引号吧

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/matmul_en.html#:~:text=The%20output%20Tensor.-,Return%20type,-Tensor
中英文这两处格式不一样，中文直接在返回中说明

### 主观评价

英文还是英文，翻译待加强

**Comment by Ligoml** [comment]
- 红线问题需要修改，输出应与实际情况一致
- 内容问题因格式调整目前看不清楚，建议直接在pr里修改，具体细节可以review时沟通
