### ISSUE TITLE
paddle.expand文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4408]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/expand_cn.html

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/expand_en.html

### 内容问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/expand_cn.html#:~:text=tuple%7Clist%7CTensor)%20%2D-,%E7%BB%99%E5%AE%9A%E8%BE%93%E5%85%A5%20x%20%E6%89%A9%E5%B1%95%E5%90%8E%E7%9A%84%E5%BD%A2%E7%8A%B6%2C,-%E8%8B%A5%20shape%20%E4%B8%BA 中文后的标点符号有问题

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/expand_en.html#:~:text=same%20as%20x.-,Return%20type,-N%2DD%20Tensor   英文处的返回类型和中文格式不一样

### 主观评价

英文继续加强

**Comment by Ligoml** [comment]
- 格式问题已做修改
- N-D tensor改为tensor
