### ISSUE TITLE
paddle.max文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4411]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/max_cn.html
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/max_en.html

### 红线问题

1）中英文API文档的标题样式不统一。
2）中文API最后的“使用本API的教程文档”在英文文档中没有对应的内容。

### 内容问题

1）原文的“支持数据类型为float32，float64，int32，int64“是否需要更改为“支持数据类型为float32、float64、int32、int64”

### 主观评价

max API接口功能较简单，通过介绍和示例很容易看懂。

**Comment by Ligoml** [comment]
- 标点符号需要修改
