### ISSUE TITLE
paddle.equal_all文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4412]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/equal_all_cn.html#equal-all
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/equal_all_en.html#equal-all

### 红线问题

1）英文原文“This OP returns the truth value of x==y. True if two inputs have the same elements, False otherwise.”对应的中文“该OP返回：返回的结果只有一个元素值，如果所有相同位置的元素相同返回True，否则返回False。”不好理解。建议修改为“该OP返回x==y的布尔值，果所有相同位置的元素相同返回True，否则返回False。”
2）中英文标题格式没有对应。

### 主观评价

API接口较简单，通过文档说明和示例很容易理解。

**Comment by Ligoml** [comment]
翻译问题直接在PR中沟通
