### ISSUE TITLE
paddle.full_like文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4414]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/full_like_cn.html#full-like
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/full_like_en.html#full-like

### 红线问题

1）中英文文档标题格式不统一。
2）英文文档‘tensor which is created according to x, fill_value and dtype.’与中文文档‘返回一个存储结果的Tensor，数据类型和dtype相同。’不对应

### 主观评价

该接口实现功能较简单，通过示例和文档可理解该接口用法。

**Comment by Ligoml** [comment]
翻译问题参考源码做统一
