### ISSUE TITLE
paddle.subtract文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4415]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/subtract_cn.html#subtract
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/subtract_en.html#subtract

### 红线问题

1）中英文标题格式不统一

### 结构问题

1）这一个API文档的‘数据类型为 float32 、 float64 、 int32 或 int64’中都是“、”，其他的API文档大多都是“，”分割的，请官方确认到底使用哪一个符号是正确的。符号统一。通常情况下，英语中没有“、”号，所有都使用“，”相隔，中文通常使用“、”。

### 主观评价

接口内容较简单，通过示例和API很容易理解。

**Comment by Ligoml** [comment]
中文文档应该是 、 已做修改
