### ISSUE TITLE
paddle.histogram文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4416]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/histogram_cn.html#histogram
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/histogram_en.html#histogram

### 红线问题

1）中英文文档的标题格式不一样。
2）中文文档的“抛出异常“部分在英文文档没有对应的内容。
3）中文的参数介绍都没有写默认值，与英文文档不对应。

### 内容问题

1）原文“数据类型为int32, int64, float32或float64。”是否可修改为“数据类型为int32、 int64 、float32或float64。”

### 主观评价

接口功能较简单，通过示例很容易理解

**Comment by Ligoml** [comment]
已完成修改
