### ISSUE TITLE
paddle.log1p  文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4419]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/log1p_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/log1p_cn.html

### 内容问题

中文部分

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/log1p_cn.html#:~:text=OP%E8%AE%A1%E7%AE%97Log1p-,%EF%BC%88%E5%8A%A0%E4%B8%80%E7%9A%84%E8%87%AA%E7%84%B6%E5%AF%B9%E6%95%B0%EF%BC%89,-%E7%BB%93%E6%9E%9C%E3%80%82    建议翻译为自然对数+1

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/log1p_cn.html#:~:text=name%20(str%EF%BC%8C%E5%8F%AF%E9%80%89)%20%E2%80%93%20%E8%AF%A5%E5%8F%82%E6%95%B0%E4%BE%9B%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%89%93%E5%8D%B0%E8%B0%83%E8%AF%95%E4%BF%A1%E6%81%AF%E6%97%B6%E4%BD%BF%E7%94%A8   name这部分好多都翻译不统一，建议统一一下

示例输出的结果实际应该为

[[0.        ],
 [0.69314718]]    文档中给出的做了四舍五入

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/log1p_cn.html#:~:text=Log1p%E7%AE%97%E5%AD%90%E8%87%AA%E7%84%B6%E5%AF%B9%E6%95%B0%E8%BE%93%E5%87%BA%EF%BC%8C%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%EF%BC%8C%E5%BD%A2%E7%8A%B6%E4%B8%BA%E8%BE%93%E5%85%A5%E4%B8%80%E8%87%B4   语句不通顺

英文部分

公式建议一行，公式较短

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/log1p_en.html#:~:text=Calculates%20the%20natural%20log%20of%20the%20given%20input%20tensor%2C%20element%2Dwise.
开头语法错误

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/log1p_en.html#:~:text=Must%20be%20one%20of%20the%20following%20types%3A%20float32%2C%20float64.   没有主语

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/log1p_en.html#:~:text=the%20natural%20log%20of%20the%20input%20Tensor%20computed%20element%2Dwise.  compute语法错误

### 主观评价

中文翻译不通顺，英文语法错误较多

**Comment by Ligoml** [comment]
- name说法已有统一，见working group表单共性问题
- 公式问题需要修改，建议统一做一次修改
- 代码示例应该保持一致
- 翻译问题直接在pr里沟通
