### ISSUE TITLE
paddle.isfinite  文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4420]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/isfinite_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/isfinite_cn.html

### 内容问题

中文部分

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/isfinite_cn.html#:~:text=%E5%80%BC%E6%98%AF%E5%90%A6%E4%B8%BA%20Finite-,%EF%BC%88%E6%97%A2%E9%9D%9E%20%2B/%2DINF%20%E4%B9%9F%E9%9D%9E%20%2B/%2DNaN%20%EF%BC%89,-%E3%80%82   格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/isfinite_cn.html#:~:text=%E5%85%83%E7%B4%A0%E6%98%AF%E4%B8%80%E4%B8%AA-,bool%E5%80%BC,-%EF%BC%8C%E8%A1%A8%E7%A4%BA%E8%BE%93%E5%85%A5%20x   bool翻译统一一下，有的不翻译有的翻译，目前有点混乱

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/isfinite_cn.html#:~:text=%E5%85%83%E7%B4%A0%E6%98%AF%E5%90%A6%E4%B8%BA%20Finite-,%EF%BC%88%E6%97%A2%E9%9D%9E%20%2B/%2DINF%20%E4%B9%9F%E9%9D%9E%20%2B/%2DNaN%20%EF%BC%89,-%E3%80%82   格式问题

英文部分

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/isfinite_en.html#:~:text=number%20or%20not.-,Examples,-import%20paddle%0A%0Ax  应该为Example，此处只有一个示例，不是多个

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/isfinite_en.html#:~:text=it%E2%80%99s%20data%20type%20should%20be   语法问题

### 主观评价

英文翻译有待加强，国际友人要说了

**Comment by Ligoml** [comment]
- 数据类型：int、float、bool等中文文档不做翻译
- examples是一个关键字，不需要修改
- 语法问题在pr中沟通
