### ISSUE TITLE
paddle.imag 文档评估

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4422]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/imag_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/imag_cn.html

### 内容问题

中文部分

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/imag_cn.html#:~:text=%E8%BF%94%E5%9B%9E%E4%B8%80%E4%B8%AA%E5%8C%85%E5%90%AB%E8%BE%93%E5%85%A5%E5%A4%8D%E6%95%B0Tensor%E7%9A%84%E8%99%9A%E9%83%A8%E6%95%B0%E5%80%BC%E7%9A%84%E6%96%B0Tensor  建议翻译为： 返回新Tensor包含输入复数Tensor的虚部

英文部分

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/imag_en.html#:~:text=Return%20type,Tensor
返回类型这块，好多文档建议格式统一 一下

### 主观评价

基本问题不大，个别不通顺

**Comment by Ligoml** [comment]
已做修改
