### ISSUE TITLE
paddle.ones_like文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4429]
### 文档中英文链接

英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/ones_like_en.html
中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/ones_like_cn.html

### 红线问题

1）中英文文档标题不对应
2）中英文文档关于“抛出异常”部分内容不对应。

### 主观评价

接口功能相对简单，通过实例很容易理解。

**Comment by Ligoml** [comment]
- 英文文档中的raises需要删除
