### ISSUE TITLE
paddle.gather文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4435]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/gather_en.html#gather

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/gather_cn.html#gather

### 红线问题

API描述中中文文档 少了"given"

### 内容问题

中文文档【参数】栏中中英文的逗号都有。

### 格式问题

中文文档使用了numpy

### 主观评价

中文文档质量不太行

**Comment by Ligoml** [comment]
建议集体修改，在pr中沟通
