### ISSUE TITLE
paddle.all文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4437]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/all_en.html#all

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/all_cn.html#all

### 红线问题

无问题

![image](https://user-images.githubusercontent.com/20416270/160820121-57a269f5-454c-4fea-bc7c-5efcc007a23a.png)

### 结构问题

无问题

### 内容问题

无问题，keepdim 中文文档说了bool，而英文文档说bool 可选

### 格式问题

使用了numpy

### 主观评价

整体非常不错

**Comment by Ligoml** [comment]
中文文档需要修改，保持一致
