### ISSUE TITLE
paddle.nonzero文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4438]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nonzero_en.html#nonzero

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nonzero_cn.html#nonzero

### 红线问题

![image](https://user-images.githubusercontent.com/20416270/160821524-a740d3bc-4c8e-4c1d-b6c0-e24fb97ad995.png)

### 结构问题

无

### 内容问题

中英文文档的参数as_tuple描述不一致

### 格式问题

合格

### 主观评价

两篇文档整体不错

**Comment by Ligoml** [comment]
参数描述需要保持一致
