### ISSUE TITLE
paddle.empty_like文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4439]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/empty_like_cn.html#empty-like

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/empty_like_en.html#empty-like

### 内容问题

中文文档使用了英文逗号

### 格式问题

均使用了numpy

中文文档的【返回】格式有误

### 主观评价

整体不错，不过格式有些问题，标点符号要注意

**Comment by Ligoml** [comment]
标点符号与numpy问题需要修改
