### ISSUE TITLE
paddle.strided_slice文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4441]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/strided_slice_en.html#strided-slice

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/strided_slice_cn.html#strided-slice

### 红线问题

![image](https://user-images.githubusercontent.com/20416270/160822973-e1cdc386-1aa7-4d0c-9d87-07cf3d6b0c61.png)

### 内容问题

参数x ，中文文档说可以使用bool，而英文文档没有说明，源代码是没有bool的。

### 格式问题

中文文档【参数：】【返回】有格式问题

### 主观评价

整体不错

**Comment by Ligoml** [comment]
- 参数问题通过源码校验，保持一致（红线问题）
- 文档中的链接以参考链接的方式放在文本描述的下面，参数之前
