### ISSUE TITLE
paddle.scatter_nd_add文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4442]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/scatter_nd_add_cn.html#scatter-nd-add

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/scatter_nd_add_en.html#scatter-nd-add

### 红线问题

![image](https://user-images.githubusercontent.com/20416270/160823701-3a2270b1-841b-4229-be85-dd72a6fcf7cc.png)

### 内容问题

描述中 we get 翻译成输出较妥当，而不是  得到

### 格式问题

使用了numpy

### 主观评价

翻译较为生硬

**Comment by Ligoml** [comment]
翻译和numpy需要修改
