### ISSUE TITLE
paddle.unbind文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4445]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/unbind_cn.html#unbind

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/unbind_en.html#unbind

### 格式问题

使用了numpy

### 主观评价

文档不错

**Comment by Ligoml** [comment]
numpy需要换掉
