### ISSUE TITLE
paddle.gather_nd文档评估

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4446]
### 文档中英文链接

中文[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/gather_nd_cn.html#gather-nd](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/gather_nd_cn.html#gather-nd)

英文 [https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/gather_nd_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/gather_nd_en.html0)

### 红线问题

无问题

### 结构问题

无问题

### 格式问题

无问题

### 主观评价

质量高。

建议：
给出的3个例子应该对应三个类型，建议标题写清楚，而不是直接给代码。

**Comment by Ligoml** [comment]
index中已经把tensor样式给出，比文字描述更清晰，这里可以不做修改~
