### ISSUE TITLE
paddle.is_empty文档测评

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4453]
### 文档中英文链接

中文 [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/is_empty_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/is_empty_cn.html)

英文 [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/is_empty_en.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/is_empty_en.html)

### 红线问题

测试变量是否为空应该为测试张量是否为空

### 结构问题

无问题

### 内容问题

无问题

### 格式问题

无问题

### 主观评价

清晰易懂

**Comment by Ligoml** [comment]
红线问题需要修改，另外加上标点符号
