### ISSUE TITLE
paddle.get_default_dtype文档测评

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4454]
### 文档中英文链接

中文  [https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_default_dtype_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_default_dtype_cn.html)

英文 [https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_default_dtype_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_default_dtype_en.html)

### 红线问题

无问题

### 结构问题

无问题

### 内容问题

英文文档返回值没写。

### 格式问题

无问题

### 主观评价

清晰易懂

**Comment by Ligoml** [comment]
中英文返回值不一致，参考源码做修改
