### ISSUE TITLE
paddle.load文档测评

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4455]
### 文档中英文链接

中文  [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/load_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/load_cn.html)

英文 [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/load_en.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/load_en.html)

### 红线问题

无问题

### 结构问题

无问题

### 内容问题

中文文档给出的5个示例，建议给出中文标题

### 格式问题

无问题

### 主观评价

清晰易懂

**Comment by Ligoml** [comment]
- 代码示例修改为代码示例 1-5，并增加说明
- 标点符号需要修改
