### ISSUE TITLE
paddle.jit.load文档测评

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4472]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/jit/load_cn.html

英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/jit/load_en.html

### 红线问题

中文缺少关于Paddle 1.x模型载入的说法。

### 结构问题

中英文参数config格式不对

### 内容问题

无

### 格式问题

无

### 主观评价

好

**Comment by Ligoml** [comment]
- 文档应基于paddle2.x，因此可以不涉及1.x相关内容
- config确实格式有问题，需要调整
