### ISSUE TITLE
paddle.device.is_compiled_with_cuda测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4474]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_cuda_cn.html
英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/is_compiled_with_cuda_en.html

### 红线问题

无

### 结构问题

英文文档导航栏不存在

### 内容问题

无

### 格式问题

无

### 主观评价

英文文档导航栏不存在

**Comment by Ligoml** [comment]
英文文档格式会参照中文文档做统一调整，这里不做修复
