### ISSUE TITLE
paddle.floor文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4475]
### 文档中英文链接

中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/floor_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/floor_en.html

### 红线问题

1. 参数不一致， 英文文档有with_quant_attr (BOOLEAN)参数，中文文档无，需要删除
2. 中英文代码示例不一致。推荐使用中文的代码示例

### 内容问题

1. 中文文档，删除“该OP”
2. 英文文档公式格式有误

### 主观评价

需要修复示例代码不一致问题

**Comment by Ligoml** [comment]
问题存在，欢迎修复
