### ISSUE TITLE
paddle.sinh文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4476]
### 文档中英文链接

中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sinh_cn.html
英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sinh_en.html

### 红线问题

1. 英文文档公式与中文不一致，建议按照中文文档的写法，给出sinh(x) 的计算方法
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中英文文档示例代码不一致

### 内容问题

1. 关于返回值： 
  - 中文文档为：与 x 维度相同、数据类型相同
  - 英文为：a Tensor with shape same as input。 建议英文文档改为：a Tensor with same shape and dtype as input, 更加通顺完整

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
