### ISSUE TITLE
paddle.asin文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4478]
### 文档中英文链接

中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/asin_cn.html
英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/asin_en.html

### 红线问题

1. 英文文档参数与中文不一致： 多了with_quant_attr (BOOLEAN)， 源码中无
2. 英文文档公式格式有误，需要居中
3. 中英文文档代码示例不一致，建议按照英文文档

### 内容问题

API返回中英文表述有差异
 - 中文：输出Tensor，与 x 维度相同、数据类型相同
 - 英文： Output of asin operator。 英文可以修改为： Tensor, same shape and dtype as input

### 主观评价

红线问题需要完善

**Comment by Ligoml** [comment]
问题存在，欢迎修复
