### ISSUE TITLE
paddle.round文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4480]
### 文档中英文链接

- 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/round_cn.html
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/round_en.html

### 红线问题

1. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
2. 中英文文档示例代码不一致

### 内容问题

关于API的返回： 
 - 中文为： 返回类型为Tensor， 数据类型同输入一致
 - 英文： Output of Round operator, a Tensor with shape same as input， 建议修改为： Tensor, same shape and dtype as input

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
代码可以使用copy-from的方式，保证一致
