### ISSUE TITLE
paddle.acos文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4481]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/acos_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/acos_en.html

### 红线问题

1. 英文文档的公式格式有误，需要居中
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中英文文档示例代码中的测试案例数值不一致

### 内容问题

关于API的返回：
 - 中文： 输出Tensor，与 x 维度相同、数据类型相同。
 - 英文： Output of acos operator， 建议更改为： Tensor, same shape and dtype as input

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
