### ISSUE TITLE
paddle.exp文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4487]
### 文档中英文链接

- 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/exp_cn.html
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/exp_en.html

### 红线问题

1. 英文文档的公式格式有误，需要居中
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中英文文档示例代码中的测试案例数值不一致

### 内容问题

关于API的返回：

中文： 输出Tensor，与 x 维度相同、数据类型相同。
英文： Output of Cos operator, a Tensor with shape same as input.，
建议更改为： Tensor, same shape and dtype as input x

### 主观评价

需要修复红线问题

**Comment by Ligoml** [comment]
问题存在，欢迎修复
