### ISSUE TITLE
paddle.cosh文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4488]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/cosh_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/cosh_en.html

### 红线问题

1. 英文文档的公式和中文不一致，建议英文格式居中，并增加cosh的计算方法
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除

### 内容问题

关于API的返回：

中文： 输出Tensor，与 x 维度相同、数据类型相同。
英文： Output of Cos operator, a Tensor with shape same as input.，
建议更改为： Tensor, same shape and dtype as input x

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
