### ISSUE TITLE
paddle.rsqrt文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4489]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/rsqrt_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/rsqrt_en.html

### 红线问题

1. 英文文档的公式格式有误
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除

### 内容问题

关于API的返回：

中文： Tensor，对输入x进行rsqrt激活函数计算结果，数据shape、类型和输入x的shape、类型一致
英文： Output of Rsqrt operator, a Tensor with shape same as input.
建议更改为： 
中文：  Tensor，数据shape、dtype 和输入x一致
英文：Tensor, same shape and dtype as input x

### 主观评价

需要修复红线问题

**Comment by Ligoml** [comment]
问题存在，欢迎修复
