### ISSUE TITLE
paddle.abs文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4490]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/abs_cn.html
- 英文： https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/abs_en.html

### 红线问题

1. 英文文档的公式格式与中文不一致，建议单独一行，居中
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中文文档中有“使用本API的教程文档”章节以及链接， 英文无对应的章节
4. 英文文档的 Return Type内容错误： out (Tensor)， 改为：Tensor

### 内容问题

关于API的返回：

中文： 输出Tensor，与 x 维度相同、数据类型相同。
英文： (Tensor), The output tensor of abs op，
建议更改为： 
中文： Tensor, 与 x 维度相同、数据类型相同
英文：  Tensor, same shape and dtype as input x

### 主观评价

需要修改红线问题

**Comment by Ligoml** [comment]
问题存在，欢迎修复
使用本API文档是前端抽取，不需要管
