### ISSUE TITLE
paddle.utils.require_version测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4493]
### 文档中英文链接

中文文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/require_version_cn.html
英文文档：
无

### 红线问题

英文文档缺失

### 结构问题

无

### 内容问题

参数处：
min_version (str) - 指定所需要的最低版本（如‘1.4.0’）缺少句号

### 格式问题

无

### 主观评价

英文文档缺失

**Comment by zyl1223582136** [comment]
### PR types

Others

### PR changes

Docs

### Describe

添加英文文档

---

paddle.fluid.require_version(*min_version*, *max_version=None*)[[source\]](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/framework.py#L388)



This interface is used to check whether the installed propeller version is between [`min_version`, `max_version`] (including `min_version` and `max_version`), and if the installed version is lower than  `min_version`  or higher than`max_version`, an exception will be thrown. The interface has no return value.

#### Parameters

> - **min_version** (str) -  Specify the minimum required version (e.g. `1.4.0`)
> - **max_version** (str, optional) – Specify the highest acceptable version (e.g. `1.7.0`), and the default value of None means that any version greater than or equal to `min_version` is acceptable.



#### Returns

None



#### throw exception

> - `TypeError` – The type of`min_version` is not str
> - `TypeError` –  The type of`max_version`is not str or type(None).
> - `ValueError` – The value of`min_version` is not in the normal version number format.
> - `ValueError` – The value of`max_version` is not in the normal version number format or None.
> - `Exception` – The installed version is earlier than`min_version`or higher than`max_version`.



#### Examples

```
import paddle.fluid as fluid

# any version >= 0.1.0 is acceptable.
fluid.require_version('0.1.0')

# if 0.1.0 <= version <= 10.0.0, it is acceptable.
fluid.require_version(min_version='0.1.0', max_version='10.0.0')
```
