### ISSUE TITLE
paddle.sqrt文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4494]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sqrt_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sqrt_en.html

### 红线问题

1. 英文文档的公式格式有误，需要居中
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中英文文档示例代码中的测试案例数值不一致

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
代码使用copy-from保证一致
