### ISSUE TITLE
paddle.square文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4496]
### 文档中英文链接

 - 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/square_cn.html
 - 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/square_en.html

### 红线问题

1. 中文文档删除“该OP”， 英文文档删除“The OP”, 并保持语句通顺
2. 英文文档公式建议居中，和中文保持一致
3. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
4. 中英文文档示例代码不一致

### 内容问题

关于API的返回：

中文： 取平方后的Tensor，维度和数据类型同输入一致。
英文： Output of Square operator, a Tensor with shape same as input.
建议更改为：
中文：  Tensor, 维度和数据类型同输入一致。
英文： Tensor, same shape and dtype as input x

### 主观评价

红线问题需要修复

**Comment by Ligoml** [comment]
问题存在，欢迎修复
