### ISSUE TITLE
paddle.reciprocal文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4498]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/reciprocal_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/reciprocal_en.html

### 红线问题

1. 英文文档公式格式、内容有错误
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3.  中英文文档示例代码不一致

### 内容问题

关于API的返回：

中文： 对输入取倒数得到的Tensor，输出Tensor数据类型和维度与输入相同。
英文： Output of Reciprocal operator, a Tensor with shape same as input.
建议更改为： 
中文： Tensor, shape和dtype与输入x一致
英文： Tensor, same shape and dtype as input x

### 主观评价

需要修改红线问题

**Comment by Ligoml** [comment]
问题存在，建议修复
