### ISSUE TITLE
paddle.static.nn.sparse_embedding测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4499]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sparse_embedding_cn.html
英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sparse_embedding_en.html

### 红线问题

中文文档：
param_attr参数：
1. numpy未替换为Tensor；
2. “具体用法请参见 cn_api_paddle_ParamAttr”这句话中的cn_api_paddle_ParamAttr未带链接。
英文文档：
param_attr参数：
1.numpy未替换为Tensor
2.无“具体用法请参见 cn_api_paddle_ParamAttr”这句话的英文对照

### 结构问题

英文文档导航栏不存在，英文文档包含Api_attr属性

### 内容问题

英文文档：
开头表述中带有The OP ，需修改

### 格式问题

中英文文档中的numpy表述未替换为Tensor

### 主观评价

英文文档导航栏缺失，英文文档包含Api_attr属性

**Comment by Ligoml** [comment]
- Api_attr属性删除
- numpy换掉
- the OP 删除
- 超链接需要增加

**Comment by zyl1223582136** [comment]
### PR types
Others

### PR changes
Docs

### Describe
#### 中文文档
* 修改param_attr参数如下所示：
(ParamAttr，可选) - 指定权重参数属性的对象。默认值为 None，表示使用默认的权重参数属性。具体用法请参见 [cn_api_paddle_ParamAttr](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/ParamAttr_cn.html)。此外，可以通过 param_attr 参数加载用户自定义或预训练的词向量。只需将本地词向量转为 numpy 数据格式，且保证本地词向量的 shape 和 embedding 的 size 参数一致，然后使用 [to_tensor](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/to_tensor_cn.html#cn-api-paddle-to-tensor) 进行初始化，即可实现加载自定义或预训练的词向量。

#### 英文文档
* 去掉Api_attr属性
* 修改para_attr为如下：
param_attr (ParamAttr, optional) – To specify the weight parameter property. Default: None, which means the default weight parameter property is used.For specific usage, see [cn_api_paddle_ParamAttr](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/ParamAttr_cn.html). In addition, user-defined or pre-trained word vectors can be loaded with the param_attr parameter. The local word vector needs to be transformed into numpy format, and the shape of local word vector should be consistent with size .Then initialize with  [to_tensor](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/to_tensor_cn.html#cn-api-paddle-to-tensor)
* 将开头中的“The OP”去掉
