### ISSUE TITLE
paddle.slice测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4502]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/slice_cn.html
英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/slice_en.html

### 红线问题

无

### 结构问题

英文文档导航栏缺失

### 内容问题

中文文档：
1.文档开头多次出现”该OP“
2. numpy的链接地址未隐藏，显示问题
3. ”以下示例将解释切片如何工作：“ 下面的示例代码，写法不推荐。

英文文档：
1.文档开头出现“This operator”
2. numpy的链接地址未隐藏，显示问题
3.  ”Following examples will explain how slice works:“ 下面的示例代码，写法不推荐。

中英文对照：
”返回“部分，中文文档为多维 Tensor，英文文档是A Tensor，未写明多维。

### 格式问题

无

### 主观评价

英文文档导航栏缺失，内容排版有问题。

**Comment by zyl1223582136** [comment]
### PR types
Others

### PR changes
Docs

### Describe
#### 中文文档
* 将开头修改为：
slice
沿多个轴生成 input 的切片。与 [numpy](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) 类似： slice使用 axes 、 starts 和 ends 属性来指定轴列表中每个轴的起点和终点位置，并使用此信息来对 input 切片。如果向 starts 或 ends 传递负值如 −i，则表示该轴的反向第 i−1 个位置（这里以 0 为初始位置）。如果传递给 starts 或 end 的值大于 n（维度中的元素数目），则表示 n。当切片一个未知数量的维度时，建议传入 INT_MAX。 axes 、 starts 和 ends 三个参数的元素数目必须相等。以下示例将解释切片如何工作：
```python
# example 1
data=[[1,2,3,4],[5,6,7,8],]
axes=[0,1]
starts=[1,0]
ends=[2,3]
result=paddle.slice(input=data, axes=axes, starts=starts, ends=ends)
print(result) #[[5,6,7],]

# example 2
data=[[1,2,3,4],[5,6,7,8],]
starts=[0,1]
ends=[-1,1000]    # 此处-1 表示第 0 维的反向第 0 个位置，索引值是 1。
result=paddle.slice(input=data, starts=starts, ends=ends)
print(result) #[[2,3,4],] ,data[0:1, 1:4]
```

#### 英文文档
* 将文档开头修改为：
slice
produces a slice of input along multiple axes. Similar to [numpy](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html):  Slice uses axes, starts and ends attributes to specify the start and end dimension for each axis in the list of axes and Slice uses this information to slice the input data tensor. If a negative value is passed to starts or ends such as −i, it represents the reverse position of the axis i−1 (here 0 is the initial position). If the value passed to starts or ends is greater than n (the number of elements in this dimension), it represents n. For slicing to the end of a dimension with unknown size, it is recommended to pass in INT_MAX. The size of axes must be equal to starts and ends. Following examples will explain how slice works:
```python
# example 1
data=[[1,2,3,4],[5,6,7,8],]
axes=[0,1]
starts=[1,0]
ends=[2,3]
result=paddle.slice(input=data, axes=axes, starts=starts, ends=ends)
print(result) #[[5,6,7],]

# example 2
data=[[1,2,3,4],[5,6,7,8],]
starts=[0,1]
ends=[-1,1000]    # -1 denotes the reverse 0th position of dimension 0.。
result=paddle.slice(input=data, starts=starts, ends=ends)
print(result) #[[2,3,4],] ,data[0:1, 1:4]
```
* 在Returns部分修改原有文字为：
Multidimensional `tensors`. The data type is same as `input`.
