### ISSUE TITLE
paddle.bitwise_not文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4503]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/bitwise_not_cn.html

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/bitwise_not_en.html#bitwise-not

### 红线问题

中英文文档不一致

英文文档没有注解

而且参数out 不一致

### 结构问题

无问题

### 内容问题

无问题

### 主观评价

中英文文档不一致

**Comment by Ligoml** [comment]
参数out不一致需要修改
英文文档需要加note
