### ISSUE TITLE
paddle.bitwise_or文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4504]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/bitwise_or_cn.html#bitwise-or

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/bitwise_or_en.html#bitwise-or

### 红线问题

无问题

### 结构问题

无问题

### 内容问题

无问题

### 格式问题

英文文档 example格式有问题

### 主观评价

注解建议加上超链接

**Comment by Ligoml** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/39876205/162902504-01457f45-5ec6-4045-b018-f13a48d9b308.png">

note中的内容本身是有链接的，只是显示错误需要调整一下源码
此外标点符号也可以顺便改一下
