### ISSUE TITLE
paddle.bitwise_xor文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4506]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/bitwise_xor_cn.html#bitwise-xor

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/bitwise_xor_en.html#bitwise-xor

### 格式问题

英文文档Examples格式有问题

### 主观评价

建议注解加上超链接

**Comment by Ligoml** [comment]
同paddle.bitwise_or
