### ISSUE TITLE
paddle.digamma文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4507]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/digamma_cn.html#digamma

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/digamma_en.html#digamma

### 格式问题

Examples格式有问题

### 主观评价

这个文档不错

**Comment by Ligoml** [comment]
这是前端显示问题，不用管
<img width="626" alt="image" src="https://user-images.githubusercontent.com/39876205/162902948-39d7de45-6c25-4d27-8b8b-3aaca50093b6.png">
