### ISSUE TITLE
paddle.neg文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4508]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/neg_en.html#neg

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/neg_cn.html#neg

### 内容问题

英文文档没有公式

### 格式问题

example格式有问题

### 主观评价

不错

**Comment by Ligoml** [comment]
英文补一下公式
