### ISSUE TITLE
paddle.io.WeightedRandomSampler测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4509]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/WeightedRandomSampler_cn.html#weightedrandomsampler
英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/io/WeightedRandomSampler_en.html#weightedrandomsampler

### 红线问题

无

### 结构问题

中文文档：
导航栏不存在

英文文档：
导航栏不存在

### 内容问题

英文文档：
”if replacement is True“ 中的True未加深背景。
多个句子后未加句号。

中文文档：
多个句子后未加句号。

### 格式问题

无

### 主观评价

无导航栏，缺少标点

**Comment by zyl1223582136** [comment]
### PR types
Others

### PR changes
Docs

### Describe
#### 中文文档
* 将开头部分修改为：
通过制定的权重随机采样，采样下标范围在 [0, len(weights) - 1]，如果 replacement 为 True，则下标可被采样多次。

* 将参数部分修改为：

>  (numpy.ndarray|paddle.Tensor|tuple|list) - 权重序列，需要是 numpy 数组，paddle.Tensor，list 或者 tuple 类型。
num_samples (int) - 采样样本数。
replacement (bool) - 是否采用有放回的采样，默认值为 True.

* 将返回部分文字修改为：
WeightedRandomSampler，返回根据权重随机采样下标的采样器。

####英文文档
* 将参数部分修改为：

    * weights (numpy.ndarray|paddle.Tensor|list|tuple) – sequence of weights, should be numpy array, paddle.Tensor, list or tuple.
    * num_samples (int) – set sample number to draw from sampler.
    * replacement (bool) – Whether to draw sample with replacements, default True.

* 将"Returns"部分文字修改为：
a Sampler yield sample index randomly by given weights.
