### ISSUE TITLE
paddle.diagonal文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4510]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/diagonal_en.html#diagonal

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/diagonal_cn.html#diagonal

### 红线问题

英文文档出现了 This OP 

参数 中英文描述不一致  比如x。

### 格式问题

example 格式有问题

### 主观评价

中英文不一致

**Comment by Ligoml** [comment]
example 格式不用管，其他的可以修复
