### ISSUE TITLE
paddle.sin文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4511]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sin_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sin_en.html

### 红线问题

1. 对于API的功能，原文为： “计算输入的正弦值”， 建议更改为逐元素计算输入Tensor的正弦值，同时英文增加element wise
2. 英文文档中有计算公式，中文无。由于计算比较简单，建议英文删除
3. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
4. 中英文文档的代码示例不一致

### 主观评价

需要修复红线问题

**Comment by Ligoml** [comment]
问题存在，建议修复
