### ISSUE TITLE
paddle.trunc文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4513]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/trunc_cn.html#trunc

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/trunc_en.html#trunc

### 红线问题

API功能描述 与 API返回  中英文文档不一致

### 格式问题

example格式有问题

### 主观评价

还不错

**Comment by Ligoml** [comment]
内容基本一致，可以不用修复
