### ISSUE TITLE
paddle.ceil文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4514]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/ceil_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/ceil_en.html

### 红线问题

1. 英文文档中公式格式错误
2. 英文文档的参数多了with_quant_attr (BOOLEAN) ，需要删除
3. 中英文文档的代码示例不一致

### 主观评价

需要修改红线问题

**Comment by Ligoml** [comment]
问题存在，建议修复
