### ISSUE TITLE
paddle.device.is_compiled_with_npu文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4516]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_npu_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/is_compiled_with_npu_en.html

### 红线问题

1. 英文文档格式问题： 返回和代码示例为标题，需要修改

### 主观评价

修改红线问题

**Comment by Ligoml** [comment]
改一下英文的return吧
