### ISSUE TITLE
paddle.bitwise_and文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4517]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/bitwise_and_cn.html#bitwise-and

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/bitwise_and_en.html#bitwise-and

### 格式问题

example格式有问题

注解应该有超链接

### 主观评价

“输入的 N-D Tensor”  像是直译或机翻。

**Comment by Ligoml** [comment]
同paddle.bitwise_or
