### ISSUE TITLE
paddle.tolist文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4525]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tolist_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/tolist_en.html

### 红线问题

1. 英文文档**note**格式错误
2. 英文文档中有两个Return Type, 重复
3. 参数部分，中文表述为：输入的 Tensor ，数据类型为：float32、float64、bool、int8、int32、int64， 英文部分为：x is the Tensor we want to translate to list， 不是严格一致
4. 英文文档代码示例部分标题格式错误

### 主观评价

需要修改红线问题

**Comment by Ligoml** [comment]
问题存在，建议修复
