### ISSUE TITLE
paddle.batch文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4526]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/batch_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/batch_en.html

### 红线问题

- 中文文档中有警告注意部分，英文文档无
- 英文文档示例代码部分标题格式错误

### 主观评价

需要修复红线问题

**Comment by Ligoml** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/39876205/162899584-46d2e891-a028-4138-85d9-6d9e4aa454f8.png">

这是前端解析的问题，可以不用管
其他问题需要修复
