### ISSUE TITLE
paddle.tan文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4527]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tan_cn.html#tan
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/tan_en.html#tan

### 红线问题

英文文档多了参数with_quant_attr

中英文文档代码示例不一致

### 格式问题

Examples格式有问题

### 主观评价

中英文文档不太一致

**Comment by Ligoml** [comment]
文档保持一致，中文的比较好以中文为准同步在英文吧，最好加上copy-from
