### ISSUE TITLE
paddle.static.global_scope文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4528]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/global_scope_cn.html#global-scope

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/global_scope_en.html#global-scope

### 红线问题

英文文档有Api_attr而中文文档没有

### 内容问题

英文文档没有以注释给出了运行结果

### 格式问题

中英文文档都使用了numpy

### 主观评价

不太好~

**Comment by Ligoml** [comment]
问题存在，需要修复
