### ISSUE TITLE
paddle.static.default_startup_program文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4529]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/default_startup_program_cn.html#default-startup-program

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/default_startup_program_en.html#default-startup-program

### 红线问题

中文文档给 [Program](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/Program_cn.html#cn-api-fluid-program) 等API加上了超链接，而英文文档没有。

### 内容问题

没有以注释给出运行结果

### 格式问题

英文文档·多了Returns type: 

example格式有问题

### 主观评价

英文文档问题比较多

**Comment by Ligoml** [comment]
问题存在，建议修复
Returns type:和example不用管
