### ISSUE TITLE
paddle.static.nn.embedding文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4530]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/embedding_cn.html#embedding

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/embedding_en.html#embedding

### 红线问题

中英文文档的示例代码不一致。
param_attr的中英文文档不一致，”具体用法请参见 cn_api_paddle_ParamAttr 。“、
”然后使用 [to_tensor](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/to_tensor_cn.html#cn-api-paddle-to-tensor) 进行初始化，即可实现加载自定义或预训练的词向量。“英文文档没有对应的信息。

### 结构问题

英文文档有 【Api_attr】 栏  而中文文档没有。

### 格式问题

使用numpy创建输入

### 主观评价

: )

**Comment by Ligoml** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/39876205/162906846-c7527a43-b09b-4506-99d5-7e12f8ebdb99.png">
这句话改成：只需要将本地词向量转换为Tensor格式，且保证本地词向量的shape和embedding的 size 参数一致
另外红框里的引用也有问题，应该是一个可跳转链接的
