### ISSUE TITLE
paddle.static.load文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4532]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/load_cn.html#load

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/load_en.html#load

### 红线问题

英文文档有”Api_attr“  而中文文档没有

”默认值：None。“ 在中文文档参数executor有，而参数var_list没有，英文文档反过来。

### 主观评价

中英文文档有区别

**Comment by Ligoml** [comment]
参考源码实现统一中英文文档说法
