### ISSUE TITLE
paddle.static.set_program_state文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4533]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/set_program_state_cn.html#set-program-state

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/set_program_state_en.html#set-program-state

### 红线问题

中英文文档的参数state_dict 描述内容不一致

### 格式问题

英文文档多了Api_attr栏 

### 主观评价

: )

**Comment by Ligoml** [comment]
问题存在，建议修复
