### ISSUE TITLE
is_compiled_with_rocm文档评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#4535]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_rocm_cn.html#is-compiled-with-rocm

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/is_compiled_with_rocm_en.html#is-compiled-with-rocm

### 格式问题

英文文档 Returns 和 example 格式有问题

### 主观评价

！英文文档 Returns 和 example 格式有问题

**Comment by Ligoml** [comment]
问题存在，建议修复
