### ISSUE TITLE
paddle.utils.profiler.profiler

### ISSUE THREAD

**Issue by Yilingyelu** [PaddlePaddle/docs#4546]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/profiler/Profiler_cn.html#profiler
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/profiler/Profiler_en.html

### 红线问题

1. 中英文函数定义不同
2. 中英文示例代码的格式排版不同
3. 英文Examples标题排版混乱

### 主观评价

单看两篇文档都可以了解表述的内容，但是对照着看不一致

**Comment by Ligoml** [comment]
请详细说明一下什么定义不同？
