### ISSUE TITLE
paddle.static.xpu_places

### ISSUE THREAD

**Issue by Yilingyelu** [PaddlePaddle/docs#4547]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/xpu_places_cn.html#xpu-places
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/xpu_places_en.html#xpu-places

### 红线问题

1. 中英文基础描述部分不同
2. 英文的Note格式错误

### 主观评价

较好

**Comment by Ligoml** [comment]
主要问题是英文note和介绍部分混杂在一起了，建议修改
