### ISSUE TITLE
paddle.metric.accuracy文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4549]
### 文档中英文链接

- 中文： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/metric/Accuracy_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/metric/Accuracy_en.html

### 红线问题

1. 中文文档中update方法和英文文档参数不一致：
    - 中文：update(pred, label, *args)
    - 英文：update(correct, *args)
    - 参考源码，应该是中文部分有误
 2. 对于类的文档，可以考虑增加一个一级标题“方法”， 将该类下面的相关方法作为二级标题

### 主观评价

- 修复红线问题

**Comment by TCChenlong** [comment]
请：
修复中文文档中update方法和英文文档参数不一致的问题：
中文：update(pred, label, *args)
英文：update(correct, *args)
