### ISSUE TITLE
paddle.static.save

### ISSUE THREAD

**Issue by Yilingyelu** [PaddlePaddle/docs#4551]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/save_cn.html#save
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/save_en.html#save

### 红线问题

中英文参数不同

### 结构问题

英文包括Api_attr，example标题格式错误

### 主观评价

ok

**Comment by Ligoml** [comment]
中文文档需要增加configs的参数介绍
