### ISSUE TITLE
paddle_utils_deprecated

### ISSUE THREAD

**Issue by Yilingyelu** [PaddlePaddle/docs#4552]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/utils/deprecated_cn.html#paddle-utils-deprecated
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/utils/deprecated_en.html#deprecated

### 红线问题

1. 英文文档包含This function wraps a method that will soon be removed and does two things:标题
2. 中英文函数定义不同
3. 中英文参数描述不同

### 主观评价

ok

**Comment by Ligoml** [comment]
格式问题，这两个应该都是notes
