### ISSUE TITLE
paddle.log文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4553]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/log_cn.html#log
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/log_en.html

### 红线问题

1，中文原文“Log激活函数（计算自然对数）”与对应位置的英文“Calculates the natural log of the given input tensor, element-wise.”不对应。
2，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 内容问题

1，英文公式换行了。
2，中文数据类型至今使用“，”好连接。

### 主观评价

改接口功能较简单，通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
1、解决 中文原文“Log激活函数（计算自然对数）”与对应位置的英文“Calculates the natural log of the given input tensor, element-wise.”不对应 的问题
2、修复 英文公式换行 的问题
