### ISSUE TITLE
paddle.static.create_global_var文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4555]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/create_global_var_cn.html#create-global-var
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/create_global_var_en.html#create-global-var

### 红线问题

1，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。
2，中英文参数介绍，部分参数内容对不上如shape .
3，中英文示例代码不一致，中文代码缺少 paddle.enable_static()

### 主观评价

还行吧，中英文切换的看，能明白接口的意思，可以使用。

**Comment by TCChenlong** [comment]
请解决以下问题：
1、中英文参数介绍，部分参数内容对不上如shape .
2、中英文示例代码不一致，中文代码缺少 paddle.enable_static()
