### ISSUE TITLE
paddle.logical_xor文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4556]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/logical_xor_cn.html#logical-xor
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/logical_xor_en.html#logical-xor

### 红线问题

1，中文原文“该OP逐元素的对 X 和 Y 进行逻辑异或运算。”与对应位置的英文“logical_xor operator computes element-wise logical XOR on x and y, and returns out. out is N-dim boolean Tensor. Each element of out is calculated by.”不对应。
2，中英文公式格式不一致。

### 格式问题

示例代码中使用“import numpy as np”

### 主观评价

改接口功能较简单，通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
请解决以下问题：
1，中文原文“该OP逐元素的对 X 和 Y 进行逻辑异或运算。”与对应位置的英文“logical_xor operator computes element-wise logical XOR on x and y, and returns out. out is N-dim boolean Tensor. Each element of out is calculated by.”不对应。
2，中英文公式格式不一致。
谢谢~
