### ISSUE TITLE
paddle.static.nn.sequence_expand_as文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4557]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sequence_expand_as_cn.html#sequence-expand-as
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_expand_as_en.html#sequence-expand-as

### 结构问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，英文“Please note that the input x should be LodTensor or Tensor,and input y must be LodTensor.”这句话是不是注解？中英文格式不对应。
3，英文文档的两个例子是放在一起的，中文文档是分开的。
4，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 格式问题

示例代码中使用“import numpy as np”

### 主观评价

接口文档中英文内容对应不上的地方较多，英文格式也有问题。通过例子大概能明白怎么使用的。

**Comment by TCChenlong** [comment]
请：
1，删除英文文档中的“Api_attr /n Static Graph”.
2，修改英文格式，将“Please note that the input x should be LodTensor or Tensor,and input y must be LodTensor.” 调整为正文
3，将中文文档2个例子合并为1个。
