### ISSUE TITLE
paddle.static.nn.sequence_scatter文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4558]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sequence_scatter_cn.html#sequence-scatter
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_scatter_en.html#sequence-scatter

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，中英文注解格式不统一。
3，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。
4，中文数据类型至今使用“，”连接。

### 主观评价

中文文档中，参数介绍时，有些英文名词没看懂啥意思。需要中英文切换的看。

**Comment by TCChenlong** [comment]
请
1，删除英文文档中多的“Api_attr /n Static Graph”.
2，修改中文注解，使注解格式统一。
3，修复 中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样 的问题。
4，修复 中文数据类型使用“，”连接 的问题
