### ISSUE TITLE
paddle.static.nn.nce文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4559]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/nce_cn.html#nce
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/nce_en.html#nce

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，中文文档在参数介绍时，“is_sparse (bool, optional) – The flag indicating whether to use sparse update, the weight@GRAD and bias@GRAD will be changed to SelectedRows. Default False.”缺少相应的超链接。
3，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 格式问题

示例代码中使用“import numpy as np”

### 主观评价

中英文切换的看，能明白接口的意思，可以使用。

**Comment by TCChenlong** [comment]
请：
1，删除 英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph” 的问题
2，修改英文中 weight@GRAD and bias@GRAD 格式错误的问题（误解析为邮箱）
3，修复 中文‘返回’和英文的“Returns” 中英文内容不一样 的问题
