### ISSUE TITLE
paddle.static.nn.sequence_reverse文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4560]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sequence_reverse_cn.html#sequence-reverse
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_reverse_en.html#sequence-reverse

### 红线问题

1，中文文档缺少“Notes: The Op only receives LoDTensor as input. If your input is Tensor, please use reverse Op.(fluid.layers. api_fluid_layers_reverse ).”对应内容。
2，英文文档的“DynamicRNN ”没有超链接。
3，中文‘返回’和英文的“Returns”的标题及内容都不对应，中英文内容不一样。

### 主观评价

还行吧，中英文切换的看，能明白接口的意思，可以使用。

**Comment by TCChenlong** [comment]
请
1，为中文文档添加 “Notes: The Op only receives LoDTensor as input. If your input is Tensor, please use reverse Op.(fluid.layers. api_fluid_layers_reverse ).”对应内容。
2，为英文文档的“DynamicRNN ”添加超链接。
3，修改中英文返回中内容不一样的问题
