### ISSUE TITLE
paddle.shape文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4561]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/shape_cn.html#shape
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/shape_en.html#shape

### 红线问题

1，中文缺少”与对应位置的英文“Alias_main paddle.shape :alias: paddle.shape,paddle.tensor.shape,paddle.tensor.attribute.shape :old_api: paddle.fluid.layers.shape”的相关描述。
2，英文文档的“Used in the guide/tutorials”里面的链接名字是中文。
3，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 内容问题

中文数据类型至今使用“，”连接。

### 格式问题

4，示例代码中使用“import numpy as np”

### 主观评价

接口功能较简单，通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
请
1，删除英文中“Alias_main paddle.shape :alias: paddle.shape,paddle.tensor.shape,paddle.tensor.attribute.shape :old_api: paddle.fluid.layers.shape”的相关描述。
2，修改中文‘返回’和英文的“Returns”内容不一样的问题
3，修改 示例代码中使用“import numpy as np” 的问题
