### ISSUE TITLE
paddle.static.nn.sequence_pad文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4564]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sequence_pad_cn.html#sequence-pad
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_pad_en.html#sequence-pad

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，英文文档的两个例子是放在一起的，中文文档是分开的。
3，中文缺少"Returns: A Python tuple (Out, Length): the 1st is a 0 level LodTensor"对应信息。
4，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 格式问题

示例代码中使用“import numpy”

### 主观评价

接口功能较简单，通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
请
1，删除英文文档中“Api_attr /n Static Graph”.
2，将中文文档中示例合并成1个。
3，补全中文中缺少的"Returns: A Python tuple (Out, Length): the 1st is a 0 level LodTensor"对应信息。
