### ISSUE TITLE
paddle.static.nn.layer_norm文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4565]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/layer_norm_cn.html#layer-norm
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/layer_norm_en.html#layer-norm

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，英文公式换行了，格式不对。
3，中文缺少“Layer Normalization Layer”的内容。
4，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 主观评价

中文文档中，参数介绍时，有些英文名词没看懂啥意思。需要中英文切换的看。

**Comment by TCChenlong** [comment]
请：
1，删除英文文档中多的“Api_attr /n Static Graph”.
2，修正英文公式格式。
3，删除英文中“Layer Normalization Layer”的内容。
