### ISSUE TITLE
paddle.static.nn.switch_case文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4568]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/switch_case_cn.html#switch-case
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/switch_case_en.html#switch-case

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，中文文档缺少“Raises
TypeError – If the type of branch_index is not Tensor.

TypeError – If the data type of branch_index is not int32, int64 or uint8.

TypeError – If the type of branch_fns is not dict, list or tuple.

TypeError – If the elements of branch_fns is not 2-tuple.

TypeError – If the first element of 2-tuple in branch_fns is not integer.

ValueError – If the first element of 2-tuple in branch_fns is not unique.

TypeError – If the second element of 2-tuple in branch_fns is not callable.

TypeError – If default is not None but it is not callable.”相关内容。

### 主观评价

通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
请：
1、删除英文文档中多的“Api_attr /n Static Graph”.
2，删除英文文档中的“Raises
