### ISSUE TITLE
paddle.static.nn.case文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4569]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/case_cn.html#case
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/case_en.html#case

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，中文缺少“Raises
TypeError – If the type of pred_fn_pairs is not list or tuple.

TypeError – If the type of elements in pred_fn_pairs is not tuple.

TypeError – If the size of tuples in pred_fn_pairs is not 2.

TypeError – If the first element of 2-tuple in pred_fn_pairs is not a Tensor.

TypeError – If the second element of 2-tuple in pred_fn_pairs is not callable.

TypeError – If default is not None but it is not callable.”相关内容。
3，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 主观评价

还行吧，中英文切换的看，能明白接口的意思，可以使用。

**Comment by TCChenlong** [comment]
请：
1、删除英文文档中多的“Api_attr /n Static Graph”.
2，删除英文文档中的“Raises
