### ISSUE TITLE
paddle.static.nn.group_norm文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4570]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/group_norm_cn.html#group-norm
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/group_norm_en.html#group-norm

### 红线问题

1，英文文档在介绍完函数的基本信息后多了“Api_attr /n Static Graph”.
2，中文缺少“Group Normalization Layer”对应内容。
3，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 主观评价

接口写的不错，很详细

**Comment by TCChenlong** [comment]
请：
1、删除英文文档中多的“Api_attr /n Static Graph”.
2，删除英文文档中的 “Group Normalization Layer”
