### ISSUE TITLE
paddle.static.accuracy文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4572]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/accuracy_cn.html#accuracy
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/accuracy_en.html#accuracy

### 红线问题

1，中文数据类型至今使用“，”连接。
2，中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样。

### 格式问题

示例代码中使用“import numpy as np”

### 主观评价

通过示例和文档介绍可以清晰的了解用法。

**Comment by TCChenlong** [comment]
请：
1，修改中文数据类型使用“，”连接的问题
2，修复 中文‘返回’和英文的“Returns”和“Return type”的标题及内容都不对应，中英文内容不一样 的问题
3，修复 示例代码中使用“import numpy as np” 的问题
