### ISSUE TITLE
paddle.static.append_backward

### ISSUE THREAD

**Issue by Yilingyelu** [PaddlePaddle/docs#4573]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/append_backward_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/append_backward_en.html

### 红线问题

1. 中英文函数定义不同
2. 英文包含Api_attr标题
3. 英文Example标题格式错误

### 主观评价

ok

**Comment by Ligoml** [comment]
什么定义不同？请详细说明？
