### ISSUE TITLE
paddle.optimizer.AdamW文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4577]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/AdamW_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/optimizer/AdamW_en.html

### 红线问题

1. 中英文文档不一致：
    - 1）关于参数parameters的说明不一致：
        - 中文：parameters (list，可选)
        - 英文： parameters (list|tuple, optional)， 且英文部分说明更多
 2. 英文文档的代码示例段落格式错误
 3. 英文文档部分增加方法作为一级标题，将各种类的方法作为二级标题
 4. 中文文档缺少append_regularization_ops，set_state_dict(state_dict)、state_dict()等方法的描述，且中英文文档的方法的顺序也不是100%一致

### 格式问题

- 英文文档的格式需要调整

### 主观评价

需要解决上述红线问题

**Comment by TCChenlong** [comment]
请：
中英文文档不一致：
1）关于参数parameters的说明不一致：
中文：parameters (list，可选)
英文： parameters (list|tuple, optional)， 且英文部分说明更多
2）给中文文档添加append_regularization_ops，set_state_dict(state_dict)、state_dict()等方法的描述，
