### ISSUE TITLE
paddle.metric.Precision文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4578]
### 文档中英文链接

 - 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/metric/Precision_cn.html
 - 英文：
 - https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/metric/Precision_en.html

### 红线问题

1. 英文文档格式问题： 增加代码示例和方法作为一级标题
2. 中英文中对于update方法的参数说明不一致：
   - 中文：preds、labels  (numpy.array | Tensor)
   - 英文：preds 、labels (numpy.ndarray)， 英文缺少Tensor类型
4. 英文文档中reset()方法缺少返回说明
5.  英文文档中有compute(*args)方法，中文无

### 主观评价

需要修复红线问题，保持中英文一致且准确

**Comment by TCChenlong** [comment]
请：
1、修复中英文中对于update方法的参数说明不一致的问题：
    中文：preds、labels (numpy.array | Tensor)
    英文：preds 、labels (numpy.ndarray)， 英文缺少Tensor类型
2、补充英文文档中reset()方法返回说明
3、补充中文文档中compute(*args)方法说明
