### ISSUE TITLE
paddle.static.nn.multi_box_head文档测评

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/docs#4587]
### 文档中英文链接

中：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/multi_box_head_cn.html#multi-box-head
英：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/multi_box_head_en.html

### 红线问题

中英文不一致。
英文部分：论文参考，格式乱了，并到上一段了。

### 结构问题

无

### 内容问题

无

### 格式问题

无

### 主观评价

好

**Comment by TCChenlong** [comment]
请：
1、修改英文部分论文参考，另起一段
