### ISSUE TITLE
paddle.optimizer.lr.ReduceOnPlateau文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4593]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/ReduceOnPlateau_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/optimizer/lr/ReduceOnPlateau_en.html

### 红线问题

1. 中英文的代码示例部分没有用注释部分给出运行结果。通过运行结果可以直观的看到学习率的变化，更容易理解该类的作用
2. API的方法部分，中文文档大部分没有，和英文不一致

### 主观评价

需要修复红线问题

**Comment by TCChenlong** [comment]
请：
1、以注释补充每个 epoch 的LR
