### ISSUE TITLE
paddle.optimizer.lr.MultiStepDecay文档评估

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/docs#4596]
### 文档中英文链接

- 中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/MultiStepDecay_cn.html
- 英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/optimizer/lr/MultiStepDecay_en.html

### 红线问题

1. milestons参数数据类型中英文文档不一致
    - 中文：milestones (list)
    - 英文：milestones (tuple|list)
 2. 中英文的代码示例部分没有用注释部分给出运行结果。通过运行结果可以直观的看到学习率的变化，更容易理解该类的作用
3. API的方法部分，中文文档大部分没有，和英文不一致

### 主观评价

需要修改红线问题，具体如上

**Comment by TCChenlong** [comment]
请
1、修复 milestons参数数据类型中英文文档不一致的问题
中文：milestones (list)
英文：milestones (tuple|list)
2、以注释给出每个epoch的LR
