### ISSUE TITLE
paddle.static.nn.sequence_softmax

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4600]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/sequence_softmax_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_softmax_en.html

### 红线问题

中文版代码示例运行报错，需要开启静态图模式，示例代码建议copy英文版代码
英文版公式格式错乱

### 结构问题

无

### 内容问题

无

### 格式问题

英文版没导航

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
请：
1、删除 英文中 api_attr Static Graph 的描述
2、修正公式问题
