### ISSUE TITLE
paddle.static.nn.sequence_expand

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4603]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/sequence_expand_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_expand_en.html

无导航

### 红线问题

1. 中文版示例代码运行报错，为开启静态图模式，代码建议参考英文版
2. 英文版Returns标题化内容过多，参考中文版修改

### 结构问题

无

### 内容问题

无

### 格式问题

英文版Return Type: Variable未标题化

### 主观评价

关于此函数的适用场景或paddle在什么情况下用它，建议描述一下，不然用户很难理解此函数有什么用处，或者参考其他文档 增加一个使用本API的教程文档[ XXX]

**Comment by TCChenlong** [comment]
请
1、修复 英文标题
