### ISSUE TITLE
paddle.linspace

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4604]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/linspace_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/linspace_en.html

### 红线问题

无

### 结构问题

无

### 内容问题

返回值的描述中，出现笔误，mum应该为num

### 格式问题

英文版无导航

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
请修复中文文档的 `mum` 的 typo问题

**Comment by longranger2** [comment]
我已经修复好了，请验收
https://github.com/PaddlePaddle/docs/pull/5504

**Comment by Ligoml** [comment]
@longranger2 查看英文文档后发现，paddle.linspace 支持了0-D Tensor，但是中文文档中并未增加描述，辛苦一并增加一下吧~
