### ISSUE TITLE
paddle.static.nn.sequence_enumerate

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4605]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/sequence_enumerate_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_enumerate_en.html

### 红线问题

无

### 结构问题

无

### 内容问题

1. 概述部分格式异常，异常的层次结构。参考中文版修改
2. Returns标题化内容过多，参考中文版修改
3. Return Type: Variable未标题化
4. 英文版无导航

### 格式问题

无

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
请：
修改英文文档结构
