### ISSUE TITLE
paddle.stanh

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4608]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/stanh_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/stanh_en.html

### 红线问题

参数描述中没有输入值x和name的描述，参考英文版修改

### 结构问题

无

### 内容问题

无

### 格式问题

无

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
请
1、中文文档参数缺少 输入值x和name的描述
2、英文文档公式格式错误

**Comment by longranger2** [comment]
我看了下中文文档，是有对输入值x和name的描述

<img width="642" alt="image" src="https://user-images.githubusercontent.com/52858395/207562326-6d0b2af3-78db-4cb0-a0a7-ca0e15f3756e.png">

英文文档的公式的格式具体哪里有问题呢？

不过英文文档没有导航
