### ISSUE TITLE
paddle.static.auc

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4618]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/auc_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/auc_en.html

### 红线问题

1. 中英文代码示例运行均失败“InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.”

### 结构问题

无

### 内容问题

无

### 格式问题

1.  英文版Return描述格式异常，参考中文进行换行
2. 无导航

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
代码可能是因为 windows 下数据类型的问题，已于 develop版本 paddle 修复
