### ISSUE TITLE
paddle.static.nn.spectral_norm

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/docs#4619]
### 文档中英文链接

中文：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/spectral_norm_cn.html
英文：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/spectral_norm_en.html

### 红线问题

1. 英文版公式异常
2. 英文版Return的具体描述格式异常

### 结构问题

无

### 内容问题

无

### 格式问题

英文版无导航

### 主观评价

通俗易懂

**Comment by TCChenlong** [comment]
请：
1、修复英文文档公式格式问题
