### ISSUE TITLE
paddle.optimizer.lr.LRScheduler

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4620]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/LRScheduler_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/LRScheduler_cn.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/LRScheduler_en.html#:~:text=the%20schedulers%20state.-,get_lr(),-For%20those%20subclass    英文部分没有代码示例，中文有

### 内容问题

中文部分
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/LRScheduler_cn.html#:~:text=%E8%AF%B7%E5%8F%82%E8%80%83%20cn_api_paddle_optimizer_lr_PolynomialDecay   未给出链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/LRScheduler_cn.html#:~:text=%E8%AF%B7%E5%8F%82%E8%80%83-,%E5%9F%BA%E7%B1%BBLRScheduler,-%E7%9A%84%E4%BB%BB%E6%84%8F%E5%AD%90    格式问题，代码和汉字混在一起了

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/LRScheduler_cn.html#:~:text=%E5%AD%A6%E4%B9%A0%E7%8E%87%E7%AD%96%E7%95%A5%EF%BC%8C-,%E5%AF%BC%E5%87%BA%E5%9F%BA%E7%B1%BB%E7%9A%84%E6%96%B9%E6%B3%95%E4%B8%BA,-form%20paddle.optimizer  应该为引用而非导出

英文

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/LRScheduler_en.html#:~:text=Can%20be%20set%20to%20restart%20training   缺乏主语

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/LRScheduler_en.html#:~:text=%E2%80%9Clast_epoch%2C%20last_lr%E2%80%9D   引用代码格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/LRScheduler_en.html#:~:text=set_dict(state_dict)-,Loads%20the%20schedulers%20state.,-get_lr()  应该是loading吧？？

### 主观评价

总体OK，英文缺失部分代码示例

**Comment by TCChenlong** [comment]
请：
1、修复 PolynomialDecay: 多项式衰减，即得到的学习率为初始学习率和给定最终学习之间由多项式计算权重定比分点的插值。请参考 cn_api_paddle_optimizer_lr_PolynomialDecay 中链接问题
2、修改 基类LRScheduler 的格式问题
3、导出基类的方法为  -> 引用基类的方法为
