### ISSUE TITLE
paddle.optimizer.lr.StepDecay

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4622]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/StepDecay_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/StepDecay_cn.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/StepDecay_cn.html#:~:text=%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B%20%EF%BC%9A,%E4%B8%8A%E8%BF%B0%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E3%80%82

此处中英文不一致，英文没有此部分

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/StepDecay_cn.html#:~:text=%E7%8E%87%E6%8C%89%E6%8C%87%E5%AE%9A-,%E9%97%B4%E9%9A%94,-%E8%BD%AE%E6%95%B0%E8%A1%B0%E5%87%8F  epoch文档翻译不统一，有的地方翻译，有的地方不翻译，建议统一

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/StepDecay_cn.html#:~:text=%E5%A6%82%E6%9E%9C%E6%98%AF%20True%20%EF%BC%8C%E5%88%99%E5%9C%A8%E6%AF%8F%E4%B8%80%E8%BD%AE%E6%9B%B4%E6%96%B0%E6%97%B6%E5%9C%A8%E6%A0%87%E5%87%86%E8%BE%93%E5%87%BA%20stdout%20%E8%BE%93%E5%87%BA%E4%B8%80%E6%9D%A1%E4%BF%A1%E6%81%AF%E3%80%82%E9%BB%98%E8%AE%A4%E5%80%BC%E4%B8%BA%20False
此处的True和False格式不统一

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/StepDecay_cn.html#:~:text=%E4%BC%98%E5%8C%96%E5%99%A8%E7%9A%84-,optimizer.step(),-%E5%87%BD%E6%95%B0%E4%B9%8B%E5%90%8E%E8%B0%83  格式问题，建议统一这个格式

### 主观评价

有小瑕疵，格式待统一

**Comment by TCChenlong** [comment]
请：
1、间隔 -> epoch
2、统一 verbose 中 True & False 的格式
3、统一 optimizer.step() 的格式
