### ISSUE TITLE
paddle.static.deserialize_persistables

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4624]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/deserialize_persistables_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/deserialize_persistables_en.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/deserialize_persistables_en.html#:~:text=run%20load%20op.-,Returns,Program,-Examples    中文部分无此翻译说明

### 内容问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/deserialize_persistables_cn.html#:~:text=%E7%94%A8%E6%9D%A5%E6%89%A7%E8%A1%8C%20load%20op%20%E7%9A%84%20executor%20%E3%80%82   未清晰说明

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/deserialize_persistables_en.html#:~:text=Api_attr,Static%20Graph

格式问题，应该在api说明下

### 主观评价

总体问题不大，个别细节待提高

**Comment by TCChenlong** [comment]
请：
1、删除 Api_attr Static Graph 等描述
2、优化描述 `用来执行 load op 的 executor` 。
