### ISSUE TITLE
paddle.static.serialize_program

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4626]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/serialize_program_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/serialize_program_en.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/serialize_program_en.html#:~:text=Api_attr,Static%20Graph    中英文这个部分不一致

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/serialize_program_en.html#:~:text=Returns,bytes  中文部分格式和此处不一致

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/serialize_program_cn.html#:~:text=program%20%2D%20%E6%8C%87%E5%AE%9A%E6%83%B3%E8%A6%81%E5%BA%8F%E5%88%97%E5%8C%96%E7%9A%84%20program%EF%BC%8C%E9%BB%98%E8%AE%A4%E6%98%AF%20default_main_program%E3%80%82  格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/serialize_program_cn.html#:~:text=%E7%9A%84%20key%20%E5%8C%85%E6%8B%AC-,%27program%27,-%E3%80%82(%E6%B3%A8%E6%84%8F%EF%BC%9Akwargs%20%E4%B8%BB%E8%A6%81%E6%98%AF    格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/serialize_program_cn.html#:~:text=%E8%8A%82%E6%95%B0%E7%BB%84%E3%80%82-,%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8%EF%BC%9A,-ValueError%20%E2%80%93%20%E5%A6%82%E6%9E%9C%20feed_vars  格式问题，不应该作为一个小标题

### 主观评价

参数格式不一致

**Comment by TCChenlong** [comment]
请
1、删除英文文档中  Api_attr Static Graph 的描述
2、 program 参数格式说明有问题
3、修改 'program' g格式问题
4、删除中文中 抛出异常的部分
