### ISSUE TITLE
paddle.static.data

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4627]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/data_cn.html

### 红线问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/data_en.html#:~:text=Used%20in%20the%20guide/tutorials    中英文部分不一样

### 内容问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/data_cn.html#:~:text=%E6%89%A7%E8%A1%8C%E5%99%A8%EF%BC%88Executor%EF%BC%89-,feed%E6%95%B0%E6%8D%AE%E8%BF%9B%E8%AF%A5%E5%8F%98%E9%87%8F,-%2C%E5%BD%93%20dtype%20%E4%B8%BA   建议feed翻译为中文

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/data_cn.html#:~:text=%E5%85%B3%E4%BA%8ELoD%20level%E7%9A%84%E8%AF%A6%E7%BB%86%E9%80%82%E7%94%A8%E5%9C%BA%E6%99%AF%E5%92%8C%E7%94%A8%E6%B3%95%E8%AF%B7%E8%A7%81%20cn_user_guide_lod_tensor  无连接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/data_en.html#:~:text=lod_level%3D0)%5Bsource%5D-,Data%20Layer,-This%20function%20creates   中文部分无此 说明

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/data_en.html#:~:text=For%20more%20details%20about%20when%20and%20how%20to%20use%20LoD%20level%2C%20see%20user_guide_lod_tensor  无链接

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/data_en.html#:~:text=You%20can%20set-,%E2%80%9CNone%E2%80%9D,-or%20%2D1%20at  格式问题

### 主观评价

中文相对完善，英文欠缺

**Comment by TCChenlong** [comment]
请：
1、中文文档 翻译 feed
2、删除参数描述中关于 lodTensor 部分的说明
3、删除英文中的 Data Layer
4、修复 shape 中 None 格式错误的问题
