### ISSUE TITLE
paddle.static.deserialize_program

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4630]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/deserialize_program_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/deserialize_program_cn.html

### 内容问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/static/deserialize_program_en.html#:~:text=Api_attr,Static%20Graph   中文无此说明

### 主观评价

总体OK

**Comment by TCChenlong** [comment]
删除英文中的这部分描述即可
