### ISSUE TITLE
paddle.sysconfig.get_include

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4634]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/sysconfig/get_include_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/sysconfig/get_include_en.html

### 内容问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/sysconfig/get_include_cn.html#:~:text=%C2%B6-,%E8%8E%B7%E5%8F%96%E5%8C%85%E5%90%AB%E9%A3%9E%E6%A1%A8C%2B%2B%E5%A4%B4%E6%96%87%E4%BB%B6%E7%9A%84%E7%9B%AE%E5%BD%95%E3%80%82,-%E8%BF%94%E5%9B%9E   此处最好能够图示说明

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/sysconfig/get_include_cn.html#:~:text=%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E3%80%82-,%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B,-%C2%B6   与英文格式不一样

### 主观评价

格式问题

**Comment by TCChenlong** [comment]
可以补充一下文档示例，通过示例展示该API的作用
