### ISSUE TITLE
paddle.utils.run_check

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4636]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/utils/run_check_en.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/run_check_cn.html

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/utils/run_check_en.html#:~:text=on%20your%20system.-,Examples,-import%20paddle%0A%0Apaddle   格式不一样

### 主观评价

基本OK

**Comment by TCChenlong** [comment]
格式问题 会统一修复
