### ISSUE TITLE
paddle.utils.download.get_weights_path_from_url

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/docs#4637]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/download/get_weights_path_from_url_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/utils/download/get_weights_path_from_url_en.html

### 格式问题

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/utils/download/get_weights_path_from_url_en.html#:~:text=save%20downloaded%20weights.-,Return%20type,-str   格式问题，与中文不一致

### 主观评价

基本OK

**Comment by TCChenlong** [comment]
格式问题，会由前端统一修复
