### ISSUE TITLE
paddle.vision.models.alexnet

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/docs#4699]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/models/alexnet_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/vision/models/alexnet_en.html

### 红线问题

1. 文档描述与API不一致，代码无法跑通
2. 中英文代码内容不一致

### 结构问题

1. 英文没有返回
2. 中文介绍没有和函数定义间隔一行
3. 代码无输出示例

### 内容问题

示例代码中
model = alexnet()会报错，model = alexnet.AlexNet()可以运行

### 主观评价

较差，请尽快确认错误内容

**Comment by SigureMo** [comment]
唔，其他几个问题确实在 paddle.vision.models 模块下普遍存在，这些我之后应该会一并修下～

但想问下「代码无法跑通」的问题，我这里完全无法复现呀，我同样是使用的示例代码，paddle 版本是 2.3.0-rc0，但是可以运行的呀，在 AI Studio 上试了下也是没问题的……

<img width="522" alt="image" src="https://user-images.githubusercontent.com/38436475/165827235-efbd1dd1-6a1c-4545-b7fe-00835f222198.png">
