### ISSUE TITLE
paddle.vision.models.ResNet文档评估

### ISSUE THREAD

**Issue by olinquantum** [PaddlePaddle/docs#4796]
### 文档中英文链接

中文链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/models/ResNet_cn.html#resnet
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/vision/models/ResNet_en.html#resnet

### 红线问题

1）中文文档缺少参数“groups (int, optional) – number of groups for each convolution block, Default: 1.”的介绍。
2）英文文档缺少“返回
ResNet模型，Layer的实例。”的对应说明。
3)英文文档这部分内容没看明白，“forward(inputs)
Defines the computation performed at every call. Should be overridden by all subclasses.
Parameters

*inputs (tuple) – unpacked tuple arguments

**kwargs (dict) – unpacked dict argument”

### 主观评价

中英文文档都缺少东西，不太理解。
本地环境有点问题，配置好后，提交PR。

**Comment by SigureMo** [comment]
问题 1 是因为 #4322 还没有合并导致的啦～2、3 不太清楚……
