### ISSUE TITLE
paddle.nansum

### ISSUE THREAD

**Issue by xiongjunfeng** [PaddlePaddle/docs#4980]
### 文档中英文链接

https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nansum_en.html#nansum
缺中文版

### 主观评价

可以读懂

**Comment by xiehuanyi** [comment]
你好，我刚刚fork了paddle文档的repository，看到里面是有nansum_cn.rst文件的，里面中文文档应该是写好了的，请问这样的话这个issue还能用来练手吗
