### ISSUE TITLE
paddle.nanquantile()

### ISSUE THREAD

**Issue by mrcangye** [PaddlePaddle/docs#5054]
### 文档中英文链接

中文链接：缺失
英文链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nanquantile_en.html

### 红线问题

中文文档缺失！

### 主观评价

缺失中文文档，需要补充中文文档

**Comment by Asthestarsfalll** [comment]
中文文档在这儿：https://github.com/PaddlePaddle/docs/pull/4657
