### ISSUE TITLE
第六轮评估第四组API 评估

### ISSUE THREAD

**Issue by ReganYue** [PaddlePaddle/docs#5144]
### 文档中英文链接

paddle.nn.CELU

paddle.nn.functional.celu

paddle.nn.ChannelShuffle

paddle.nn.functional.channel_shuffle

paddle.nn.CosineEmbeddingLoss

paddle.nn.functional.cosine_embedding_loss

paddle.nn.CosineSimilarity

paddle.nn.functional.cosine_similarity

paddle.nn.CrossEntropyLoss

paddle.nn.functional.cross_entropy

### 主观评价

```
paddle.nn.CELU				good
paddle.nn.functional.celu				中英文参数不一致
paddle.nn.ChannelShuffle				英文文档参数data_format没有标记可选   
paddle.nn.functional.channel_shuffle				中英文API描述不一致，英文文档参数data_format可选  有Return type
paddle.nn.CosineEmbeddingLoss				英文文档Shape格式有问题
paddle.nn.functional.cosine_embedding_loss				英文文档参数格式有问题 
paddle.nn.CosineSimilarity				good
paddle.nn.functional.cosine_similarity				good
paddle.nn.CrossEntropyLoss				中英文参数描述不一致，且英文文档参数属性为空
paddle.nn.functional.cross_entropy				中文文档该OP  中英文文档参数多处不一致
```

**Comment by Dandelight** [comment]
For `paddle.nn.functional.celu`: <https://github.com/PaddlePaddle/Paddle/pull/48074>
