### ISSUE TITLE
【社区治理】SigureMo 发起 Committer 身份申请

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/docs#5230]
## 基本信息

| 申请人 GitHub ID | **docs Repo 整体 merge PR 数**                                                           | **docs Repo 整体 review PR 数**                                                                                 | **docs Repo 整体报告 Issue 数**                                                 |
| ---------------- | ---------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| SigureMo         | [28](https://github.com/PaddlePaddle/docs/pulls?q=is%3Apr+is%3Amerged+author%3ASigureMo) | [9](https://github.com/PaddlePaddle/docs/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3ASigureMo+-author%3ASigureMo) | [2](https://github.com/PaddlePaddle/docs/issues?q=is%3Aissue+author%3ASigureMo) |

## 社区贡献概况

以下是此前在本 repo 里做过的贡献：

- 为 Paddle repo 贡献的 API 写文档
- 修复部分 API 文档及一些 typo 之类的
- 为所有文档添加自动在中英文之间添加空格的 hook，并使 API 文档（rst 文件）也受部分 hook 的约束，以统一文档格式规范
- review 部分 API 文档（含部分文档修复和部分 Hackathon 任务）

至于理由嘛，主要是 review 时有时候让贡献者自己改太麻烦了，有时候往往需要沟通很多遍才能达到满意的效果（比如修改部分有遗漏和代码风格等问题）

### 高质量 merged PR 展示

都不咋样呀，不算高质量～

| PR 号                             | PR 标题                                                                                | PR 简介                                                           | Reviewer                      |
| --------------------------------- | -------------------------------------------------------------------------------------- | ----------------------------------------------------------------- | ----------------------------- |
| #3914, #3921, #3922, #3924, #4034 | [PaddlePaddle Hackathon] add GoogLeNet cn docs, ...                                    | 第一期 Hackathon 任务 API 文档                                    | TCChenlong                    |
| #4176                             | add MobileNetV3 cn docs                                                                | MobileNetV3 API 文档                                              | TCChenlong                    |
| #4929                             | fix paddle.Model cn docs                                                               | 修复 paddle.Model 文档                                            | Ligoml                        |
| #4322, #4936                      | fix paddle.vision.models.\* cn docs                                                    | 修复 paddle.vision.models 下全部 API 文档                         | Ligoml                        |
| #4944                             | fix paddle.vision.datasets.\* cn docs                                                  | 修复 paddle.vision.datasets 下全部 API 文档                       | Ligoml                        |
| #4964                             | \[Docs\]\[cn\] make the word case correct                                              | 修复专有名词的大小写                                              | Ligoml                        |
| #4973                             | \[Docs\]\[hook\] add a pre-commit hook to automatically insert space to cn and en char | 添加一个自动在中英文间添加空格的 hook，并文本 hook 应用于全部文档 | Ligoml, betterpig             |

### 高质量 review PR 展示

| PR 号          | PR 标题                                                               | PR 简介                        | review 详情                            |
| -------------- | --------------------------------------------------------------------- | ------------------------------ | -------------------------------------- |
| #4978          | 修复 paddle.amax、paddle.amin 的参数问题，删除多个 API 中【返回类型】 | 文档修复                       | 文档格式和规范建议等                   |
| #5089          | 【PaddlePaddle Hackathon 3】5 新增 API bucketize                      | 第三期 Hackathon 任务 API 文档 | 中英文一致性建议、API 参数建议等       |
| #5107          | 【PaddlePaddle Hackathon 3 No.17】为 Paddle 新增 sgn 文档           | 第三期 Hackathon 任务 API 文档 | 中英文一致性建议、格式建议等           |
| #5111          | fix cn docs in fft and io.dataset                                     | 文档修复                       | 公式格式建议等                         |
| #5136          | update paddle.nn.Pad1D/2D/3D cn docs                                  | 文档修复                       | 文档格式和规范建议等                   |
| #5161          | 【PaddlePaddle Hackathon 3】13 新增 API triu_indices                  | 第三期 Hackathon 任务 API 文档 | 文档格式和代码风格建议等               |
| #5192          | update PixelShuffle api                                             | 文档修复                       | 公式建议等                             |

### 代表性 Issue 展示

| Issue 号       | Issue 标题                                              | Issue 简介               | 解决情况                                                   |
| -------------- | ------------------------------------------------------- | ------------------------ | ---------------------------------------------------------- |
| #5140          | pre-commit 在大小写敏感文件系统上运行失败的临时解决方案 | 如题                     | closed by #5174                                            |
| #4935          | 除大小写外同名 API 在侧边栏排序不稳定的问题             | 文档前端问题             | 迁移至 https://github.com/PaddlePaddle/Paddle/issues/44009 ，待解决 |

#### 担保人意见

@Ligoml

**Comment by Ligoml** [comment]
谦虚了，@SigureMo 的很多工作对于飞桨文档来说都意义重大
- API 文档修复工作，修正了相当数量的 API 中英文文档，使得飞桨 API 文档在准确性和易用性上有了很大的提升
- 为 pre-commit 增加 hook 的工作，使得后续增加的文档都能保持格式的统一，也减轻了修复与后续 review 的工作量
- 主动参与 PR review 的工作，帮助社区内的其他开发者及时修正自己的文档错误
- issue 方面提出了诸多官网前端问题及大小写不敏感导致的 repo 管理问题，目前一部分问题已被解决

因此，推荐 SigureMo 成为 docs repo 的 Committer，为飞桨开源社区治理发挥更加积极的作用~~
 
cc @jzhang533

**Comment by jzhang533** [comment]
+1 

@SigureMo 不仅为飞桨社区做出了非常有意义的文档贡献，在Paddle仓库下做了很多非常有价值的贡献。同时，在社区里积极交流技术和经验。

**Comment by jzhang533** [comment]
committer access is granted.
have fun in your new responsibility.

cc: @XiaoguangHu01 @raindrops2sea

**Comment by Ligoml** [comment]
申请规则详见：[飞桨框架代码仓库的角色及权限介绍](https://github.com/PaddlePaddle/community/blob/master/contributors/community-membership.md)
