### ISSUE TITLE
中文概述处超链接指向容易引起困惑

### ISSUE THREAD

**Issue by caolonghao** [PaddlePaddle/docs#5308]
### 文档链接&描述 Document Links & Description

中文概述处
[提PR来修复一个bug](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/10_contribution/local_dev_guide_cn.html)
以及
[提PR来实现一个新功能](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/10_contribution/local_dev_guide_cn.html)
的超链接会跳转至使用指南，使用逻辑上容易造成疑惑和混乱。将这两处的超链接修改为文档中PR指南的链接
https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/git_guides/submit_pr_guide_cn.html
更符合中文使用逻辑

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

一个简单的修正
#5307

**Comment by Ligoml** [comment]
感谢贡献~已回复comment，请参考：https://github.com/PaddlePaddle/docs/pull/5307#pullrequestreview-1135174222
