### ISSUE TITLE
[documentation] git操作教程文档征集

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/docs#5402]
#  一、项目背景介绍

为了更好地与实践环境对接，降低AI开发应用门槛，加速推动AI规模化落地，现结合用户评测反馈，提议共建梳理一套针对不同系统、环境准备搭建的使用说明文档，方便用户解决除框架外，环境搭建过程中所遇到繁琐问题，诚邀各位同学一起加入文档设计与撰写。

---

# 二、项目说明

目前结合用户需求反馈 ，需要梳理的内容主要分为以下几个方向：
1. windows , Linux , mac 等主流操作系统python环境的安装与更新
2. 集成环境开发工具的安装与构建 ：
pycharm ， vs code , Visual Studio , anaconda 等工具的下载，插件安装，镜像配置等
3.  TortoiseGit ，Source Tree 等工具在不同操作系统中安装和使用详细 (包含user信息配置）
4. (未完待续，欢迎各位同学提出idea) 

---

# 三、参与流程
个人认领 ： 
      每个同学可以更具个人兴趣爱好认领喜欢的课题，进行文档的设计和撰写。
任务认领只需在下属表格中填写对应的`课题名` 与 `认领人` 即可 ， 
组队认领 ：
       如进行多人组队认领同一课题，只需在`认领人 `将全体成员名称 or 团队名称_团队人数(5人以上)即可

成果物提交：
      课题整理文档统一使用md文件格式撰写，文档整理完毕后，请在`项目成果物路径`栏填写文件路径 

| `课题名`   | 认领人 |  项目成果物路径 |
| :------------- | :----------: | ------------: |
| window系统python环境的安装与更新        |    xxx     |   xxxx |

---

# 四、答疑
在整理过程中，有任何问题，都可以在群中或此ISSUE下进行提问，我们会尽快解答你的问题~

---
# 五、最后
再一次感谢你参与本次任务，我们会认真参考您的成果物文档，打造最好用的深度学习框架！

若对往期活动感兴趣，请前往[【PPSIGs】](https://github.com/PaddlePaddle/community/tree/master/ppsigs)中的【PPSIG Uuability】处进行了解。

如果您对产品体验评测任务感兴趣，可以直接联系13957128876（微信） 或 扫码加入我们。
 
![image](https://user-images.githubusercontent.com/79358023/199927711-ddb4dc73-914e-42a6-9134-f477e0d470ee.png)

**Comment by gouzil** [comment]
GitHub for Desktop (没中文) 和 Source Tree (有中文) 也是比较常见的git可视化工具可以考虑添加

**Comment by whisky-12** [comment]
好的 收到，我这边添加下


&nbsp;


→孤←&nbsp;vermouth￡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/docs] [documentation] git操作教程文档征集 (Issue #5402)





 
GitHub for Desktop (没中文) 和 Source Tree (有中文) 也是比较常见的git可视化工具可以考虑添加
