### ISSUE TITLE
《零基础实践深度学习》的章节：使用Python和NumPy构建神经网络模型

### ISSUE THREAD

**Issue by coderbullbull** [PaddlePaddle/docs#5601]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/tutorials/projectdetail/4497974

![image](https://user-images.githubusercontent.com/54444805/216028963-b56c5029-e252-43f9-b2e9-c7f1752ee651.png)

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

感觉这个权重的数量应该是13？

**Comment by tngt** [comment]
> ### 文档链接&描述 Document Links & Description
> https://www.paddlepaddle.org.cn/tutorials/projectdetail/4497974
> 
> ![image](https://user-images.githubusercontent.com/54444805/216028963-b56c5029-e252-43f9-b2e9-c7f1752ee651.png)
> 
> ### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it
> 感觉这个权重的数量应该是13？

波士顿房价预测数据集共包含13个特征，它们分别是：

CRIM：城镇人均犯罪率
ZN：占地面积超过2.5万平方英尺的住宅用地比例
INDUS：城镇中非零售业务的比例
CHAS：查尔斯河（Charles River）虚拟变量，如果观测到河流则为1，否则为0
NOX：一氧化氮浓度（每千万份）
RM：每个住宅的平均房间数
AGE：1940年以前建造的自用单位的比例
DIS：距离五个波士顿就业中心的加权距离
RAD：径向高速公路的可达性指数
TAX：每10,000美元的全值财产税率
PTRATIO：城镇中的师生比例
B：城镇黑人比例
LSTAT：人口中地位较低者的百分比

因此该公式w权重w0-w12共13个是没问题的。
