### ISSUE TITLE
PyTorch 1.13 与 Paddle 2.4  API 映射文档开源任务

### ISSUE THREAD

**Issue by Fancy-hjyp** [PaddlePaddle/docs#5691]
✨ **问题描述**：

   大家好，为了更好地将 PyTorch 代码转写成 Paddle 代码，对外开放  `PyTorch 1.13` 与 ` Paddle 2.4` 之间的API映射关系的编写任务，欢迎大家提 PR 来一起完善🎉🎉🎉。通过本次活动，可以更详细地了解 PyTorch 框架与 Paddle 框架的 API 。

  该工作的本质是两者框架API的映射关系分析，涉及到较多的人工代码分析工作。关于如何编写 API 映射关系，为保证文档格式统一与可读性，请参照 [API 映射关系-格式规范与模板](https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/model_convert/convert_from_pytorch/api_difference/pytorch_api_mapping_format_cn.md) 来编写。

**注意：请严格根据格式规范来编写文档，避免因格式问题增加不必要的review成本，不满足格式规范的PR将不予合入。**

🍻 **你需要做的是**：

   1. Fork [PaddlePaddle/docs](https://github.com/PaddlePaddle/docs) 项目。

   2. 为每个 `API` 编写对应的 `md` 文件放入`docs/guides/model_convert/convert_from_pytorch/api_difference`对应文件夹下，文件名以 PyTorch 框架中的方法命名。例如`torch.nn.functional.adaptive_avg_pool1d.md`需要放在`docs/guides/model_convert/convert_from_pytorch/api_difference/functional`文件夹下。
   3. 如果发现已经有该API对应的 `.md`，则请不要重复新建文件，只需要校对之前写的是否完全正确并在原来基础上修改。
   4. 如果属于第7类 `功能缺失`，则也不需要新建文件，但需要在 PR 的 comment 中说明哪些API 功能缺失。
   5. 提交 PR 。

   我们会将 API 每 10 个分为一组，存放在[在线文档链接](https://docs.qq.com/sheet/DQlFWWGpnYk9IWkVI?tab=BB08J2), 认领的同学在 issue 下回复认领的任务组 ID 即可，欢迎大家认领任务和提 PR ~。

**注：** 
   1. **该任务时间：PR 截止合入时间是6月15日，之后请勿提交。**
   2. **认领规则：直接在 issue 下回复认领的任务组 ID 。**
   4. **PR 标题格式：映射文档 No. xxx** （该任务 PR 较多，请大家遵守标题格式，避免遗漏审核）
   6. **提交PR前请参照[官网](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/code_contributing_path_cn.html)安装`pre-commit`，检查代码格式。否则CI可能无法通过。**
   7. **PR请通过CI检查后再发起review，避免增加不必要的review成本。**
   8. 可使用提 PR 辅助工具来加速工作：https://github.com/PFCCLab/PaddleAutoProject ，关于这个工具的使用问题，可以 @Liyulingyue 讨论
   9. **PR 通过 CI 后，可以评论里 @Tomoko-hjf （初审）**，初审通过后； @Tomoko-hjf 会统一提交二审及合入。
   10. [历史上的 good first issue 列表](https://github.com/PaddlePaddle/community/tree/master/pfcc#good-first-issue)，也欢迎来提 PR 解决~ 欢迎联系花花加入社区，和我们一起[快乐开源](https://github.com/PaddlePaddle/Paddle/issues/48019)！
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39876205/213131273-361d2bb8-ea48-4f62-9603-0b0401f50337.png">

**Comment by Fancy-hjyp** [comment]
🍻 **任务列表**（整体进度 39/95）
> 按 merge 的时间顺序，排名不分先后： @DrRyanHuang (2)  @enkilee(1) @ccsuzzh (1) @Ainavo (4)  @Yang-Changhui(1)  @jjyaoao(1) @hongtushi(1)  @YouZijun97(1) @Supershutu(1) @zeyuxionghust(1) @zade23(1) @comeony(1) @zhug777(1)  @Liyulingyue(1) @WLApollo(1) @Kurunie(1)  @eternalmeteor(1)  @PikG09(1) @zpc2024(1) @xianyu11-x(1) @wenyin(1) @ranchongzhi(1)  @Lihuannn(1)  @Archor001(1) @YaxAda(1)  @whyn0tdance(1) @carloscjl(2) @YiZoey (1)  @TzssZ(1)  @Don-LZ(1)  @Hzwords(1) @co63oc(3)


|                         分组 ID                        |                          认领人 Github                               |                          修复 PR 链接                                 |
| ----------------------------- | ---------------------------------------------- | ---------------------------------------- |
|  1 ✅(2023/3/21) |      @DrRyanHuang           |  https://github.com/PaddlePaddle/docs/pull/5699     |
|  2 ✅(2023/3/21)  |      @DrRyanHuang               |  https://github.com/PaddlePaddle/docs/pull/5702     |
|  3  |       @DrRyanHuang              |       |
|  4  |      @DrRyanHuang               |       |
|  5  |      @DrRyanHuang               |       |
|  6   ✅(2023/3/31) |      @enkilee    |     https://github.com/PaddlePaddle/docs/pull/5757    |
|  7  ✅(2023/4/6)  |       @Ainavo    |   https://github.com/PaddlePaddle/docs/pull/5727    |
|  8  ✅(2023/4/6) |       @Ainavo       |   https://github.com/PaddlePaddle/docs/pull/5727    |
|  9  ✅(2023/4/6)  |       @Ainavo       |   https://github.com/PaddlePaddle/docs/pull/5727    |
|  10  ✅(2023/4/6)  |      @Ainavo       |   https://github.com/PaddlePaddle/docs/pull/5727    |
|  11 ✅(2023/4/25) |      @Liyulingyue    | https://github.com/PaddlePaddle/docs/pull/5709      |
|  12  |      @sanbuphy    |       |
|  13  |     @WADreaming  |       |
|  14 ✅(2023/4/21)   |     @zade23  |    https://github.com/PaddlePaddle/docs/pull/5747   |
|  15  |     @zade23  |       |
|  16  |        @kewuyu     | https://github.com/PaddlePaddle/docs/pull/5725      |
|  17 ✅(2023/4/15) |      @YouZijun97    |  https://github.com/PaddlePaddle/docs/pull/5778   |
|  18 ✅(2023/4/11) |     @jjyaoao   |   https://github.com/PaddlePaddle/docs/pull/5742    |
|  19  |    @stqcheck   |       |
|  20  ✅(2023/4/11) |     @hongtushi  |   https://github.com/PaddlePaddle/docs/pull/5733    |
|  21  |     @honglili-ya   |       |
|  22  ✅(2023/4/6) |      @Yang-Changhui   |    https://github.com/PaddlePaddle/docs/pull/5751   |
|  23 ✅(2023/4/25) |   @WLApollo    |   https://github.com/PaddlePaddle/docs/pull/5798    |
|  24✅(2023/4/3)  |      @ccsuzzh             |  https://github.com/PaddlePaddle/docs/pull/5756     |
|  25 ✅(2023/4/21) |   @Supershutu     |    https://github.com/PaddlePaddle/docs/pull/5808   |
|  26 ✅(2023/4/21)  |    @zeyuxionghust   |   https://github.com/PaddlePaddle/docs/pull/5799    |
|  27 ✅(2023/4/25) |    @zpc2024   |    https://github.com/PaddlePaddle/docs/pull/5821   |
|  28  |    @ShiJiawenwen  |       |
|  29  |    @potato-asuteed-potato    |       |
|  30  |       |       |
|  31  |   @potato-asuteed-potato    |   https://github.com/PaddlePaddle/docs/pull/5806    |
|  32 ✅(2023/4/25)  |   @zhug777   |   https://github.com/PaddlePaddle/docs/pull/5820    |
|  33  |   @CaiFuyao  |       |
|  34  |    @cccbbbttt  |   https://github.com/PaddlePaddle/docs/pull/5825    |
|  35  ✅(2023/4/28) |    @PikG09   |  https://github.com/PaddlePaddle/docs/pull/5832     |
|  36  ✅(2023/4/25)  |   @comeony    |  https://github.com/PaddlePaddle/docs/pull/5823     |
|  37  ✅(2023/4/28) |   @Kurunie    |   https://github.com/PaddlePaddle/docs/pull/5837    |
|  38  ✅(2023/4/28) |    @eternalmeteor   |   https://github.com/PaddlePaddle/docs/pull/5833    |
|  39  ✅(2023/5/12) |   @YaxAda    |   https://github.com/PaddlePaddle/docs/pull/5851    |
|  40  ✅(2023/5/12) |  @carloscjl     |  https://github.com/PaddlePaddle/docs/pull/5841     |
|  41 ✅(2023/5/9) |  @Lihuannn     |  https://github.com/PaddlePaddle/docs/pull/5835     |
|  42  |    @Drunkriver   |       |
|  43  |   @YaxAda    |       |
|  44  ✅(2023/5/12)  |  @TzssZ     |  https://github.com/PaddlePaddle/docs/pull/5827     |
|  45  ✅(2023/5/25) |  @Don-LZ    |  https://github.com/PaddlePaddle/docs/pull/5834     |
|  46  ✅(2023/5/06)  |   @xianyu11-x    |   https://github.com/PaddlePaddle/docs/pull/5854    |
|  47  ✅(2023/5/12) |   @Archor001    |   https://github.com/PaddlePaddle/docs/pull/5858    |
|  48  ✅(2023/5/12) |  @YiZoey     |  https://github.com/PaddlePaddle/docs/pull/5840     |
|  49  ✅(2023/5/12) |  @whyn0tdance    |  https://github.com/PaddlePaddle/docs/pull/5849   |
|  50  |       |       |
|  51  |  @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  52  |  @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  53  |   @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  54  ✅(2023/5/9)  |   @ranchongzhi    |  https://github.com/PaddlePaddle/docs/pull/5852     |
|  55  |    @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  56  |    @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  57  |  @daishuangbiao   |       |
|  58  |     @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  59 ✅(2023/5/9)  |  @wenyin      |  https://github.com/PaddlePaddle/docs/pull/5857     |
|  60  |   @co63oc      |  https://github.com/PaddlePaddle/docs/pull/5919     |
|  61 ✅(2023/6/7)  |  @co63oc     |   https://github.com/PaddlePaddle/docs/pull/5902    |
|  62✅(2023/6/13)  |    @co63oc   |   https://github.com/PaddlePaddle/docs/pull/5912    |
|  63 ✅(2023/6/13)  |   @co63oc    |    https://github.com/PaddlePaddle/docs/pull/5912   |
|  64  |   @co63oc    |  https://github.com/PaddlePaddle/docs/pull/5915     |
|  65  |    @co63oc   |  https://github.com/PaddlePaddle/docs/pull/5915     |
|  66  |  @Drunkriver     |       |
|  67  |     @honglili-ya    |       |
|  68  |    @xiaoheicheng   |   https://github.com/PaddlePaddle/docs/pull/5865    |
|  69  |   @co63oc    |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  70  ✅(2023/5/25) |   @Hzwords     |  https://github.com/PaddlePaddle/docs/pull/5860     |
|  71  |   @co63oc    |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  72 ✅(2023/5/16) |    @carloscjl   |  https://github.com/PaddlePaddle/docs/pull/5869     |
|  73  |  @co63oc     |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  74  |   @co63oc    |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  75  |  @co63oc     |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  76  |   @co63oc    |    https://github.com/PaddlePaddle/docs/pull/5915   |
|  77  |   @co63oc    |    https://github.com/PaddlePaddle/docs/pull/5915   |
|  78  |  @co63oc     |   https://github.com/PaddlePaddle/docs/pull/5915    |
|  79  |  @zhangtailai     |  https://github.com/PaddlePaddle/docs/pull/5853     |
|  80  |       |       |
|  81  |       |       |
|  82  |       |       |
|  83  |       |       |
|  84  |       |       |
|  85  |       |       |
|  86  |       |       |
|  87  |       |       |
|  88  |       |       |
|  89  |       |       |
|  90  |       |       |
|  91  |       |       |
|  92  |       |       |
|  93  |       |       |
|  94  |       |       |
|  95  |       |       |

**Comment by DrRyanHuang** [comment]
<html>
<body>


分组 ID | 认领人 Github  | PR
-- | -- | --
1 | DrRyanHuang  |  https://github.com/PaddlePaddle/docs/pull/5699
2 |  DrRyanHuang |  https://github.com/PaddlePaddle/docs/pull/5702
3 | DrRyanHuang  |  
4 |  DrRyanHuang |  
5 |  DrRyanHuang | 


</body>
</html>

**Comment by ccsuzzh** [comment]
分组 ID | 认领人 Github | PR
-- | -- | --
24 | ccsuzzh |  https://github.com/PaddlePaddle/docs/pull/5756

**Comment by kewuyu** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
16 | kewuyu |  


</body>
</html>

**Comment by enkilee** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
6 | enkilee |   https://github.com/PaddlePaddle/docs/pull/5757


</body>
</html>

**Comment by Ainavo** [comment]
7、8、9、10

**Comment by Liyulingyue** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
11| Liyulingyue|  https://github.com/PaddlePaddle/docs/pull/5709


</body>
</html>

**Comment by sanbuphy** [comment]
认领 12

**Comment by WADreaming** [comment]
认领13

**Comment by stqcheck** [comment]
你好，API石墨文档的链接没有权限查看。是要认领才能查看相关任务吗

**Comment by Fancy-hjyp** [comment]
> 你好，API石墨文档的链接没有权限查看。是要认领才能查看相关任务吗

分享链接失效了，已修复好~

**Comment by siyuanling** [comment]
您好，链接现在失效了，能麻烦再重新设置一下吗

**Comment by Fancy-hjyp** [comment]
> 您好，链接现在失效了，能麻烦再重新设置一下吗

好的，这次应该可以了~

**Comment by zade23** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
14 | zade23 | https://github.com/PaddlePaddle/docs/pull/5747
15 | zade23 | 


</body>
</html>

**Comment by hongtushi** [comment]
分组 ID | 认领人 Github | PR
-- | -- | --
20 | hongtushi| --

**Comment by stqcheck** [comment]
| 分组ID       | 认领人Github   |  PR  |
| --------   | -----:     | :----:  |
| 19      | stqcheck |        |

**Comment by honglili-ya** [comment]
认领67

**Comment by jjyaoao** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
18 | jjyaoao |  https://github.com/PaddlePaddle/docs/pull/5742


</body>
</html>

**Comment by Yang-Changhui** [comment]
<html>
<body>


分组 ID | 认领人 Github | PR
-- | -- | --
22 | Yang-Changhui |  


</body>
</html>

**Comment by Waylon7** [comment]
分组 ID | 认领人 Github | PR
-- | -- | --
17 | YouZijun97 |

**Comment by honglili-ya** [comment]
认领21

**Comment by Supershutu** [comment]
认领25

**Comment by WLApollo** [comment]
认领23

**Comment by potato-asuteed-potato** [comment]
认领26

**Comment by potato-asuteed-potato** [comment]
认领31

**Comment by WLApollo** [comment]
认领23

**Comment by WLApollo** [comment]
认领23

**Comment by WLApollo** [comment]
认领23

**Comment by potato-asuteed-potato** [comment]
认领31

**Comment by zeyuxionghust** [comment]
26

**Comment by zeyuxionghust** [comment]
> 26

@Tomoko-hjf 
是否能帮我check 一下PR，https://github.com/PaddlePaddle/docs/pull/5799

**Comment by potato-asuteed-potato** [comment]
认领29

**Comment by zhug777** [comment]
认领32

**Comment by CaiFuyao** [comment]
认领28

**Comment by CaiFuyao** [comment]
认领33

**Comment by zpc2024** [comment]
认领27

**Comment by ShiJiawenwen** [comment]
认领28

**Comment by comeony** [comment]
认领 36

**Comment by zhug777** [comment]
> 认领32

@Tomoko-hjf 麻烦帮我查看一下PR[#5820](https://github.com/PaddlePaddle/docs/pull/5820)，谢谢

**Comment by PikG09** [comment]
认领35

**Comment by Kurunie** [comment]
认领37

**Comment by cccbbbttt** [comment]
认领29

**Comment by cccbbbttt** [comment]
认领34

**Comment by YaxAda** [comment]
认领39

**Comment by cccbbbttt** [comment]
你好，我认领的是34.




程斌涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/docs] PyTorch 1.13 与 Paddle 2.4  API 映射文档开源任务 (Issue #5691)





 
认领39

**Comment by eternalmeteor** [comment]
认领38

**Comment by TzssZ** [comment]
认领44

**Comment by Don-LZ** [comment]
认领45

**Comment by Lihuannn** [comment]
认领41

**Comment by YaxAda** [comment]
认领43

**Comment by YaxAda** [comment]
认领43

**Comment by y3oZ** [comment]
认领48

**Comment by carloscjl** [comment]
认领40

**Comment by daishuangbiao** [comment]
认领57

**Comment by Drunkriver** [comment]
认领66

**Comment by daishuangbiao** [comment]
认领57

**Comment by Drunkriver** [comment]
认领42

**Comment by whyn0tdance** [comment]
认领47

**Comment by whyn0tdance** [comment]
认领49

**Comment by zhangtailai** [comment]
认领79

**Comment by wenyin** [comment]
认领66

**Comment by wenyin** [comment]
认领59

**Comment by ranchongzhi** [comment]
|分组ID|认领人Github|PR|
|:-:|:-:|:-:|
|54|[ranchongzhi](https://github.com/ranchongzhi)|[#5852 ](https://github.com/PaddlePaddle/docs/pull/5852)|

**Comment by xianyu11-x** [comment]
认领46

**Comment by Archor001** [comment]
认领47

**Comment by Hzwords** [comment]
认领70

**Comment by xiaoheicheng** [comment]
认领52

**Comment by xiaoheicheng** [comment]
认领60

**Comment by xiaoheicheng** [comment]
认领68

**Comment by carloscjl** [comment]
认领72

**Comment by Hzwords** [comment]
Hzwords:my-cool-stuff

**Comment by Hzwords** [comment]
https://github.com/PaddlePaddle/docs/pull/5860

**Comment by Hzwords** [comment]
[https://github.com/PaddlePaddle/docs/pull/5860](url)

**Comment by Hzwords** [comment]
#5860

**Comment by co63oc** [comment]
映射文档 No.61 
62 63
64 65 69 71 73 74 75 76 77 78 
51, 52, 53, 55, 56, 58, 60

**Comment by luotao1** [comment]
【PyTorch 1.13 与 Paddle 2.4 API 映射文档开源任务】已升级为如下任务
- https://github.com/PaddlePaddle/PaConvert/issues/112

本任务先关闭，已经提交的PR会 review 完成，但不再接受新的 PR，感谢所有参与的小伙伴

> @DrRyanHuang (2) @enkilee(1) @ccsuzzh (1) @Ainavo (4) @Yang-Changhui(1) @jjyaoao(1) @hongtushi(1) @YouZijun97(1) @Supershutu(1) @zeyuxionghust(1) @zade23(1) @comeony(1) @zhug777(1) @Liyulingyue(1) @WLApollo(1) @Kurunie(1) @eternalmeteor(1) @PikG09(1) @zpc2024(1) @xianyu11-x(1) @wenyin(1) @ranchongzhi(1) @Lihuannn(1) @Archor001(1) @YaxAda(1) @whyn0tdance(1) @carloscjl(2) @YiZoey (1) @TzssZ(1) @Don-LZ(1) @Hzwords(1) @co63oc(3)
