### ISSUE TITLE
paddle.static.nn.nce示例代码报错

### ISSUE THREAD

**Issue by XieYunshen** [PaddlePaddle/docs#5868]
### 文档链接&描述 Document Links & Description

paddle.static.nn.nce示例代码有问题
![image](https://user-images.githubusercontent.com/6836917/236728207-0eb9dcf3-2e67-409c-a9a9-b50a23a25644.png)

示例代码地址:
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/nn/loss.py#L35
原因：
https://github.com/PaddlePaddle/Paddle/pull/49989/files 加了检查，但未更新示例代码

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

修复示例代码报错问题

**Comment by luotao1** [comment]
辛苦 @RedContritio 修复一下

**Comment by RedContritio** [comment]
已修复 [Paddle/pull/53588](https://github.com/PaddlePaddle/Paddle/pull/53588)
