### ISSUE TITLE
paddle2.4中 paddle.Tensor.nanmean paddle.frexp  API中文文档缺失

### ISSUE THREAD

**Issue by Hzwords** [PaddlePaddle/docs#5883]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html
paddle2.4中 paddle.Tensor.nanmean paddle.frexp  API中文文档缺失

**Comment by luotao1** [comment]
develop分支上是有的：
- nanmean: https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nanmean_cn.html
- frexp: https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/frexp_cn.html
