### ISSUE TITLE
paddle.Tensor.bsubtract 文档缺少

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/docs#5901]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/docs/issues/5691 文档映射任务中 paddle.Tensor.bsubtract 文档缺少
![图片](https://github.com/PaddlePaddle/docs/assets/4617245/58d3399c-fe50-46f2-bb46-ff6887a51cd0)

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/Tensor_cn.html
![图片](https://github.com/PaddlePaddle/docs/assets/4617245/4b44cdcb-d047-4acc-bba4-431c3c2b4e73)

**Comment by luotao1** [comment]
请 @zhwesky2010 @Tomoko-hjf 帮忙看下任务描述表格里是不是笔误了？bsubtract 应该是 subtract?

**Comment by zhwesky2010** [comment]
是的，表格中映射关系仅供初步参考，发现问题直接在最终的md映射文档中修改即可。以最终提交的PR审核为准
