### ISSUE TITLE
官网英文文档入口有问题 & 部分英文文档缺失

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/docs#6155]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/linalg/inv_cn.html 

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

无法通过 中|英 的按钮一键跳转到对应的英文文档，在英文界面搜索后默认展示2.2版本，并且英文无inv文档

**Comment by Liyulingyue** [comment]
相关 ISSUE https://github.com/PaddlePaddle/docs/issues/6063

**Comment by sunzhongkai588** [comment]
> 无法通过 中|英 的按钮一键跳转到对应的英文文档，在英文界面搜索后默认展示2.2版本，并且英文无inv文档

可以跳转呀，而且也是develop版本
![image](https://github.com/PaddlePaddle/docs/assets/70642955/3fc0d7ff-492b-48e0-848c-0111aead9cce)
