### ISSUE TITLE
【Docathon】补充缺失的中文 API 文档

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/docs#6193]
## 背景
飞桨官网的 API 文档，有中文和英文两个版本，都存储于 GitHub 中，并通过技术手段转为 HTML 文件后呈现在官网。
* `中文 API 文档`存储于 docs 仓库下，具体路径为 [PaddlePaddle/docs/docs/api/paddle](https://github.com/PaddlePaddle/docs/tree/develop/docs/api/paddle)。 
* `英文 API 文档`存储于 Paddle 仓库下的对应的 API 源码中，具体路径为 [PaddlePaddle/Paddle/python/paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle)。

以 `paddle.add` 为例，在 develop 分支下
* 中文文档 URL： https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/add_cn.html，api/paddle/add_cn.html即对应 (docs/docs/)api/paddle/add_cn.rst
* 英文文档 URL：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/add_en.html， 进入文档页面中点击 [source] 即可跳转至 add 源代码中。

原则上官网 API 文档必须提供中文和英文两个版本，但目前许多 API 文档只提供了英文版本，而缺失了中文版本，导致这些API不容易被开发者发现和有效利用。为了解决这个问题，我们号召大家一起努力来补充这些 API 的中文文档。

任务结束后，完成该任务的开发者将会在官网中进行展示哦🎉

## 任务描述：
我们提供了部分缺失中文文档的 API 清单，如下所示。请根据提供的 API 的英文文档，来补充相应的中文文档。补充完后请 request 对应的 API 负责人（Paddle 内部研发） review. 

| 序号 | 英文 API | 对应 API 负责人 | 认领人/状态/PR  |
| ---- | ---------------- | ---------------- | ------------- | 
| 1 | [paddle.sin\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sin__en.html) | @caizejun |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6384](https://github.com/PaddlePaddle/docs/pull/6384) [#6383](https://github.com/PaddlePaddle/docs/pull/6383)<br> | 
| 2 | [paddle.sinh\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sinh__en.html) | @caizejun |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6475](https://github.com/PaddlePaddle/docs/pull/6475) [#6477](https://github.com/PaddlePaddle/docs/pull/6477)<br> | 
| 3 | [paddle.incubate.nn.functional.fused_linear](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_linear_en.html) | @sneaxiy |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6479](https://github.com/PaddlePaddle/docs/pull/6479)<br> | 
| 4 | [paddle.incubate.nn.functional.fused_matmul_bias](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_matmul_bias_en.html) | @sneaxiy |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6362](https://github.com/PaddlePaddle/docs/pull/6362)<br> | 
| 5 | [paddle.incubate.nn.FusedLinear](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/FusedLinear_en.html) | @sneaxiy |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6362](https://github.com/PaddlePaddle/docs/pull/6362)<br> | 
| 6 | [paddle.acos\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/acos__en.html) | @wuyefeilin |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6361](https://github.com/PaddlePaddle/docs/pull/6361)<br> | 
| 7 | [paddle.atan\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/atan__en.html) | @wuyefeilin |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6361](https://github.com/PaddlePaddle/docs/pull/6361)<br> | 
| 8 | [paddle.cos\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/cos__en.html) | @wuyefeilin |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6361](https://github.com/PaddlePaddle/docs/pull/6361)<br> | 
| 9 | [paddle.erf\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/erf__en.html) | @wuyefeilin |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6361](https://github.com/PaddlePaddle/docs/pull/6361)<br> | 
| 10 | [paddle.get_rng_state](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_rng_state_en.html) | @qingshuchen |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6363](https://github.com/PaddlePaddle/docs/pull/6363)<br> | 
| 11 | [paddle.set_rng_state](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/set_rng_state_en.html) | @qingshuchen |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6363](https://github.com/PaddlePaddle/docs/pull/6363)<br> | 
| 12 | [paddle.nn.functional.thresholded*relu*](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/thresholded_relu__en.html) | @csy0225 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6365](https://github.com/PaddlePaddle/docs/pull/6365)<br> | 
| 13 | [paddle.geometric.weighted_sample_neighbors](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/geometric/weighted_sample_neighbors_en.html) | @DesmonDay |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6366](https://github.com/PaddlePaddle/docs/pull/6366)<br> | 
| 14 | [paddle.abs\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/abs__en.html) | @haoyuying |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6367](https://github.com/PaddlePaddle/docs/pull/6367)<br> | 
| 15 | [paddle.version.xpu ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/version/xpu_en.html) | @houj04 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6368](https://github.com/PaddlePaddle/docs/pull/6368)<br> | 
| 16 | [paddle.version.xpu_xccl ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/version/xpu_xccl_en.html) | @houj04 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6368](https://github.com/PaddlePaddle/docs/pull/6368)<br> | 
| 17 | [paddle.incubate.nn.functional.fused_multi_transformer ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_multi_transformer_en.html) | @Courtesy-Xs |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6369](https://github.com/PaddlePaddle/docs/pull/6369)<br> | 
| 18 | [paddle.nn.functional.hardtanh\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/hardtanh__en.html) | @qili93 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6370](https://github.com/PaddlePaddle/docs/pull/6370)<br> | 
| 19 | [paddle.static.nn.static_pylayer](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/static_pylayer_en.html) | @qili93 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6370](https://github.com/PaddlePaddle/docs/pull/6370)<br> | 
| 20 | [paddle.nn.quant.llm_int8_linear](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/quant/llm_int8_linear_en.html) | @zhenyun-li |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6371](https://github.com/PaddlePaddle/docs/pull/6371)<br> | 
| 21 | [paddle.nn.quant.weight_only_linear](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/quant/weight_only_linear_en.html) | @zhenyun-li |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6371](https://github.com/PaddlePaddle/docs/pull/6371)<br> | 
| 22 | [paddle.nn.quant.weight_quantize](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/quant/weight_quantize_en.html) | @zhenyun-li |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6371](https://github.com/PaddlePaddle/docs/pull/6371)<br> | 
| 23 | [paddle.static.ctr_metric_bundle](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/ctr_metric_bundle_en.html) | @danleifeng |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6372](https://github.com/PaddlePaddle/docs/pull/6372)<br> | 
| 24 | [paddle.sparse.nn.functional.conv2d](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sparse/nn/functional/conv2d_en.html) | @Xreki |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6360](https://github.com/PaddlePaddle/docs/pull/6360)<br> | 
| 25 | [paddle.sparse.nn.Conv2D ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sparse/nn/Conv2D_en.html) | @Xreki |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6360](https://github.com/PaddlePaddle/docs/pull/6360)<br> | 
| 26 | [paddle.nn.functional.scaled_dot_product_attention](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/scaled_dot_product_attention_en.html) | @liuzhenhai93 |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6390](https://github.com/PaddlePaddle/docs/pull/6390) [#6484](https://github.com/PaddlePaddle/docs/pull/6484)<br> | 
| 27 | [paddle.utils.try_import ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/utils/try_import_en.html) | @kangguangli |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6385](https://github.com/PaddlePaddle/docs/pull/6385) [#6387](https://github.com/PaddlePaddle/docs/pull/6387)<br>@Kaedeharai <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 28 | [paddle.amp.debugging.check_layer_numerics](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/amp/debugging/check_layer_numerics_en.html) | @zhangting2020 |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6382](https://github.com/PaddlePaddle/docs/pull/6382)<br>@Kaedeharai <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 29 | [paddle.incubate.nn.functional.fused_linear_activation](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_linear_activation_en.html) | @zhangting2020 |  @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6382](https://github.com/PaddlePaddle/docs/pull/6382)<br>@Kaedeharai <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 30 | [paddle.incubate.nn.functional.fused_rotary_position_embedding](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_rotary_position_embedding_en.html) | @zhangting2020 |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6447](https://github.com/PaddlePaddle/docs/pull/6447)<br> | 
| 31 | [paddle.sparse.nn.functional.subm_conv2d ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sparse/nn/functional/subm_conv2d_en.html) | @zhangting2020 |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6447](https://github.com/PaddlePaddle/docs/pull/6447)<br> | 
| 32 | [paddle.sparse.nn.SubmConv2D ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/sparse/nn/SubmConv2D_en.html) | @zhangting2020 |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6430](https://github.com/PaddlePaddle/docs/pull/6430)<br> | 
| 33 | [paddle.incubate.nn.functional.fused_dropout_add ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_dropout_add_en.html) | @ForFishes |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6431](https://github.com/PaddlePaddle/docs/pull/6431)<br> | 
| 34 | [paddle.incubate.nn.FusedDropoutAdd ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/FusedDropoutAdd_en.html) | @ForFishes |  @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6431](https://github.com/PaddlePaddle/docs/pull/6431)<br> | 
| 35 | [paddle.incubate.distributed.utils.io.dist_save.save ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_en.html) | @SylarTiaNII |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6442](https://github.com/PaddlePaddle/docs/pull/6442)<br> | 
| 36 | [paddle.incubate.distributed.utils.io.dist_save.save_for_auto_inference](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_en.html) | @SylarTiaNII |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6442](https://github.com/PaddlePaddle/docs/pull/6442)<br> | 
| 37 | [paddle.incubate.distributed.utils.io.save_for_auto.save_for_auto_inference](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_en.html) | @SylarTiaNII |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6442](https://github.com/PaddlePaddle/docs/pull/6442)<br> | 
| 38 | ~~[paddle.profiler.SummaryView ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/profiler/SummaryView_en.html)~~ | @tianhaodongbd |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6446](https://github.com/PaddlePaddle/docs/pull/6446)<br> | 
| 39 | [paddle.callbacks.WandbCallback](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/callbacks/WandbCallback_en.html) |  |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6446](https://github.com/PaddlePaddle/docs/pull/6446)<br> | 
| 40 | [paddle.incubate.nn.functional.variable_length_memory_efficient_attention](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/variable_length_memory_efficient_attention_en.html) |  |  @Kaedeharai <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6446](https://github.com/PaddlePaddle/docs/pull/6446)<br> | 
| 41 | [paddle.expm1\_](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/expm1__en.html) | @ronny1996 |  @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6373](https://github.com/PaddlePaddle/docs/pull/6373)<br> | 
| 42 | ~~[paddle.nn.quant.Stub](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/quant/Stub_en.html)~~ | @wanghaoshuang |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6452](https://github.com/PaddlePaddle/docs/pull/6452)<br> | 
| 43 | ~~[paddle.quantization.BaseObserver](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/BaseObserver_en.html)~~ | @wanghaoshuang |  @Turingg <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6485](https://github.com/PaddlePaddle/docs/pull/6485)<br> | 
| 44 | ~~[paddle.quantization.BaseQuanter](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/BaseQuanter_en.html)~~ | @wanghaoshuang |  @Turingg <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 45 | ~~[paddle.quantization.QuantConfig](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/QuantConfig_en.html)~~ | @wanghaoshuang |  @Turingg <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 46 | ~~[paddle.quantization.quanter](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/quanter_en.html)~~ | @wanghaoshuang |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6453](https://github.com/PaddlePaddle/docs/pull/6453)<br> | 
| 47 | ~~[paddle.quantization.PTQ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/PTQ_en.html)~~ | @wanghaoshuang |  @entired <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@jiangziyan-693 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6421](https://github.com/PaddlePaddle/docs/pull/6421) [#6481](https://github.com/PaddlePaddle/docs/pull/6481) [#6482](https://github.com/PaddlePaddle/docs/pull/6482)<br> | 
| 48 | ~~[paddle.quantization.QAT](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/quantization/QAT_en.html)~~ | @wanghaoshuang |  @entired <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@jiangziyan-693 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6410](https://github.com/PaddlePaddle/docs/pull/6410) [#6482](https://github.com/PaddlePaddle/docs/pull/6482)<br> | 
| 49 | ~~[paddle.jit.enable_to_static](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/jit/enable_to_static_en.html)~~ | @0x45f |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6374](https://github.com/PaddlePaddle/docs/pull/6374)<br> | 
| 50 | [paddle.incubate.distributed.fleet.recompute_hybrid](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/fleet/recompute_hybrid_en.html) | @wuhuachaocoding |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6375](https://github.com/PaddlePaddle/docs/pull/6375)<br> | 
| 51 | [paddle.incubate.distributed.fleet.recompute_sequential](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/fleet/recompute_sequential_en.html) | @wuhuachaocoding |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6375](https://github.com/PaddlePaddle/docs/pull/6375)<br> | 
| 52 | [paddle.square\_ ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/square__en.html) | @yangjianfengo1 |  @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6378](https://github.com/PaddlePaddle/docs/pull/6378)<br> | 
| 53 | [paddle.incubate.nn.FusedMultiTransformer](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/FusedMultiTransformer_en.html) | @iosmers |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6451](https://github.com/PaddlePaddle/docs/pull/6451)<br> | 
| 54 | ~~[paddle.device.xpu.synchronize](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/xpu/synchronize_en.html)~~ | @XiaociZhang |  @entired <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6377](https://github.com/PaddlePaddle/docs/pull/6377)<br> | 
| 55 | [paddle.incubate.xpu.resnet_block.resnet_basic_block](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/xpu/resnet_block/resnet_basic_block_en.html) | @zhangyk0314 |  @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6376](https://github.com/PaddlePaddle/docs/pull/6376)<br> |  | 
| 56 | [paddle.incubate.nn.functional.fused_bias_dropout_residual_layer_norm ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_bias_dropout_residual_layer_norm_en.html) | @Vvsmile |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6358](https://github.com/PaddlePaddle/docs/pull/6358)<br> | 
| 57 | [paddle.incubate.nn.FusedBiasDropoutResidualLayerNorm ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/FusedBiasDropoutResidualLayerNorm_en.html) | @Vvsmile |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6358](https://github.com/PaddlePaddle/docs/pull/6358)<br> | 
| 58 | [paddle.incubate.nn.functional.masked_multihead_attention ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/masked_multihead_attention_en.html) | @xiaoxiaohehe001 | @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6356](https://github.com/PaddlePaddle/docs/pull/6356)<br> | 
| 59 | [paddle.nn.functional.leaky*relu* ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/leaky_relu__en.html) | @xiaoxiaohehe001 |  @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6356](https://github.com/PaddlePaddle/docs/pull/6356)<br> | 
| 60 | [paddle.incubate.nn.functional.fused_layer_norm ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_layer_norm_en.html) | @MARD1NO  | @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6211](https://github.com/PaddlePaddle/docs/pull/6211)<br> | 
| 61 | [paddle.incubate.nn.functional.fused_rms_norm ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/nn/functional/fused_rms_norm_en.html) | @MARD1NO  | @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6211](https://github.com/PaddlePaddle/docs/pull/6211)<br> | 
| 62 | ~~[paddle.incubate.asp.decorate ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/decorate_en.html)~~ | @mingxu1067  |  | 
| 63 | ~~[paddle.incubate.asp.prune_model ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/prune_model_en.html)~~ | @mingxu1067  |  | 
| 64 | [paddle.incubate.asp.reset_excluded_layers ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/reset_excluded_layers_en.html) | @mingxu1067  | @ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6224](https://github.com/PaddlePaddle/docs/pull/6224)<br> | 
| 65 | [paddle.incubate.asp.set_excluded_layers ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/set_excluded_layers_en.html) | @mingxu1067  | @ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6224](https://github.com/PaddlePaddle/docs/pull/6224)<br> | 
| 66 | [paddle.incubate.asp.add_supported_layer ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/add_supported_layer_en.html) | @mingxu1067  | @ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6224](https://github.com/PaddlePaddle/docs/pull/6224)<br> | 
| 67 | [paddle.incubate.asp.calculate_density ](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/asp/calculate_density_en.html) | @mingxu1067  | @ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6224](https://github.com/PaddlePaddle/docs/pull/6224)<br> | 

>  ⚠️注意：补充文档时，还需要注意下是否需要在相应的 `overview.rst` 等综述页面增加相关 API 描述

## 任务认领
> [!NOTE]
> **1. Issue 回复格式**：
>为了自动填写报名信息，需要在 issue 下回复报名信息，如果报名格式不正确，则会在 comment 区提示报名不正确，格式如下：
> ```
> 【报名】: 2、3、6-10
> ```
> > 其中【报名】:  后直接是报名的赛题序号，多个赛题之间需要用中文顿号`、`分隔，多个连续赛题可以用`横线`表示

> [!NOTE] 
> **2. PR 标题格式**：
> ```
> [Docathon][Add CN Doc No.2、3、6-10]
> ```
> PR的标题中以 ` [Docathon][Add CN Doc No.xxxx]` 开头即可，程序会自动提取赛题编号并更新榜单。
> 一个 PR 也可以提交多个赛题，多个赛题间以`顿号`或`横线`分隔，比如 No.24、26-28、30 赛题。

> [!NOTE] 
> **3. PR 内容**：
>  描述新增了什么文档、附上该 issue 链接、 附上英文文档链接、并  @sunzhongkai588 和表中的 API 负责人review

## 参考资料：

[文档贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/docs_contributing_guides_cn.html)

[API 文档书写规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_docs_guidelines_cn.html)

[Python 文档示例代码书写规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/style_guide_and_references/code_example_writing_specification_cn.html)
## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
| Docathon | 67 | 63 / 65 | 94.03% | 47 | 70.15% |
#####

## 统计信息 
> 排名不分先后 @Turingg (6) @zade23 (28) @Kaedeharai (6) @entired (3) @ooooo-create (4) 
#####

**Comment by ooooo-create** [comment]
【报名】: 64-67

**Comment by zade23** [comment]
【报名】: 4-25、56-61

**Comment by Turingg** [comment]
【报名】: 1，27-29

**Comment by Kaedeharai** [comment]
【报名】: 26-40

**Comment by entired** [comment]
【报名】：46-54

**Comment by entired** [comment]
【报名】：55

**Comment by jiangziyan-693** [comment]
【报名】: 47、48

**Comment by jiangziyan-693** [comment]
[Docathon][Add CN Doc No.48]https://github.com/PaddlePaddle/docs/pull/6410

**Comment by Turingg** [comment]
【报名】: 2、3、43-45

**Comment by luotao1** [comment]
[【Docathon】补充缺失的中文 API 文档](https://github.com/PaddlePaddle/docs/issues/6193#top) 已基本完成，感谢参与的小伙伴们！

> 排名不分先后 @Turingg (6) @zade23 (28) @Kaedeharai (6) @entired (3) @ooooo-create (4)

备注: incubate的可能未来会有变动，量化相关的研发自行补充，paddle.callbacks.WandbCallback 是印度开发者提交的，暂时没找到 reviewer 。可以在后续活动完成。
