### ISSUE TITLE
【社区治理】ooooo-create 发起 Committer 身份申请

### ISSUE THREAD

**Issue by ooooo-create** [PaddlePaddle/docs#6278]
## 基本信息
| **申请人 GitHub ID** | **docs Repo 整体 merge PR 数** | **docs Repo 整体 review PR 数** | **docs Repo 整体报告 Issue 数** |
| --- | --- | --- | --- |
| ooooo-create | 38 | 0 | 2 |

## 社区贡献概况
以下是此前在本 repo 里做过的贡献：
- 新增部分缺失的中文 API 文档
- 在孙师傅和一师傅的帮助下，添加和修复中文 `api_label` 的规范，和 CI 监测
- 在一师傅的帮助下，把 paddle repo 下的 codestyle 迁移到 docs repo

至于理由嘛，自然是帮助孙师傅和一师傅先 review 一下

## 高质量 merged PR 展示
主要靠一师傅和孙师傅的 review～
| **PR 号** | **PR 标题** | **PR 简介** | **Reviewer** |
| --- | --- | --- | --- |
| #6266 , #6237 , #6246   | [ci] 添加监测中文 apilabel 的 ci  | ci 监测 | @SigureMo |
| #6224  , #6222 | [Docathon] Add NO.64-67 API CN Doc | 新增文档 | @sunzhongkai588 |
| #6171 , #6220, #6221 | [Docathon] fix_cn_api_label | 修复 api_label | @sunzhongkai588 @SigureMo |
| #6238 , #6244 ,  #6253  , #6274 | [Docathon][CodeStyle Fix] update | codestyle | @SigureMo |

## 高质量 review PR 展示
review 过英文 api_label 的问题，在 paddle repo ([9个](https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Apr+reviewed-by%3Aooooo-create+-author%3Aooooo-create)）
| **PR 号** | **PR 标题** | **PR 简介** | **review 详情** |
| --- | --- | --- | --- |

## 代表性 Issue 展示
都是 tasking issue～
| **Issue 号** | **Issue 标题** | **Issue 简介** | **解决情况** |
| --- | --- | --- | --- |
| #6170 | 【Docathon】 中文 api 文档中的 api_label 规范 |  中文 api 文档中的 api_label 规范 |  已完成，待close |
| #6242 | [Docathon]docs 代码风格检查工具对齐 Paddle | 如题 | close by #6274 |

担保人意见
@sunzhongkai588 @SigureMo

**Comment by SigureMo** [comment]
同意～

@ooooo-create 在 Paddle 出色地完成了 xdoctest 引入等相关任务，并在之后独立拆分完成了「中英文 API label 规范化」、「docs 代码风格优化」等任务，为 docs 做出了很多突出的贡献～

o 师傅之后可以尝试挑战一些 Paddle repo 的较难任务了，期待申请 Paddle committer 的那天～

**Comment by sunzhongkai588** [comment]
200% 同意✨

@ooooo-create 已经能具备对docs问题的发掘、拆解、发布、review等能力，为 docs 规范做出了突出贡献～同时开源热情也很高，是一个有能力、有意愿的优秀社区开发者～

后续一方面可以如 001 所说，尝试更难的题，如 paddle repo 下的任务；另一方面也可以尝试更高维度的想一些文档优化的事情，比如顺师傅之前做的增加 xdoctest 检查，可以参考比如 pytorch 的文档建设～

**Comment by jzhang533** [comment]
+1
已经发送开通docs仓库下write权限的邀请，请查收。
再次感谢。
