### ISSUE TITLE
[Docathon] 中文文档 copy-from 清理

### ISSUE THREAD

**Issue by ooooo-create** [PaddlePaddle/docs#6300]
## 背景
为了使中、英文 API 文档的示例代码保持一致，飞桨中文 API 文档使用 `COPY-FROM` 来直接引用英文的 API 示例代码。
但是，目前中文 API 文档中还存在一些 `COPY-FROM` 不成功的情况，表现形式为**无法显示代码示例**，例如 [Conll05st](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Conll05st_cn.html#daimashili)
![image](https://github.com/PaddlePaddle/docs/assets/106524776/20fe5fa8-29e0-4b6e-867b-4a89fe9e2414)

## 原因分析
一般无法正确显示代码示例，会分为 2 种情况：中文文档的 COPY-FROM 引用方式写法存在错误，或者是被引用的英文文档的示例代码写法存在错误。

### 1. COPY-FROM 后面的 `API 名称或路径`不正确。
以 [Conll05st](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Conll05st_cn.html#daimashili) 为例，COPY-FROM 后面的路径为 `paddle.text.datasets.Conll05st`，但实际的 API 路径为 `paddle.text.Conll05st`（可以直接看官网左侧 API 的目录来确定路径）

> [!IMPORTANT] 
> 正确的引用方式可以参考：[中文API文档复制英文API文档示例代码](https://github.com/PaddlePaddle/docs/wiki/%E4%B8%AD%E6%96%87API%E6%96%87%E6%A1%A3%E5%A4%8D%E5%88%B6%E8%8B%B1%E6%96%87API%E6%96%87%E6%A1%A3%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81)。
> 需要注意的是其中 `api_name` 为该 API 的 `公开路径`，英文官网 api 文档中展示的就是所有公开的 API。

### 2. 被 COPY-FROM 的 API 没有规范的书写格式
典型场景为英文文档的示例代码缺少空行，如
  - `:name: code_id` 标识符之后没有空行，以 [distributed.Fleet](https://github.com/PaddlePaddle/Paddle/blob/a013d6898f30ba8efef494623f53b9b05fa7d59e/python/paddle/distributed/fleet/fleet.py#L225-L230) 为例。
 
![image](https://github.com/PaddlePaddle/docs/assets/106524776/610e1db9-d236-4e31-82e7-fb5458e9d10d)

  - `.. code-block:: python` 之后没有空行 （在不需要 name: code_id 标识符时）
  https://github.com/PaddlePaddle/docs/blob/f311fe432d112dddf2ba60f973c3751a29ce5678/docs/api/paddle/distributed/fleet/Fleet_cn.rst?plain=1#L683-L688

## 任务描述
| **序号** | **中文文档链接** | **认领人/状态/PR**|
| --- | --- | --- |
| 1 | [Event_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/Event_cn.html) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6308](https://github.com/PaddlePaddle/docs/pull/6308) [#6326](https://github.com/PaddlePaddle/docs/pull/6326) [#6381](https://github.com/PaddlePaddle/docs/pull/6381)<br> | 
| 2 | [Conll05st_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Conll05st_cn.html) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6308](https://github.com/PaddlePaddle/docs/pull/6308) [#6326](https://github.com/PaddlePaddle/docs/pull/6326) [#6381](https://github.com/PaddlePaddle/docs/pull/6381)<br> @Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6304](https://github.com/PaddlePaddle/docs/pull/6304)<br> | 
| 3 | [Stream_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/Stream_cn.html) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6308](https://github.com/PaddlePaddle/docs/pull/6308) [#6326](https://github.com/PaddlePaddle/docs/pull/6326) [#6381](https://github.com/PaddlePaddle/docs/pull/6381)<br> | 
| 4 | [Imikolov_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Imikolov_cn.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6309](https://github.com/PaddlePaddle/docs/pull/6309)<br> | 
| 5 | [Imdb_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Imdb_cn.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6309](https://github.com/PaddlePaddle/docs/pull/6309)<br> | 
| 6 | [UCIHousing_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/UCIHousing_cn.html) | @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6311](https://github.com/PaddlePaddle/docs/pull/6311)<br> | 
| 7 | [InMemoryDataset_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/InMemoryDataset_cn.html) | @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6311](https://github.com/PaddlePaddle/docs/pull/6311)<br> | 
| 8 | [WMT16_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/WMT16_cn.html) | @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6311](https://github.com/PaddlePaddle/docs/pull/6311)<br> | 
| 9 | [Movielens_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/Movielens_cn.html) | @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6311](https://github.com/PaddlePaddle/docs/pull/6311)<br> | 
| 10 | [WMT14_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/text/WMT14_cn.html) | @Kaedeharai <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6311](https://github.com/PaddlePaddle/docs/pull/6311)<br> | 
| 11 | [**Fleet_cn**](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/fleet/Fleet_cn.html) | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6310](https://github.com/PaddlePaddle/docs/pull/6310) [#6349](https://github.com/PaddlePaddle/docs/pull/6349)<br> | 
| 12 | [Adadelta_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Adadelta_cn.html) | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6310](https://github.com/PaddlePaddle/docs/pull/6310) [#6349](https://github.com/PaddlePaddle/docs/pull/6349)<br> | 
| 13 | [AdamW_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/AdamW_cn.html) | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6310](https://github.com/PaddlePaddle/docs/pull/6310) [#6349](https://github.com/PaddlePaddle/docs/pull/6349)<br> | 
| 14 | [Adam_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Adam_cn.html#) | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6310](https://github.com/PaddlePaddle/docs/pull/6310) [#6349](https://github.com/PaddlePaddle/docs/pull/6349)<br> | 
| 15 | [Adamax_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Adamax_cn.html) | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6310](https://github.com/PaddlePaddle/docs/pull/6310) [#6349](https://github.com/PaddlePaddle/docs/pull/6349)<br> | 
| 16 | [Lamb_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Lamb_cn.html#lamb) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6327](https://github.com/PaddlePaddle/docs/pull/6327) [#6379](https://github.com/PaddlePaddle/docs/pull/6379)<br> | 
| 17 | [Optimizer_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/Optimizer_cn.html#optimizer) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6327](https://github.com/PaddlePaddle/docs/pull/6327) [#6379](https://github.com/PaddlePaddle/docs/pull/6379)<br> | 
| 18 | [RMSProp_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/RMSProp_cn.html#rmsprop) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6327](https://github.com/PaddlePaddle/docs/pull/6327) [#6379](https://github.com/PaddlePaddle/docs/pull/6379)<br> | 
| 19 | [**DistributedStrategy_cn**](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/fleet/DistributedStrategy_cn.html) | @entired <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6327](https://github.com/PaddlePaddle/docs/pull/6327) [#6379](https://github.com/PaddlePaddle/docs/pull/6379)<br> | 

## 任务认领
> [!NOTE]
> **1. Issue 回复格式**：
>为了自动填写报名信息，需要在issue下回复报名信息，如果报名格式不正确，则会在comment区提示报名不正确，格式如下：
> ```
> 【报名】: 2、3、6-10
> ```
> > 其中【报名】:  后直接是报名的赛题序号，多个赛题之间需要用中文顿号`、`分隔，多个连续赛题可以用`横线`表示

> [!NOTE] 
> **2. PR 标题格式**：
> ```
> [Docathon][Fix COPY-FROM No.2、3、6-10]
> ```
> PR的标题中以 ` [Docathon][Fix COPY-FROM No.xxxx]` 开头即可，程序会自动提取赛题编号并更新榜单。
> 一个PR也可以提交多个赛题，多个赛题间以`顿号`或`横线`分隔，比如 No.24、26-28、30 赛题。

> [!NOTE] 
> **3. PR 内容**：
> 需要描述修改的文件、附上活动 issue 链接、 并 @ooooo-create @sunzhongkai588
## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
| Docathon | 19 | 19 / 19 | 100.0% | 19 | 100.0% |
#####

## 统计信息 
> 排名不分先后 @entired (7) @Sekiro-x (2) @Kaedeharai (5) @Turingg (5) 
#####

**Comment by Turingg** [comment]
认领13，15

**Comment by Turingg** [comment]
【报名】: 13、15

**Comment by entired** [comment]
【报名】: 1、2、3

**Comment by Kaedeharai** [comment]
【报名】: 6-10

**Comment by Turingg** [comment]
【报名】: 11-15

**Comment by Sekiro-x** [comment]
【报名】: 4、5

**Comment by entired** [comment]
【报名】: 16-19

**Comment by luotao1** [comment]
[[Docathon] 中文文档 copy-from 清理](https://github.com/PaddlePaddle/docs/issues/6300#top) 已全部完成，感谢参与的小伙伴们！

> 排名不分先后 @entired (7) @Sekiro-x (2) @Kaedeharai (5) @Turingg (5)
