### ISSUE TITLE
官网文档跳转链接失效

### ISSUE THREAD

**Issue by RedContritio** [PaddlePaddle/docs#6402]
### 文档链接&描述 Document Links & Description

来自 [开始使用](https://www.paddlepaddle.org.cn/install/compile/linux-compile.html) 页面中源码安装部分，这里跳转后的预期页面应当为 

- [Linux 下使用 make 从源码编译 `develop/install/compile/linux-compile-by-make.html`](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile-by-make.html)

但实际跳转至 `https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile.html#anchor-0`，由于链接缺失，导致跳转至 [主页](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/index_cn.html#anchor-0)。

至此，跳转链接失效。

@sunzhongkai588 

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

这个**开始使用**页面貌似不是在 docs 中维护的，可能需要对这个页面进行更新维护？

**Comment by sunzhongkai588** [comment]
感谢反馈～会在内部的官网 cms 平台进行修复

**Comment by sunzhongkai588** [comment]
已修复
