### ISSUE TITLE
【Docathon】补充Overview文档相关API描述

### ISSUE THREAD

**Issue by Turingg** [PaddlePaddle/docs#6427]
## 一、背景

飞桨官网的 API 文档，有中文和英文两个版本，都存储于 GitHub 中，并通过技术手段转为 HTML 文件后呈现在官网。

- 中文 API 文档存储于 docs 仓库下，具体路径为 PaddlePaddle/docs/docs/api/paddle。
- 英文 API 文档存储于 Paddle 仓库下的对应的 API 源码中，具体路径为 PaddlePaddle/Paddle/python/paddle。

原则上每一个中文 API 文档，都需要在对应目录下的 **Overview** 页面有描述，并且是一一对应的关系，但目前部分 Overview 文档中的 API 描述存在缺失。

> [!NOTE]
> 以 [paddle.amp.debugging.collect_operator_stats](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/debugging/collect_operator_stats_cn.html) 为例，该 API **理应**在 paddle.amp 文件夹下的 Overview 页面中的 [Debug 相关辅助类](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/Overview_cn.html#debug)有对应描述，但实际是缺失的。
> ![image](https://github.com/PaddlePaddle/docs/assets/70642955/da34d460-36be-4950-9c44-97a982249934)
> 因此，你需要在对应 amp 文件夹下的 [Overview_cn.rst](https://github.com/PaddlePaddle/docs/blob/develop/docs/api/paddle/amp/Overview_cn.rst#debug-相关辅助类) 文件中增加对应描述。

## 二、原因分析

中文文档中 Overview 是通过 `:ref:` 的格式进行映射的。一般会造成其描述缺失的就是其 Overview_cn.rst 缺乏相应的" `:ref:` 引用。

以 **paddle.amp.debugging.DebugMod** 为例，`:ref:` 引用写法如下：
https://github.com/PaddlePaddle/docs/blob/962078482ad8c2bc9dfa2f5b9e2787bcec1851a3/docs/api/paddle/amp/Overview_cn.rst?plain=1#L75

## 三、解决方法

通过在相应位置添加 ```" :ref:`API<相关 API 路径>` "``` 补充 Overview 文档中缺失的 API 描述、以 paddle.add 为例：

- 首先通过路径找到相应的 Overview 文档的 rst 文件，如下图
  ![J@I (YX$SAQ7%{TN$L0LXE7](https://github.com/PaddlePaddle/docs/assets/117662096/73137b15-df1a-4e3f-8efc-567b032306c8)
  ![3J @WZ$H9WK9R0V6P24UE 8](https://github.com/PaddlePaddle/docs/assets/117662096/b2003873-0ae9-4c25-89d1-e34a08f0a582)
- 其次相关文档补齐，paddle.add 的功能是与 tensor 数学操作有关，则找到相应的位置如下
  ![FH$}%W)LH 0 V}}M9J1MWZ2](https://github.com/PaddlePaddle/docs/assets/117662096/c2ee43ca-e840-47bd-b066-cf68704900ba)
  按照 ```" :ref:`API<相关 API 路径>` "，"API 功能"``` 添加描述

## 四、任务描述

| 序号 |                         中文文档链接                         | 缺失数量 | **认领人/状态/PR** |
| :--: | :----------------------------------------------------------: | :------: | :----------------: |
| 1 | [paddle.amp.debugging.collect_operator_stats](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/debugging/collect_operator_stats_cn.html)、[paddle.amp.debugging.check_numerics](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/debugging/check_numerics_cn.html )、[paddle.amp.debugging.check_layer_numerics](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/debugging/check_layer_numerics_cn.html) | 3个 | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6523](https://github.com/PaddlePaddle/docs/pull/6523)<br> | 
| 2 | [paddle.amp.is_float16_supported](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/is_float16_supported_cn.html)、[paddle.amp.is_bfloat16_supported](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/amp/is_bfloat16_supported_cn.html) | 2个 | @Turingg <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6571](https://github.com/PaddlePaddle/docs/pull/6571)<br> | 
| 3 | [paddle.autograd.backward](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/backward_cn.html)、[paddle.autograd.jacobian](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/jacobian_cn.html)、[paddle.autograd.hessian](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/hessian_cn.html)、[paddle.autograd.saved_tensors_hooks](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/saved_tensors_hooks_cn.html) | 4个 | @Turingg <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 
| 4 | [paddle.autograd.PyLayerContext](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/PyLayerContext_cn.html)、[paddle.autograd.PyLayer](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/PyLayer_cn.html) | 2个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 
| 5 | [paddle.device.set_device](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/set_device_cn.html)、[paddle.device.get_device](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_device_cn.html) | 2个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 6 | [paddle.device.is_compiled_with_xpu](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_xpu_cn.html)、[paddle.device.is_compiled_with_rocm](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_rocm_cn.html)、[paddle.device.is_compiled_with_cinn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_cinn_cn.html)、[paddle.device.is_compiled_with_ipu](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_ipu_cn.html)、[paddle.device.is_compiled_with_custom_device](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/is_compiled_with_custom_device_cn.html) | 5个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 7 | [paddle.device.get_device_name](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/get_device_name_cn.html)、[paddle.device.get_device_properties](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/get_device_properties_cn.html)、[paddle.device.get_device_capability](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/get_device_capability_cn.html)、[paddle.device.get_device_capability](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/get_device_capability_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 8 | [paddle.device.get_cudnn_version](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_cudnn_version_cn.html) | 1个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 9 | [paddle.device.XPUPlace](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/XPUPlace_cn.html)、[paddle.device.Stream](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/Stream_cn.html)、[paddle.device.Event](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/Event_cn.html)、[paddle.device.synchronize](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/synchronize_cn.html)、[paddle.device.device_count](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/device_count_cn.html) | 5个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 10 | [paddle.device.Stream](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/Stream_cn.html)、[paddle.device.current_stream](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/current_stream_cn.html)、[paddle.device.stream_guard](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/stream_guard_cn.html)、[paddle.device.set_stream](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/set_stream_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 11 | [paddle.device.empty_cache](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/empty_cache_cn.html)、[paddle.device.IPUPlace](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/IPUPlace_cn.html)、[paddle.device.synchronize](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/synchronize_cn.html)、[paddle.device.Event](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/Event_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 12 | [paddle.device.get_available_device](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_available_device_cn.html)、[paddle.device.get_all_custom_device_type](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_all_custom_device_type_cn.html)、[paddle.device.get_available_custom_device](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_available_custom_device_cn.html)、[paddle.device.get_all_device_type](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/get_all_device_type_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 13 | [paddle.device.memory_allocated](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/memory_allocated_cn.html)、[paddle.device.max_memory_reserved](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/max_memory_reserved_cn.html)、[paddle.device.memory_reserved](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/memory_reserved_cn.html)、[paddle.device.max_memory_allocated](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/cuda/max_memory_allocated_cn.html) | 4个 | @LouisCanBe <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6620](https://github.com/PaddlePaddle/docs/pull/6620)<br> | 
| 14 | [paddle.distributed.ParallelEnv](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/ParallelEnv_cn.html)、[paddle.distributed.split](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/split_cn.html)、[paddle.distributed.wait](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/wait_cn.html)、[paddle.distributed.recompute](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/fleet/utils/recompute_cn.html) | 4个 | @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6599](https://github.com/PaddlePaddle/docs/pull/6599)<br> | 
| 15 | [paddle.distributed.get_group](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/get_group_cn.html)、[paddle.distributed.group_sharded_parallel](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/sharding/group_sharded_parallel_cn.html)、[paddle.distributed.save_group_sharded_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/sharding/save_group_sharded_model_cn.html) | 3个 | @StellaZYing <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6595](https://github.com/PaddlePaddle/docs/pull/6595)<br> | 
| 16 | [paddle.distributed.gloo_init_parallel_env](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/gloo_init_parallel_env_cn.html)、[paddle.distributed.gloo_barrier](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/gloo_barrier_cn.html)、[paddle.distributed.gloo_release](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/gloo_release_cn.html) | 3个 | @StellaZYing <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6595](https://github.com/PaddlePaddle/docs/pull/6595)<br> | 
| 17 | [paddle.distributed.is_initialized](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/is_initialized_cn.html)、[paddle.distributed.is_initialized](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/is_initialized_cn.html)、[paddle.distributed.DistAttr](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/DistAttr_cn.html)、[paddle.distributed.dtensor_from_fn_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/dtensor_from_fn_cn.html)、[paddle.distributed.shard_optimizer](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/shard_optimizer_cn.html) | 5个 | @StellaZYing <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6595](https://github.com/PaddlePaddle/docs/pull/6595)<br> | 
| 18 | [paddle.nn.utils.spectral_norm](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/spectral_norm_cn.html)、[paddle.nn.utils.parameters_to_vector](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/parameters_to_vector_cn.html)、[paddle.nn.utils.vector_to_parameters](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/vector_to_parameters_cn.html)、[paddle.nn.utils.clip_grad_norm_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/clip_grad_norm__cn.html)、[paddle.nn.utils.clip_grad_value_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/clip_grad_value__cn.html)、[remove_weight_norm](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/remove_weight_norm_cn.html)、[weight_norm](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/utils/weight_norm_cn.html) | 7个 | @gsq7474741 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6497](https://github.com/PaddlePaddle/docs/pull/6497)<br> | 
| 19 | [paddle.nn.functional.tanh_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tanh__cn.html)、[paddle.nn.functional.sparse_attention](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/sparse_attention_cn.html)、[paddle.nn.functional.hinge_embedding_loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/hinge_embedding_loss_cn.html)、[paddle.nn.functional.channel_shuffle](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/channel_shuffle_cn.html)、[paddle.nn.functional.rnnt_loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/rnnt_loss_cn.html) | 5个 | @gsq7474741 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6504](https://github.com/PaddlePaddle/docs/pull/6504)<br>@Austin-00 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6655](https://github.com/PaddlePaddle/docs/pull/6655)<br> | 
| 20 | [paddle.nn.HingeEmbeddingLoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/HingeEmbeddingLoss_cn.html)、[paddle.nn.RNNTLoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/RNNTLoss_cn.html) | 2个 | @gsq7474741 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6504](https://github.com/PaddlePaddle/docs/pull/6504)<br>@Austin-00 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6655](https://github.com/PaddlePaddle/docs/pull/6655)<br> | 
| 21 | [paddle.nn.initializer.lazy_init.LazyGuard](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/LazyGuard_cn.html) | 1个 | @gsq7474741 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6504](https://github.com/PaddlePaddle/docs/pull/6504)<br>@Austin-00 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6655](https://github.com/PaddlePaddle/docs/pull/6655)<br> | 
| 22 | [paddle.onnx.export](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/onnx/export_cn.html) | 1个 | @dajiang0085 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6585](https://github.com/PaddlePaddle/docs/pull/6585)<br> | 
| 23 | [paddle.optimizer.lr.LinearLR](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/LinearLR_cn.html)、[paddle.optimizer.lr.CosineAnnealingWarmRestarts](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/CosineAnnealingWarmRestarts_cn.html) | 2个 | @dajiang0085 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6585](https://github.com/PaddlePaddle/docs/pull/6585)<br> | 
| 24 | [paddle.regularizer.L1Decay](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/regularizer/L1Decay_cn.html)、[paddle.regularizer.L2Decay](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/regularizer/L2Decay_cn.html) | 2个 | @dajiang0085 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6585](https://github.com/PaddlePaddle/docs/pull/6585)<br> | 
| 25 | [paddle.sparse.sum](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sparse/sum_cn.html) | 1个 | @dajiang0085 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6585](https://github.com/PaddlePaddle/docs/pull/6585)<br> | 
| 26 | [paddle.sysconfig.get_include](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sysconfig/get_include_cn.html)、[paddle.sysconfig.get_lib](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sysconfig/get_lib_cn.htmlhttps://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sysconfig/get_lib_cn.html) | 2个 | @dajiang0085 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6585](https://github.com/PaddlePaddle/docs/pull/6585)<br> | 
| 27 | [paddle.vision.datasets.DatasetFolder](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/datasets/DatasetFolder_cn.html)、[paddle.vision.datasets.ImageFolder](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/datasets/ImageFolder_cn.html) | 2个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 28 | [paddle.vision.ops.read_file](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/read_file_cn.html)、[paddle.vision.ops.decode_jpeg](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/decode_jpeg_cn.html) | 2个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 29 | [paddle.vision.ops.PSRoIPool](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/PSRoIPool_cn.html)、[paddle.vision.ops.RoIPool](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/RoIPool_cn.html)、[paddle.vision.ops.roi_pool](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/roi_pool_cn.html)、[paddle.vision.ops.psroi_pool](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/psroi_pool_cn.html)、 | 4个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 30 | [paddle.vision.ops.roi_align](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/roi_align_cn.html)、[paddle.vision.ops.RoIAlign](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/RoIAlign_cn.html)、[paddle.vision.ops.nms](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/nms_cn.html) | 3个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 31 | [paddle.vision.transforms.RandomPerspective](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/RandomPerspective_cn.html)、[paddle.vision.transforms.RandomErasing](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/RandomErasing_cn.html)、[paddle.vision.transforms.perspective](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/perspective_cn.html)、[paddle.vision.transforms.erase](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/erase_cn.html)、[paddle.vision.transforms.RandomAffine](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/RandomAffine_cn.html)、[paddle.vision.transforms.affine](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/transforms/affine_cn.html) | 6个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 32 | [paddle.vision.ops.generate_proposals](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/generate_proposals_cn.html)、[paddle.vision.ops.distribute_fpn_proposals](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/distribute_fpn_proposals_cn.html)、[paddle.vision.ops.box_coder](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/box_coder_cn.html)、[paddle.vision.ops.prior_box](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/prior_box_cn.html) | 4个 | @Harryoung <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6501](https://github.com/PaddlePaddle/docs/pull/6501)<br> | 
| 33 | [paddle.set_flags](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/set_flags_cn.html)、[paddle.get_flags](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/get_flags_cn.html)、[paddle.fmax](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fmax_cn.html)、[paddle.fmin](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fmin_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 
| 34 | [paddle.fmin](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fmin_cn.html)、[paddle.nansum](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nansum_cn.html)、[paddle.quantile](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/quantile_cn.html)、[paddle.kthvalue](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/kthvalue_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 
| 35 | [paddle.nanmean](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nanmean_cn.html)、[paddle.logspace](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/logspace_cn.html)、[paddle.tril_indices](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tril_indices_cn.html)、[paddle.LazyGuard](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/LazyGuard_cn.html) | 4个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 
| 36 | [paddle.index_add_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/index_add__cn.html)、[paddle.enable_grad](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/enable_grad_cn.html)、[paddle.index_put_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/index_put__cn.html)、[paddle.logaddexp](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/logaddexp_cn.html)、[paddle.diag_embed](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/diag_embed_cn.html) | 5个 | @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6593](https://github.com/PaddlePaddle/docs/pull/6593)<br> | 

## 任务认领

> [!IMPORTANT]
> 请务必严格按照格式填写，否则无法快乐开源小助手无法自动更新信息

**1. Issue 回复格式**：

为了自动填写报名信息，需要在 issue 下回复报名信息，如果报名格式不正确，则会在 comment 区提示报名不正确，格式如下：

```
【报名】: 2、3、6-10
```

> 其中【报名】: 后直接是报名的赛题序号，多个赛题之间需要用中文顿号`、`分隔，多个连续赛题可以用`横线`表示

**2. PR 标题格式**：

```
[Docathon][Add Overview Doc No.2、3、6-10]+相关描述
```

PR 的标题中以 ` [Docathon][Add Overview Doc No.xxxx]` 开头即可，程序会自动提取赛题编号并更新榜单。
一个 PR 也可以提交多个赛题，多个赛题间以`顿号`或`横线`分隔，比如 No.24、26-28、30 赛题。

**3. PR 内容**：

描述新增了哪些 Overview 的 API 描述、附上中文文档链接、并 @Turingg 和 @sunzhongkai588

## 看板信息
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  Docathon  |  36  | 36 / 36 | 100.0% |  31  | 86.11% |
##### 

## 统计信息
> 排名不分先后 @Turingg (2) @hu-qi (15) @Wang-ZengWei (1) @StellaZYing (3) @gsq7474741 (4) @Harryoung (6)

**Comment by gsq7474741** [comment]
【报名】: 18-21

**Comment by Harryoung** [comment]
【报名】: 27-32

**Comment by Turingg** [comment]
【报名】: 1-3

**Comment by dajiang0085** [comment]
【报名】: 22-26

**Comment by hu-qi** [comment]
【报名】: 3、4、33-36

**Comment by StellaZYing** [comment]
【报名】: 11-13

**Comment by StellaZYing** [comment]
【报名】: 15-17

**Comment by Wang-ZengWei** [comment]
【报名】: 14

**Comment by Wang-ZengWei** [comment]
【报名】: 14

**Comment by hu-qi** [comment]
【报名】: 5-13

**Comment by LouisCanBe** [comment]
【报名】: 13
