### ISSUE TITLE
文档渲染异常

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/docs#6433]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.html

<img width="1728" alt="image" src="https://github.com/PaddlePaddle/docs/assets/17264618/1c577fe8-7125-43ed-bc65-a3732552d91f">

**Comment by sunzhongkai588** [comment]
@RedContritio @zhwesky2010 看看？

**Comment by RedContritio** [comment]
这个是因为合入的 [相关PR](https://github.com/PaddlePaddle/docs/pull/6394) 不符合规范，后续应该加入对增量映射文档的检查。
此外，该映射文档被 [相关PR](https://github.com/PaddlePaddle/docs/pull/6254) 进行构建后直接将构建结果加入了文档源文件，因此导致后续失去同步。

**Comment by RedContritio** [comment]
问题已修复于 #6463 ，并对于解析失败时，错误抛出中止文档构建
