### ISSUE TITLE
Binomial等API的中文代码实例显示问题

### ISSUE THREAD

**Issue by NKNaN** [PaddlePaddle/docs#6483]
### 文档链接&描述 Document Links & Description

中文代码实例没有正常显示，是什么原因呢，我可以再改一下
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distribution/Binomial_cn.html
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distribution/Poisson_cn.html
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distribution/ContinuousBernoulli_cn.html
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distribution/MultivariateNormal_cn.html
- https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/binomial_cn.html

**Comment by ooooo-create** [comment]
切换到develop是有的，这个2.6版本中文代码没有 是因为2.6版本英文还没有这个api
![image](https://github.com/PaddlePaddle/docs/assets/106524776/89d2e92d-954a-4013-a538-6551057341ba)

**Comment by NKNaN** [comment]
> 切换到develop是有的，这个2.6版本中文代码没有 是因为2.6版本英文还没有这个api ![image](https://private-user-images.githubusercontent.com/106524776/297659034-89d2e92d-954a-4013-a538-6551057341ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzIzNjYsIm5iZiI6MTcwNTU3MjA2NiwicGF0aCI6Ii8xMDY1MjQ3NzYvMjk3NjU5MDM0LTg5ZDJlOTJkLTk1NGEtNDAxMy1hNTM4LTY1NTEwNTczNDFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMDAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjU2YTRhNDZkNzJlM2YzNzkyZTE1MTZlODM3NTE5ZWJhODA3MGE1ZGEzYTg4YjljYmJiNGVhZTgxZmMzN2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uRSGXa5xmA17T-h41OcnJASp6X9skBOdVMZFwaUXTNk)

原来如此，感谢！
