### ISSUE TITLE
[docs清理] 清理未暴露在 sphinx toctree 下的文档

### ISSUE THREAD

**Issue by ooooo-create** [PaddlePaddle/docs#6491]
<h2 id="背景" class="atx">背景</h2>
<p>目前 docs 仓库中存在许多目录和文件是让我们感到困惑的，有些是和 docs 毫无关系的文件，有些是早就废弃的文件。在我们更新版本和规范的过程中，总会遇到这些神奇的文件，改也是，不改也不是。所以我们需要对现在的 docs 仓库进行一次文档清理。首先是清理一些在 Paddle 官网中找不到直接入口的文件。</p>
<blockquote>
<p>docs 仓库的文档和网页url有着一一对应的关系，可以方便的预览文件</p>
</blockquote>
<h2 id="现状" class="atx">现状</h2>
<p>docs 仓库文档大部分是使用 rst 格式编写，还有小部分 md 格式，以及 jupyter。使用 sphinx 作为构建文档的工具链。sphinx 在 Docutils （解析和处理 rst 文件） 的基础上增加了许多适用于智能生成和美化文档的指令，其中就包括 <code>.. toctree::</code> 来处理文件之间的关系。</p>
<blockquote>
<p>所有在 <em>源目录</em> （或者其子目录）必须出现在 toctree 中；如果发现文件不在 toctree 中，Sphinx将会抛出警告，因为这意味着，通过标准的导航，这个文件将是不可到达的</p>
</blockquote>
<p>我们需要对这些导航不可达的文件进行判断是否应该保留，并记录原因，借此了解此仓库的结构并可能发现更好的 docs 目录结构。</p>
<h2 id="文档列表" class="atx">文档列表</h2>

| 序号 | 文件或目录 | 是否保留 | 原因 |
| -- | -- | -- | -- |
| 1 | docs/install/install_script.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6616](https://github.com/PaddlePaddle/docs/pull/6616)<br> |   | 
| 2 | docs/install/FAQ_en.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6616](https://github.com/PaddlePaddle/docs/pull/6616)<br> |   | 
| 3 | docs/install/FAQ.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6616](https://github.com/PaddlePaddle/docs/pull/6616)<br> |   | 
| 4 | docs/guides/advanced/visualdl_cn.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6617](https://github.com/PaddlePaddle/docs/pull/6617)<br> |   | 
| 5 | docs/guides/advanced/visualdl_en.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6617](https://github.com/PaddlePaddle/docs/pull/6617)<br> |   | 
| 6 | docs/guides/jit/basic_usage_en.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6624](https://github.com/PaddlePaddle/docs/pull/6624)<br> |   | 
| 7 | docs/guides/06_distributed_training/cluster_quick_start_cn.rst |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6626](https://github.com/PaddlePaddle/docs/pull/6626)<br> |   | 
| 8 | docs/guides/06_distributed_training/cluster_quick_start_fl_ps_cn.rst |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6626](https://github.com/PaddlePaddle/docs/pull/6626) [#6641](https://github.com/PaddlePaddle/docs/pull/6641)<br> |   | 
| 9 | docs/guides/06_distributed_training/fleet_api_howto_cn.rst |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6626](https://github.com/PaddlePaddle/docs/pull/6626)<br> |   | 
| 10 | docs/guides/performance_improving/device_switching.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 11 | docs/guides/performance_improving/memory_optimize.rst |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 12 | docs/guides/performance_improving/memory_optimize_en.rst |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 13 | docs/guides/performance_improving/paddle_tensorrt_infer.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 14 | docs/guides/performance_improving/paddle_tensorrt_infer_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 15 | docs/guides/performance_improving/quantization.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 16 | docs/guides/performance_improving/analysis_tools/* |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 17 | docs/guides/model_convert/load_old_format_model_cn.rst |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6630](https://github.com/PaddlePaddle/docs/pull/6630)<br> |   | 
| 18 | docs/guides/model_convert/migration_cn.rst |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6630](https://github.com/PaddlePaddle/docs/pull/6630)<br> |   | 
| 19 | docs/guides/model_convert/update_cn.md |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6630](https://github.com/PaddlePaddle/docs/pull/6630)<br> |   | 
| 20 | ~docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 21 | ~docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 22 | ~docs/guides/model_convert/convert_from_pytorch/api_difference/*~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 23 | ~docs/guides/flags/check_nan_inf_cn.md~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 24 | ~docs/guides/flags/check_nan_inf_en.md~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 25 | ~docs/guides/flags/flags_cn.rst~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 26 | ~docs/guides/flags/flags_en.rst~ |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 27 | docs/guides/cinn/* |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6630](https://github.com/PaddlePaddle/docs/pull/6630)<br> |   | 
| 28 | docs/guides/10_contribution/* |  @Wang-ZengWei <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6630](https://github.com/PaddlePaddle/docs/pull/6630)<br> |   | 
| 29 | docs/dev_guides/api_contributing_guides/new_cpp_op_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 30 | docs/dev_guides/api_contributing_guides/new_cpp_op_notes_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 31 | docs/dev_guides/custom_device_docs/ccl_api_cn.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 32 | docs/dev_guides/custom_device_docs/custom_device_overview_cn.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 33 | ~docs/dev_guides/custom_device_docs/device_api_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 34 | ~docs/dev_guides/custom_device_docs/device_api_en.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 35 | ~docs/dev_guides/custom_device_docs/event_api_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 36 | ~docs/dev_guides/custom_device_docs/event_api_en.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 37 | ~docs/dev_guides/custom_device_docs/memory_api_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 38 | ~docs/dev_guides/custom_device_docs/memory_api_en.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 39 | ~docs/dev_guides/custom_device_docs/new_device_backend_overview_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 40 | ~docs/dev_guides/custom_device_docs/profiler_api_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 41 | ~docs/dev_guides/custom_device_docs/runtime_data_type_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 42 | ~docs/dev_guides/custom_device_docs/runtime_data_type_en.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 43 | ~docs/dev_guides/custom_device_docs/stream_api_cn.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 44 | ~docs/dev_guides/custom_device_docs/stream_api_en.md~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 45 | ~docs/dev_guides/custom_device_docs/custom_kernel_docs/*~ |  @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |   | 
| 46 | docs/dev_guides/git_guides/* |  @ooooo-create <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#6618](https://github.com/PaddlePaddle/docs/pull/6618)<br> |   | 
| 47 | docs/dev_guides/op_optimization/kernel_primitive_api/add_example_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 48 | docs/dev_guides/op_optimization/kernel_primitive_api/api_description_en.rst |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 49 | docs/dev_guides/op_optimization/kernel_primitive_api/compute_api_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 50 | docs/dev_guides/op_optimization/kernel_primitive_api/example_en.rst |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 51 | docs/dev_guides/op_optimization/kernel_primitive_api/functor_api_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 52 | docs/dev_guides/op_optimization/kernel_primitive_api/index_en.rst |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 53 | docs/dev_guides/op_optimization/kernel_primitive_api/io_api_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 54 | docs/dev_guides/op_optimization/kernel_primitive_api/model_example_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 55 | docs/dev_guides/op_optimization/kernel_primitive_api/reduce_example_en.md |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6632](https://github.com/PaddlePaddle/docs/pull/6632)<br> |   | 
| 56 | docs/eval/* |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 57 | docs/advanced_guide/* |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
| 58 | docs/design/* |  @hu-qi <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#6613](https://github.com/PaddlePaddle/docs/pull/6613)<br> |   | 
## 任务认领
> [!NOTE]
> **1. Issue 回复格式**：
>为了自动填写报名信息，需要在 issue 下回复报名信息，如果报名格式不正确，则会在 comment 区提示报名不正确，格式如下：
> ```
> 【报名】: 2、3、6-10
> ```
> > 其中【报名】:  后直接是报名的赛题序号，多个赛题之间需要用中文顿号`、`分隔，多个连续赛题可以用`横线`表示

> [!NOTE] 
> **2. PR 标题格式**：
> ```
> [Docathon][Remove File No.2、3、6-10]
> ```
> PR的标题中以 ` [Docathon][Remove File No.xxxx]` 开头即可，程序会自动提取赛题编号并更新榜单。
> 一个 PR 也可以提交多个赛题，多个赛题间以`顿号`或`横线`分隔，比如 No.24、26-28、30 赛题。

> [!NOTE] 
> **3.comment 方式**
> 先通过 **1** 的方式进行报名，然后对于自己报名的文档，重新评论一次，然后在此新的评论上维护所有报名文档的信息
> 格式如下
> | 序号 | 文件或目录 | 是否保留 | 原因 |
> | -- | -- | -- | -- |
> | xxx | xxx | 不保留 | xxx |

## 看板信息
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  Docathon  |  58  | 38 / 58 | 65.52% |  36  | 62.07% |
#####
## 统计信息 
> 排名不分先后 @Wang-ZengWei (13) @hu-qi (23) 
#####

**Comment by hu-qi** [comment]
57、58

**Comment by hu-qi** [comment]
【报名】: 10-16、29-32、56-58

**Comment by Wang-ZengWei** [comment]
【报名】: 1-9、17-28

**Comment by ooooo-create** [comment]
【报名】: 33-46

**Comment by hu-qi** [comment]
【报名】: 47-55
