### ISSUE TITLE
官网貌似没有paddle.renorm API的相关文档

### ISSUE THREAD

**Issue by Ainavo** [PaddlePaddle/docs#6508]
### 文档链接&描述 Document Links & Description

![image](https://github.com/PaddlePaddle/docs/assets/57820731/6e93eb13-21f0-43bf-b2d6-941d85bcb807)
![image](https://github.com/PaddlePaddle/docs/assets/57820731/2696cd71-13ef-45fc-9897-fc54eadad1aa)

应该是中文文档忘记加了

**Comment by sunzhongkai588** [comment]
https://github.com/PaddlePaddle/docs/pull/6625 已解决～
