### ISSUE TITLE
PyTorch 2.1.0 与 Paddle develop API 映射表格式格式有问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/docs#6582]
### 文档链接&描述 Document Links & Description

文档地址：[torch.XX API 映射列表
](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.html#torch-xx-api)

**Comment by ooooo-create** [comment]
#6605 已修复
