### ISSUE TITLE
更新昆仑芯XPU安装说明文档

### ISSUE THREAD

**Issue by micromoon779** [PaddlePaddle/docs#6682]
### 文档链接&描述 Document Links & Description

文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/hardware_support/xpu/install_cn.html
问题：昆仑芯对外的正式名称为昆仑芯，并非“昆仑”。

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

更新建议：请将本页面所有的“昆仑”更新为“昆仑芯”

**Comment by sunzhongkai588** [comment]
已由 @ooooo-create 修复 https://github.com/PaddlePaddle/docs/pull/6706
