### ISSUE TITLE
请更新昆仑芯的正式名称为"“昆仑芯”

### ISSUE THREAD

**Issue by micromoon779** [PaddlePaddle/docs#6683]
### 文档链接&描述 Document Links & Description

链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/hardware_support/xpu/install_cn.html
问题描述：昆仑芯2代已经没有R200-8FS，以及昆仑芯的正式名称不应该是“昆仑”

### 请提出你的建议/提个PR修复这个问题 Please give your suggestion/update a PR to fix it

更新建议：
1，请将本页面所有的“昆仑”替换成‘昆仑芯’
2，请删除芯片类型里面的“R200-8FS”

联系人：chenhongna01@baidu.com

**Comment by jzhang533** [comment]
你可以提个 PR 来修改， 然后 assign 给我，我来 review 和合入。
cc: @houj04 @QingshuChen

**Comment by ooooo-create** [comment]
https://github.com/PaddlePaddle/docs/pull/6684
已提交修改，@micromoon779 可以 review 一下～

**Comment by micromoon779** [comment]
> #6684 已提交修改，@micromoon779 可以 review 一下～

已review，没有问题了。
