### ISSUE TITLE
Docs 包含无效链接

### ISSUE THREAD

**Issue by zhhsplendid** [PaddlePaddle/docs#697]
在这个链接的“使用docker”编译下第8步执行cmake里，“编译选项表”是个无效链接

http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Ubuntu.html/#ubt_docker

截图如下：
<img width="691" alt="e74640c8220bb511f7e2103f4389f95f" src="https://user-images.githubusercontent.com/7913861/54508416-dc2ba480-4980-11e9-8cdf-a7935b9e8b55.png">

点进去后截图：
<img width="721" alt="485d408380be761add67b72f2b4f06bc" src="https://user-images.githubusercontent.com/7913861/54508474-f36a9200-4980-11e9-89e4-e4371a6b2e39.png">

**Comment by shanyi15** [comment]
感谢反馈，这是官网的一个bug，此前已提交需求卡片，待官网方面修复
如果在 http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/compile/compile_Ubuntu.html

这里点击“编译选项表”，则可以正确跳转

将会跳转到 
http://paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/Tables.html#permalink-2--

**Comment by shanyi15** [comment]
转为官网卡片需求~close this issue first, thanks for your feedback
