### ISSUE TITLE
doc of image_classification: lack of definition of predict

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/docs#703]
before `train_loop()` , we should add the definition of predict
```python
predict = inference_program()
```
https://github.com/PaddlePaddle/book/blob/2a6a637dc9e70d8683536fa2ef4a6d1d74fca8e0/03.image_classification/index.cn.html#L497-L501

these lines cause error: ```python NameError: name 'predict' is not defined```
https://github.com/PaddlePaddle/book/blob/2a6a637dc9e70d8683536fa2ef4a6d1d74fca8e0/03.image_classification/index.cn.html#L486-L489

**Comment by shanyi15** [comment]
Thanks for your feedback, we'll look into it
