### ISSUE TITLE
create_lod_tensor API parameters changed but doc not change

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/docs#726]
Doc use the old create_lod_tensor parameters

https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/user_guides/howto/prepare_data/feeding_data.rst

<img width="693" alt="image" src="https://user-images.githubusercontent.com/34557281/55059845-f7965e00-50aa-11e9-8d81-0ed49ffcfa90.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/34557281/55059935-39bf9f80-50ab-11e9-9073-f4290e550ab0.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/34557281/55059870-0715a700-50ab-11e9-813d-f83466b0c818.png">

**Comment by Genie-Liu** [comment]
has request a pull
https://github.com/PaddlePaddle/FluidDoc/pull/737

**Comment by shanyi15** [comment]
fixed by #737
