### ISSUE TITLE
use the wrong reader in py_reader

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/docs#730]
The definition of the reader and the reader used in py_reader not matched

https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/user_guides/howto/prepare_data/use_py_reader.rst

<img width="833" alt="image" src="https://user-images.githubusercontent.com/34557281/55122524-4b9c5380-513a-11e9-96f9-3b3ee9c882c6.png">

**Comment by Genie-Liu** [comment]
fix bug in https://github.com/PaddlePaddle/FluidDoc/pull/739

**Comment by shanyi15** [comment]
fixed by https://github.com/PaddlePaddle/FluidDoc/pull/739
