### ISSUE TITLE
add usage example for decorate_paddle_reader

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/docs#731]
In the eng version of use_py_reader, there's no usage example of decorate_paddle_reader as the one in Chinese version.

https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst

**Comment by Genie-Liu** [comment]
add more example in https://github.com/PaddlePaddle/FluidDoc/pull/740

**Comment by shanyi15** [comment]
Thanks for your contribution. Close this Issue since #740 has been merged
