### ISSUE TITLE
LRN中公式有疑问

### ISSUE THREAD

**Issue by SunAhong1993** [PaddlePaddle/docs#759]
![image](https://user-images.githubusercontent.com/48579383/55780605-ea319880-5ada-11e9-8a74-8ee4a660844b.png)
公式中的”c“代表什么没有标明，感觉修改为“i”更为合适。
（链接：http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#permalink-99-lrn）

**Comment by shanyi15** [comment]
Thanks for your feedback, we'll look into it

**Comment by qingqing01** [comment]
@SunAhong1993 感谢反馈，确实需要修改~
