### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/docs#768]
1. Dealink
2. 不知道这个文档在整体中处于什么位置
![image](https://user-images.githubusercontent.com/10721757/55878603-58f01e00-5bcf-11e9-9ca5-462d7874d124.png)

**Comment by shanyi15** [comment]
是v2的模型文档，位于models repo的legacy/目录下

**Comment by shanyi15** [comment]
官网搜索引擎策略导致搜出此文档
正在计划对搜索引擎进行优化
感谢反馈~
