### ISSUE TITLE
多版本whl包列表-Release提供的安装包地址有误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/docs#836]
http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/Tables.html#permalink-4--whl-release

这个包`win_cpu_noavx_openblas`，都是py27的

**Comment by shanyi15** [comment]
Hey yeyu, thanks for your feedback
We will look into it.

**Comment by yeyupiaoling** [comment]
OK,
