### ISSUE TITLE
关于官网文档评估指标的问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/docs#843]
![image](https://user-images.githubusercontent.com/10734244/57190763-d0a43500-6f50-11e9-86f7-624d8206d0a1.png)
accuracy_evaluator.update(value=minibatch_accuracy, weight=batch_size) 这里的minibatch_accuracy赋值给loss了，所以这里使用minibatch_accuracy会报错。
还有一个问题是这个缩进是只取每个epoch最后一个batch的训练结果吗？我用mnist三个epoch的结果值都是相同的。

**Comment by shanyi15** [comment]
Thanks for the feedback, we are fixing all the API examples now
