### ISSUE TITLE
学习率文档问题

### ISSUE THREAD

**Issue by DDDivano** [PaddlePaddle/docs#890]
http://paddlepaddle.org/documentation/docs/zh/1.4/api_cn/layers_cn.html#natural-exp-decay
![image](https://user-images.githubusercontent.com/10734244/59328004-d47c6180-8d1d-11e9-8e33-5823d7458f95.png)
这两个分支有什么区别吗？

**Comment by shanyi15** [comment]
英文文档也同样有问题，辛苦 @xsrobin 安排同学修复
